// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
  external_id,
  disease_id,
  district_id,
  epi_week_id,
  occurred_on,
  created_on,
  narrative,
  submitted_by,
  status,
  source_name
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, external_id, disease_id, district_id, epi_week_id, occurred_on, created_on, narrative, submitted_by, status, source_name, imported_at, created_at, updated_at
`

type CreateAlertParams struct {
	ExternalID  sql.NullString `json:"external_id"`
	DiseaseID   uuid.UUID      `json:"disease_id"`
	DistrictID  uuid.NullUUID  `json:"district_id"`
	EpiWeekID   uuid.NullUUID  `json:"epi_week_id"`
	OccurredOn  sql.NullTime   `json:"occurred_on"`
	CreatedOn   sql.NullTime   `json:"created_on"`
	Narrative   string         `json:"narrative"`
	SubmittedBy sql.NullString `json:"submitted_by"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, createAlert,
		arg.ExternalID,
		arg.DiseaseID,
		arg.DistrictID,
		arg.EpiWeekID,
		arg.OccurredOn,
		arg.CreatedOn,
		arg.Narrative,
		arg.SubmittedBy,
		arg.Status,
		arg.SourceName,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.DiseaseID,
		&i.DistrictID,
		&i.EpiWeekID,
		&i.OccurredOn,
		&i.CreatedOn,
		&i.Narrative,
		&i.SubmittedBy,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, external_id, disease_id, district_id, epi_week_id, occurred_on, created_on, narrative, submitted_by, status, source_name, imported_at, created_at, updated_at
FROM alerts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAlertByID(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRowContext(ctx, getAlertByID, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.DiseaseID,
		&i.DistrictID,
		&i.EpiWeekID,
		&i.OccurredOn,
		&i.CreatedOn,
		&i.Narrative,
		&i.SubmittedBy,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT
  a.id, a.external_id, a.disease_id, a.district_id, a.epi_week_id, a.occurred_on, a.created_on, a.narrative, a.submitted_by, a.status, a.source_name, a.imported_at, a.created_at, a.updated_at,
  d.name AS disease_name,
  dist.name AS district_name,
  ew.epi_year,
  ew.epi_week
FROM alerts a
JOIN diseases d ON d.id = a.disease_id
LEFT JOIN districts dist ON dist.id = a.district_id
LEFT JOIN epi_weeks ew ON ew.id = a.epi_week_id
ORDER BY a.created_on DESC, a.created_at DESC
`

type ListAlertsRow struct {
	ID           uuid.UUID      `json:"id"`
	ExternalID   sql.NullString `json:"external_id"`
	DiseaseID    uuid.UUID      `json:"disease_id"`
	DistrictID   uuid.NullUUID  `json:"district_id"`
	EpiWeekID    uuid.NullUUID  `json:"epi_week_id"`
	OccurredOn   sql.NullTime   `json:"occurred_on"`
	CreatedOn    sql.NullTime   `json:"created_on"`
	Narrative    string         `json:"narrative"`
	SubmittedBy  sql.NullString `json:"submitted_by"`
	Status       interface{}    `json:"status"`
	SourceName   sql.NullString `json:"source_name"`
	ImportedAt   time.Time      `json:"imported_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DiseaseName  string         `json:"disease_name"`
	DistrictName sql.NullString `json:"district_name"`
	EpiYear      sql.NullInt32  `json:"epi_year"`
	EpiWeek      sql.NullInt32  `json:"epi_week"`
}

func (q *Queries) ListAlerts(ctx context.Context) ([]ListAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsRow{}
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.DiseaseID,
			&i.DistrictID,
			&i.EpiWeekID,
			&i.OccurredOn,
			&i.CreatedOn,
			&i.Narrative,
			&i.SubmittedBy,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DiseaseName,
			&i.DistrictName,
			&i.EpiYear,
			&i.EpiWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByDisease = `-- name: ListAlertsByDisease :many
SELECT
  a.id, a.external_id, a.disease_id, a.district_id, a.epi_week_id, a.occurred_on, a.created_on, a.narrative, a.submitted_by, a.status, a.source_name, a.imported_at, a.created_at, a.updated_at,
  dist.name AS district_name,
  ew.epi_year,
  ew.epi_week
FROM alerts a
LEFT JOIN districts dist ON dist.id = a.district_id
LEFT JOIN epi_weeks ew ON ew.id = a.epi_week_id
WHERE a.disease_id = $1
ORDER BY a.created_on DESC, a.created_at DESC
`

type ListAlertsByDiseaseRow struct {
	ID           uuid.UUID      `json:"id"`
	ExternalID   sql.NullString `json:"external_id"`
	DiseaseID    uuid.UUID      `json:"disease_id"`
	DistrictID   uuid.NullUUID  `json:"district_id"`
	EpiWeekID    uuid.NullUUID  `json:"epi_week_id"`
	OccurredOn   sql.NullTime   `json:"occurred_on"`
	CreatedOn    sql.NullTime   `json:"created_on"`
	Narrative    string         `json:"narrative"`
	SubmittedBy  sql.NullString `json:"submitted_by"`
	Status       interface{}    `json:"status"`
	SourceName   sql.NullString `json:"source_name"`
	ImportedAt   time.Time      `json:"imported_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DistrictName sql.NullString `json:"district_name"`
	EpiYear      sql.NullInt32  `json:"epi_year"`
	EpiWeek      sql.NullInt32  `json:"epi_week"`
}

func (q *Queries) ListAlertsByDisease(ctx context.Context, diseaseID uuid.UUID) ([]ListAlertsByDiseaseRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsByDisease, diseaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsByDiseaseRow{}
	for rows.Next() {
		var i ListAlertsByDiseaseRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.DiseaseID,
			&i.DistrictID,
			&i.EpiWeekID,
			&i.OccurredOn,
			&i.CreatedOn,
			&i.Narrative,
			&i.SubmittedBy,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DistrictName,
			&i.EpiYear,
			&i.EpiWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByDistrict = `-- name: ListAlertsByDistrict :many
SELECT
  a.id, a.external_id, a.disease_id, a.district_id, a.epi_week_id, a.occurred_on, a.created_on, a.narrative, a.submitted_by, a.status, a.source_name, a.imported_at, a.created_at, a.updated_at,
  d.name AS disease_name,
  ew.epi_year,
  ew.epi_week
FROM alerts a
JOIN diseases d ON d.id = a.disease_id
LEFT JOIN epi_weeks ew ON ew.id = a.epi_week_id
WHERE a.district_id = $1
ORDER BY a.created_on DESC, a.created_at DESC
`

type ListAlertsByDistrictRow struct {
	ID          uuid.UUID      `json:"id"`
	ExternalID  sql.NullString `json:"external_id"`
	DiseaseID   uuid.UUID      `json:"disease_id"`
	DistrictID  uuid.NullUUID  `json:"district_id"`
	EpiWeekID   uuid.NullUUID  `json:"epi_week_id"`
	OccurredOn  sql.NullTime   `json:"occurred_on"`
	CreatedOn   sql.NullTime   `json:"created_on"`
	Narrative   string         `json:"narrative"`
	SubmittedBy sql.NullString `json:"submitted_by"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
	ImportedAt  time.Time      `json:"imported_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DiseaseName string         `json:"disease_name"`
	EpiYear     sql.NullInt32  `json:"epi_year"`
	EpiWeek     sql.NullInt32  `json:"epi_week"`
}

func (q *Queries) ListAlertsByDistrict(ctx context.Context, districtID uuid.NullUUID) ([]ListAlertsByDistrictRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsByDistrict, districtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsByDistrictRow{}
	for rows.Next() {
		var i ListAlertsByDistrictRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.DiseaseID,
			&i.DistrictID,
			&i.EpiWeekID,
			&i.OccurredOn,
			&i.CreatedOn,
			&i.Narrative,
			&i.SubmittedBy,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DiseaseName,
			&i.EpiYear,
			&i.EpiWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByWeek = `-- name: ListAlertsByWeek :many
SELECT
  a.id, a.external_id, a.disease_id, a.district_id, a.epi_week_id, a.occurred_on, a.created_on, a.narrative, a.submitted_by, a.status, a.source_name, a.imported_at, a.created_at, a.updated_at,
  d.name AS disease_name,
  dist.name AS district_name
FROM alerts a
JOIN diseases d ON d.id = a.disease_id
LEFT JOIN districts dist ON dist.id = a.district_id
WHERE a.epi_week_id = $1
ORDER BY a.created_on DESC, a.created_at DESC
`

type ListAlertsByWeekRow struct {
	ID           uuid.UUID      `json:"id"`
	ExternalID   sql.NullString `json:"external_id"`
	DiseaseID    uuid.UUID      `json:"disease_id"`
	DistrictID   uuid.NullUUID  `json:"district_id"`
	EpiWeekID    uuid.NullUUID  `json:"epi_week_id"`
	OccurredOn   sql.NullTime   `json:"occurred_on"`
	CreatedOn    sql.NullTime   `json:"created_on"`
	Narrative    string         `json:"narrative"`
	SubmittedBy  sql.NullString `json:"submitted_by"`
	Status       interface{}    `json:"status"`
	SourceName   sql.NullString `json:"source_name"`
	ImportedAt   time.Time      `json:"imported_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DiseaseName  string         `json:"disease_name"`
	DistrictName sql.NullString `json:"district_name"`
}

func (q *Queries) ListAlertsByWeek(ctx context.Context, epiWeekID uuid.NullUUID) ([]ListAlertsByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertsByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsByWeekRow{}
	for rows.Next() {
		var i ListAlertsByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.DiseaseID,
			&i.DistrictID,
			&i.EpiWeekID,
			&i.OccurredOn,
			&i.CreatedOn,
			&i.Narrative,
			&i.SubmittedBy,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DiseaseName,
			&i.DistrictName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlertStatus = `-- name: UpdateAlertStatus :one
UPDATE alerts
SET
  status = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, external_id, disease_id, district_id, epi_week_id, occurred_on, created_on, narrative, submitted_by, status, source_name, imported_at, created_at, updated_at
`

type UpdateAlertStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status interface{} `json:"status"`
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, updateAlertStatus, arg.ID, arg.Status)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.DiseaseID,
		&i.DistrictID,
		&i.EpiWeekID,
		&i.OccurredOn,
		&i.CreatedOn,
		&i.Narrative,
		&i.SubmittedBy,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAlertByExternalID = `-- name: UpsertAlertByExternalID :one
INSERT INTO alerts (
  external_id,
  disease_id,
  district_id,
  epi_week_id,
  occurred_on,
  created_on,
  narrative,
  submitted_by,
  status,
  source_name
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (external_id)
DO UPDATE SET
  disease_id = EXCLUDED.disease_id,
  district_id = EXCLUDED.district_id,
  epi_week_id = EXCLUDED.epi_week_id,
  occurred_on = EXCLUDED.occurred_on,
  created_on = EXCLUDED.created_on,
  narrative = EXCLUDED.narrative,
  submitted_by = EXCLUDED.submitted_by,
  status = EXCLUDED.status,
  source_name = COALESCE(EXCLUDED.source_name, alerts.source_name),
  imported_at = now(),
  updated_at = now()
RETURNING id, external_id, disease_id, district_id, epi_week_id, occurred_on, created_on, narrative, submitted_by, status, source_name, imported_at, created_at, updated_at
`

type UpsertAlertByExternalIDParams struct {
	ExternalID  sql.NullString `json:"external_id"`
	DiseaseID   uuid.UUID      `json:"disease_id"`
	DistrictID  uuid.NullUUID  `json:"district_id"`
	EpiWeekID   uuid.NullUUID  `json:"epi_week_id"`
	OccurredOn  sql.NullTime   `json:"occurred_on"`
	CreatedOn   sql.NullTime   `json:"created_on"`
	Narrative   string         `json:"narrative"`
	SubmittedBy sql.NullString `json:"submitted_by"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
}

func (q *Queries) UpsertAlertByExternalID(ctx context.Context, arg UpsertAlertByExternalIDParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, upsertAlertByExternalID,
		arg.ExternalID,
		arg.DiseaseID,
		arg.DistrictID,
		arg.EpiWeekID,
		arg.OccurredOn,
		arg.CreatedOn,
		arg.Narrative,
		arg.SubmittedBy,
		arg.Status,
		arg.SourceName,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.DiseaseID,
		&i.DistrictID,
		&i.EpiWeekID,
		&i.OccurredOn,
		&i.CreatedOn,
		&i.Narrative,
		&i.SubmittedBy,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
