// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getDiseaseDashboardSummaryByWeek = `-- name: GetDiseaseDashboardSummaryByWeek :one
SELECT
  d.id AS disease_id,
  d.name AS disease_name,
  COALESCE((
    SELECT SUM(m.metric_value)::numeric
    FROM facility_weekly_metrics m
    WHERE m.disease_id = d.id
      AND m.epi_week_id = $2
  ), 0) AS facility_total,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM district_weekly_status ds
    WHERE ds.disease_id = d.id
      AND ds.epi_week_id = $2
      AND ds.status = 'MAROON'
  ), 0) AS maroon_districts,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM district_weekly_status ds
    WHERE ds.disease_id = d.id
      AND ds.epi_week_id = $2
      AND ds.status = 'RED'
  ), 0) AS red_districts,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM district_weekly_status ds
    WHERE ds.disease_id = d.id
      AND ds.epi_week_id = $2
      AND ds.status = 'YELLOW'
  ), 0) AS yellow_districts,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM district_weekly_status ds
    WHERE ds.disease_id = d.id
      AND ds.epi_week_id = $2
      AND ds.status = 'GREEN'
  ), 0) AS green_districts,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM alerts a
    WHERE a.disease_id = d.id
      AND a.epi_week_id = $2
  ), 0) AS total_alerts
FROM diseases d
WHERE d.id = $1
LIMIT 1
`

type GetDiseaseDashboardSummaryByWeekParams struct {
	ID        uuid.UUID `json:"id"`
	EpiWeekID uuid.UUID `json:"epi_week_id"`
}

type GetDiseaseDashboardSummaryByWeekRow struct {
	DiseaseID       uuid.UUID   `json:"disease_id"`
	DiseaseName     string      `json:"disease_name"`
	FacilityTotal   interface{} `json:"facility_total"`
	MaroonDistricts interface{} `json:"maroon_districts"`
	RedDistricts    interface{} `json:"red_districts"`
	YellowDistricts interface{} `json:"yellow_districts"`
	GreenDistricts  interface{} `json:"green_districts"`
	TotalAlerts     interface{} `json:"total_alerts"`
}

func (q *Queries) GetDiseaseDashboardSummaryByWeek(ctx context.Context, arg GetDiseaseDashboardSummaryByWeekParams) (GetDiseaseDashboardSummaryByWeekRow, error) {
	row := q.db.QueryRowContext(ctx, getDiseaseDashboardSummaryByWeek, arg.ID, arg.EpiWeekID)
	var i GetDiseaseDashboardSummaryByWeekRow
	err := row.Scan(
		&i.DiseaseID,
		&i.DiseaseName,
		&i.FacilityTotal,
		&i.MaroonDistricts,
		&i.RedDistricts,
		&i.YellowDistricts,
		&i.GreenDistricts,
		&i.TotalAlerts,
	)
	return i, err
}

const getIndicatorDashboardSummaryByWeek = `-- name: GetIndicatorDashboardSummaryByWeek :one
SELECT
  i.id AS indicator_id,
  i.name AS indicator_name,
  COALESCE((
    SELECT SUM(m.metric_value)::numeric
    FROM facility_weekly_metrics m
    WHERE m.indicator_id = i.id
      AND m.epi_week_id = $2
  ), 0) AS facility_total,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM district_weekly_status ds
    WHERE ds.indicator_id = i.id
      AND ds.epi_week_id = $2
      AND ds.status = 'MAROON'
  ), 0) AS maroon_districts,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM district_weekly_status ds
    WHERE ds.indicator_id = i.id
      AND ds.epi_week_id = $2
      AND ds.status = 'RED'
  ), 0) AS red_districts,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM district_weekly_status ds
    WHERE ds.indicator_id = i.id
      AND ds.epi_week_id = $2
      AND ds.status = 'YELLOW'
  ), 0) AS yellow_districts,
  COALESCE((
    SELECT COUNT(*)::bigint
    FROM district_weekly_status ds
    WHERE ds.indicator_id = i.id
      AND ds.epi_week_id = $2
      AND ds.status = 'GREEN'
  ), 0) AS green_districts
FROM indicators i
WHERE i.id = $1
LIMIT 1
`

type GetIndicatorDashboardSummaryByWeekParams struct {
	ID        uuid.UUID `json:"id"`
	EpiWeekID uuid.UUID `json:"epi_week_id"`
}

type GetIndicatorDashboardSummaryByWeekRow struct {
	IndicatorID     uuid.UUID   `json:"indicator_id"`
	IndicatorName   string      `json:"indicator_name"`
	FacilityTotal   interface{} `json:"facility_total"`
	MaroonDistricts interface{} `json:"maroon_districts"`
	RedDistricts    interface{} `json:"red_districts"`
	YellowDistricts interface{} `json:"yellow_districts"`
	GreenDistricts  interface{} `json:"green_districts"`
}

func (q *Queries) GetIndicatorDashboardSummaryByWeek(ctx context.Context, arg GetIndicatorDashboardSummaryByWeekParams) (GetIndicatorDashboardSummaryByWeekRow, error) {
	row := q.db.QueryRowContext(ctx, getIndicatorDashboardSummaryByWeek, arg.ID, arg.EpiWeekID)
	var i GetIndicatorDashboardSummaryByWeekRow
	err := row.Scan(
		&i.IndicatorID,
		&i.IndicatorName,
		&i.FacilityTotal,
		&i.MaroonDistricts,
		&i.RedDistricts,
		&i.YellowDistricts,
		&i.GreenDistricts,
	)
	return i, err
}

const getNationalWeeklyStatusSummary = `-- name: GetNationalWeeklyStatusSummary :many
SELECT
  status,
  COUNT(*)::bigint AS total_items
FROM (
  SELECT status
  FROM national_weekly_status
  WHERE epi_week_id = $1
) x
GROUP BY status
ORDER BY
  CASE status
    WHEN 'MAROON' THEN 1
    WHEN 'RED' THEN 2
    WHEN 'YELLOW' THEN 3
    WHEN 'GREEN' THEN 4
  END
`

type GetNationalWeeklyStatusSummaryRow struct {
	Status     interface{} `json:"status"`
	TotalItems int64       `json:"total_items"`
}

func (q *Queries) GetNationalWeeklyStatusSummary(ctx context.Context, epiWeekID uuid.UUID) ([]GetNationalWeeklyStatusSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, getNationalWeeklyStatusSummary, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNationalWeeklyStatusSummaryRow{}
	for rows.Next() {
		var i GetNationalWeeklyStatusSummaryRow
		if err := rows.Scan(&i.Status, &i.TotalItems); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopFacilitiesByDiseaseAndWeek = `-- name: GetTopFacilitiesByDiseaseAndWeek :many
SELECT
  f.id AS facility_id,
  f.name AS facility_name,
  d.name AS district_name,
  r.name AS region_name,
  m.metric_value
FROM facility_weekly_metrics m
JOIN facilities f ON f.id = m.facility_id
LEFT JOIN districts d ON d.id = f.district_id
LEFT JOIN regions r ON r.id = f.region_id
WHERE m.disease_id = $1
  AND m.epi_week_id = $2
ORDER BY m.metric_value DESC, f.name ASC
LIMIT $3
`

type GetTopFacilitiesByDiseaseAndWeekParams struct {
	DiseaseID uuid.UUID `json:"disease_id"`
	EpiWeekID uuid.UUID `json:"epi_week_id"`
	Limit     int32     `json:"limit"`
}

type GetTopFacilitiesByDiseaseAndWeekRow struct {
	FacilityID   uuid.UUID      `json:"facility_id"`
	FacilityName string         `json:"facility_name"`
	DistrictName sql.NullString `json:"district_name"`
	RegionName   sql.NullString `json:"region_name"`
	MetricValue  string         `json:"metric_value"`
}

func (q *Queries) GetTopFacilitiesByDiseaseAndWeek(ctx context.Context, arg GetTopFacilitiesByDiseaseAndWeekParams) ([]GetTopFacilitiesByDiseaseAndWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopFacilitiesByDiseaseAndWeek, arg.DiseaseID, arg.EpiWeekID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopFacilitiesByDiseaseAndWeekRow{}
	for rows.Next() {
		var i GetTopFacilitiesByDiseaseAndWeekRow
		if err := rows.Scan(
			&i.FacilityID,
			&i.FacilityName,
			&i.DistrictName,
			&i.RegionName,
			&i.MetricValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopFacilitiesByIndicatorAndWeek = `-- name: GetTopFacilitiesByIndicatorAndWeek :many
SELECT
  f.id AS facility_id,
  f.name AS facility_name,
  d.name AS district_name,
  r.name AS region_name,
  m.metric_value
FROM facility_weekly_metrics m
JOIN facilities f ON f.id = m.facility_id
LEFT JOIN districts d ON d.id = f.district_id
LEFT JOIN regions r ON r.id = f.region_id
WHERE m.indicator_id = $1
  AND m.epi_week_id = $2
ORDER BY m.metric_value DESC, f.name ASC
LIMIT $3
`

type GetTopFacilitiesByIndicatorAndWeekParams struct {
	IndicatorID uuid.UUID `json:"indicator_id"`
	EpiWeekID   uuid.UUID `json:"epi_week_id"`
	Limit       int32     `json:"limit"`
}

type GetTopFacilitiesByIndicatorAndWeekRow struct {
	FacilityID   uuid.UUID      `json:"facility_id"`
	FacilityName string         `json:"facility_name"`
	DistrictName sql.NullString `json:"district_name"`
	RegionName   sql.NullString `json:"region_name"`
	MetricValue  string         `json:"metric_value"`
}

func (q *Queries) GetTopFacilitiesByIndicatorAndWeek(ctx context.Context, arg GetTopFacilitiesByIndicatorAndWeekParams) ([]GetTopFacilitiesByIndicatorAndWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopFacilitiesByIndicatorAndWeek, arg.IndicatorID, arg.EpiWeekID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopFacilitiesByIndicatorAndWeekRow{}
	for rows.Next() {
		var i GetTopFacilitiesByIndicatorAndWeekRow
		if err := rows.Scan(
			&i.FacilityID,
			&i.FacilityName,
			&i.DistrictName,
			&i.RegionName,
			&i.MetricValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklySubjectTotals = `-- name: GetWeeklySubjectTotals :many
SELECT
  d.id AS subject_id,
  d.name AS subject_name,
  'DISEASE' AS subject_type,
  SUM(m.metric_value)::numeric AS total_value
FROM facility_weekly_metrics m
JOIN diseases d ON d.id = m.disease_id
WHERE m.epi_week_id = $1
  AND m.disease_id IS NOT NULL
GROUP BY d.id, d.name

UNION ALL

SELECT
  i.id AS subject_id,
  i.name AS subject_name,
  'INDICATOR' AS subject_type,
  SUM(m.metric_value)::numeric AS total_value
FROM facility_weekly_metrics m
JOIN indicators i ON i.id = m.indicator_id
WHERE m.epi_week_id = $1
  AND m.indicator_id IS NOT NULL
GROUP BY i.id, i.name

ORDER BY total_value DESC, subject_name ASC
`

type GetWeeklySubjectTotalsRow struct {
	SubjectID   uuid.UUID `json:"subject_id"`
	SubjectName string    `json:"subject_name"`
	SubjectType string    `json:"subject_type"`
	TotalValue  string    `json:"total_value"`
}

func (q *Queries) GetWeeklySubjectTotals(ctx context.Context, epiWeekID uuid.UUID) ([]GetWeeklySubjectTotalsRow, error) {
	rows, err := q.db.QueryContext(ctx, getWeeklySubjectTotals, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWeeklySubjectTotalsRow{}
	for rows.Next() {
		var i GetWeeklySubjectTotalsRow
		if err := rows.Scan(
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectType,
			&i.TotalValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistrictWeeklySubjectsByWeek = `-- name: ListDistrictWeeklySubjectsByWeek :many
SELECT
  s.id,
  s.district_id,
  d.name AS district_name,
  s.epi_week_id,
  s.status,
  s.source_name,
  dis.id AS subject_id,
  dis.name AS subject_name,
  'DISEASE' AS subject_type
FROM district_weekly_status s
JOIN districts d ON d.id = s.district_id
JOIN diseases dis ON dis.id = s.disease_id
WHERE s.epi_week_id = $1
  AND s.disease_id IS NOT NULL

UNION ALL

SELECT
  s.id,
  s.district_id,
  d.name AS district_name,
  s.epi_week_id,
  s.status,
  s.source_name,
  i.id AS subject_id,
  i.name AS subject_name,
  'INDICATOR' AS subject_type
FROM district_weekly_status s
JOIN districts d ON d.id = s.district_id
JOIN indicators i ON i.id = s.indicator_id
WHERE s.epi_week_id = $1
  AND s.indicator_id IS NOT NULL

ORDER BY district_name ASC, status ASC, subject_name ASC
`

type ListDistrictWeeklySubjectsByWeekRow struct {
	ID           uuid.UUID      `json:"id"`
	DistrictID   uuid.UUID      `json:"district_id"`
	DistrictName string         `json:"district_name"`
	EpiWeekID    uuid.UUID      `json:"epi_week_id"`
	Status       interface{}    `json:"status"`
	SourceName   sql.NullString `json:"source_name"`
	SubjectID    uuid.UUID      `json:"subject_id"`
	SubjectName  string         `json:"subject_name"`
	SubjectType  string         `json:"subject_type"`
}

func (q *Queries) ListDistrictWeeklySubjectsByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListDistrictWeeklySubjectsByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistrictWeeklySubjectsByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistrictWeeklySubjectsByWeekRow{}
	for rows.Next() {
		var i ListDistrictWeeklySubjectsByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.DistrictID,
			&i.DistrictName,
			&i.EpiWeekID,
			&i.Status,
			&i.SourceName,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNationalWeeklySubjectsByWeek = `-- name: ListNationalWeeklySubjectsByWeek :many
SELECT
  s.id,
  s.epi_week_id,
  s.status,
  s.source_name,
  s.imported_at,
  s.created_at,
  d.id AS subject_id,
  d.name AS subject_name,
  'DISEASE' AS subject_type
FROM national_weekly_status s
JOIN diseases d ON d.id = s.disease_id
WHERE s.epi_week_id = $1
  AND s.disease_id IS NOT NULL

UNION ALL

SELECT
  s.id,
  s.epi_week_id,
  s.status,
  s.source_name,
  s.imported_at,
  s.created_at,
  i.id AS subject_id,
  i.name AS subject_name,
  'INDICATOR' AS subject_type
FROM national_weekly_status s
JOIN indicators i ON i.id = s.indicator_id
WHERE s.epi_week_id = $1
  AND s.indicator_id IS NOT NULL

ORDER BY status, subject_name
`

type ListNationalWeeklySubjectsByWeekRow struct {
	ID          uuid.UUID      `json:"id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
	ImportedAt  time.Time      `json:"imported_at"`
	CreatedAt   time.Time      `json:"created_at"`
	SubjectID   uuid.UUID      `json:"subject_id"`
	SubjectName string         `json:"subject_name"`
	SubjectType string         `json:"subject_type"`
}

func (q *Queries) ListNationalWeeklySubjectsByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListNationalWeeklySubjectsByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listNationalWeeklySubjectsByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNationalWeeklySubjectsByWeekRow{}
	for rows.Next() {
		var i ListNationalWeeklySubjectsByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.EpiWeekID,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegionWeeklySubjectsByWeek = `-- name: ListRegionWeeklySubjectsByWeek :many
SELECT
  s.id,
  s.region_id,
  r.name AS region_name,
  s.epi_week_id,
  s.status,
  s.source_name,
  dis.id AS subject_id,
  dis.name AS subject_name,
  'DISEASE' AS subject_type
FROM region_weekly_status s
JOIN regions r ON r.id = s.region_id
JOIN diseases dis ON dis.id = s.disease_id
WHERE s.epi_week_id = $1
  AND s.disease_id IS NOT NULL

UNION ALL

SELECT
  s.id,
  s.region_id,
  r.name AS region_name,
  s.epi_week_id,
  s.status,
  s.source_name,
  i.id AS subject_id,
  i.name AS subject_name,
  'INDICATOR' AS subject_type
FROM region_weekly_status s
JOIN regions r ON r.id = s.region_id
JOIN indicators i ON i.id = s.indicator_id
WHERE s.epi_week_id = $1
  AND s.indicator_id IS NOT NULL

ORDER BY region_name ASC, status ASC, subject_name ASC
`

type ListRegionWeeklySubjectsByWeekRow struct {
	ID          uuid.UUID      `json:"id"`
	RegionID    uuid.UUID      `json:"region_id"`
	RegionName  string         `json:"region_name"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
	SubjectID   uuid.UUID      `json:"subject_id"`
	SubjectName string         `json:"subject_name"`
	SubjectType string         `json:"subject_type"`
}

func (q *Queries) ListRegionWeeklySubjectsByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListRegionWeeklySubjectsByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listRegionWeeklySubjectsByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegionWeeklySubjectsByWeekRow{}
	for rows.Next() {
		var i ListRegionWeeklySubjectsByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.RegionName,
			&i.EpiWeekID,
			&i.Status,
			&i.SourceName,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
