// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diseases.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDisease = `-- name: CreateDisease :one
INSERT INTO diseases (
  name,
  short_name,
  code,
  category
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, short_name, code, category, is_active, created_at, updated_at
`

type CreateDiseaseParams struct {
	Name      string         `json:"name"`
	ShortName sql.NullString `json:"short_name"`
	Code      sql.NullString `json:"code"`
	Category  sql.NullString `json:"category"`
}

func (q *Queries) CreateDisease(ctx context.Context, arg CreateDiseaseParams) (Disease, error) {
	row := q.db.QueryRowContext(ctx, createDisease,
		arg.Name,
		arg.ShortName,
		arg.Code,
		arg.Category,
	)
	var i Disease
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDisease = `-- name: DeleteDisease :exec
DELETE FROM diseases
WHERE id = $1
`

func (q *Queries) DeleteDisease(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDisease, id)
	return err
}

const getDiseaseByID = `-- name: GetDiseaseByID :one
SELECT id, name, short_name, code, category, is_active, created_at, updated_at
FROM diseases
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDiseaseByID(ctx context.Context, id uuid.UUID) (Disease, error) {
	row := q.db.QueryRowContext(ctx, getDiseaseByID, id)
	var i Disease
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiseaseByName = `-- name: GetDiseaseByName :one
SELECT id, name, short_name, code, category, is_active, created_at, updated_at
FROM diseases
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetDiseaseByName(ctx context.Context, lower string) (Disease, error) {
	row := q.db.QueryRowContext(ctx, getDiseaseByName, lower)
	var i Disease
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveDiseases = `-- name: ListActiveDiseases :many
SELECT id, name, short_name, code, category, is_active, created_at, updated_at
FROM diseases
WHERE is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListActiveDiseases(ctx context.Context) ([]Disease, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDiseases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Disease{}
	for rows.Next() {
		var i Disease
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.Code,
			&i.Category,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiseases = `-- name: ListDiseases :many
SELECT id, name, short_name, code, category, is_active, created_at, updated_at
FROM diseases
ORDER BY name ASC
`

func (q *Queries) ListDiseases(ctx context.Context) ([]Disease, error) {
	rows, err := q.db.QueryContext(ctx, listDiseases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Disease{}
	for rows.Next() {
		var i Disease
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.Code,
			&i.Category,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDiseaseActiveState = `-- name: SetDiseaseActiveState :one
UPDATE diseases
SET
  is_active = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, name, short_name, code, category, is_active, created_at, updated_at
`

type SetDiseaseActiveStateParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetDiseaseActiveState(ctx context.Context, arg SetDiseaseActiveStateParams) (Disease, error) {
	row := q.db.QueryRowContext(ctx, setDiseaseActiveState, arg.ID, arg.IsActive)
	var i Disease
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDisease = `-- name: UpsertDisease :one
INSERT INTO diseases (
  name,
  short_name,
  code,
  category
) VALUES (
  $1, $2, $3, $4
)
ON CONFLICT (name)
DO UPDATE SET
  short_name = COALESCE(EXCLUDED.short_name, diseases.short_name),
  code = COALESCE(EXCLUDED.code, diseases.code),
  category = COALESCE(EXCLUDED.category, diseases.category),
  updated_at = now()
RETURNING id, name, short_name, code, category, is_active, created_at, updated_at
`

type UpsertDiseaseParams struct {
	Name      string         `json:"name"`
	ShortName sql.NullString `json:"short_name"`
	Code      sql.NullString `json:"code"`
	Category  sql.NullString `json:"category"`
}

func (q *Queries) UpsertDisease(ctx context.Context, arg UpsertDiseaseParams) (Disease, error) {
	row := q.db.QueryRowContext(ctx, upsertDisease,
		arg.Name,
		arg.ShortName,
		arg.Code,
		arg.Category,
	)
	var i Disease
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
