// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: districts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDistrict = `-- name: CreateDistrict :one
INSERT INTO districts (
  name,
  region_id,
  code
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id, name, region_id, code, created_at, updated_at
`

type CreateDistrictParams struct {
	Name     string         `json:"name"`
	RegionID uuid.NullUUID  `json:"region_id"`
	Code     sql.NullString `json:"code"`
}

func (q *Queries) CreateDistrict(ctx context.Context, arg CreateDistrictParams) (District, error) {
	row := q.db.QueryRowContext(ctx, createDistrict, arg.Name, arg.RegionID, arg.Code)
	var i District
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDistrict = `-- name: DeleteDistrict :exec
DELETE FROM districts
WHERE id = $1
`

func (q *Queries) DeleteDistrict(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDistrict, id)
	return err
}

const getDistrictByID = `-- name: GetDistrictByID :one
SELECT id, name, region_id, code, created_at, updated_at
FROM districts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDistrictByID(ctx context.Context, id uuid.UUID) (District, error) {
	row := q.db.QueryRowContext(ctx, getDistrictByID, id)
	var i District
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDistrictByName = `-- name: GetDistrictByName :one
SELECT id, name, region_id, code, created_at, updated_at
FROM districts
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetDistrictByName(ctx context.Context, lower string) (District, error) {
	row := q.db.QueryRowContext(ctx, getDistrictByName, lower)
	var i District
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistricts = `-- name: ListDistricts :many
SELECT d.id, d.name, d.region_id, d.code, d.created_at, d.updated_at, r.name AS region_name
FROM districts d
LEFT JOIN regions r ON r.id = d.region_id
ORDER BY d.name ASC
`

type ListDistrictsRow struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	RegionID   uuid.NullUUID  `json:"region_id"`
	Code       sql.NullString `json:"code"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	RegionName sql.NullString `json:"region_name"`
}

func (q *Queries) ListDistricts(ctx context.Context) ([]ListDistrictsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistricts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistrictsRow{}
	for rows.Next() {
		var i ListDistrictsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RegionID,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistrictsByRegion = `-- name: ListDistrictsByRegion :many
SELECT id, name, region_id, code, created_at, updated_at
FROM districts
WHERE region_id = $1
ORDER BY name ASC
`

func (q *Queries) ListDistrictsByRegion(ctx context.Context, regionID uuid.NullUUID) ([]District, error) {
	rows, err := q.db.QueryContext(ctx, listDistrictsByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []District{}
	for rows.Next() {
		var i District
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RegionID,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistrictsByRegionInHealthContext = `-- name: ListDistrictsByRegionInHealthContext :many
SELECT id, name, region_id, code, created_at, updated_at
FROM districts
WHERE region_id = $1
  AND health_context_alias_related_to_scope(
    'surveillance-district',
    id::text,
    $2::uuid,
    $3::boolean
  )
ORDER BY name ASC
`

type ListDistrictsByRegionInHealthContextParams struct {
	RegionID           uuid.NullUUID `json:"region_id"`
	HealthContextID    uuid.UUID     `json:"health_context_id"`
	IncludeDescendants bool          `json:"include_descendants"`
}

func (q *Queries) ListDistrictsByRegionInHealthContext(ctx context.Context, arg ListDistrictsByRegionInHealthContextParams) ([]District, error) {
	rows, err := q.db.QueryContext(ctx, listDistrictsByRegionInHealthContext, arg.RegionID, arg.HealthContextID, arg.IncludeDescendants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []District{}
	for rows.Next() {
		var i District
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RegionID,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistrictsInHealthContext = `-- name: ListDistrictsInHealthContext :many
SELECT d.id, d.name, d.region_id, d.code, d.created_at, d.updated_at, r.name AS region_name
FROM districts d
LEFT JOIN regions r ON r.id = d.region_id
WHERE health_context_alias_related_to_scope(
  'surveillance-district',
  d.id::text,
  $1::uuid,
  $2::boolean
)
ORDER BY d.name ASC
`

type ListDistrictsInHealthContextParams struct {
	HealthContextID    uuid.UUID `json:"health_context_id"`
	IncludeDescendants bool      `json:"include_descendants"`
}

type ListDistrictsInHealthContextRow struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	RegionID   uuid.NullUUID  `json:"region_id"`
	Code       sql.NullString `json:"code"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	RegionName sql.NullString `json:"region_name"`
}

func (q *Queries) ListDistrictsInHealthContext(ctx context.Context, arg ListDistrictsInHealthContextParams) ([]ListDistrictsInHealthContextRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistrictsInHealthContext, arg.HealthContextID, arg.IncludeDescendants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistrictsInHealthContextRow{}
	for rows.Next() {
		var i ListDistrictsInHealthContextRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RegionID,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDistrict = `-- name: UpsertDistrict :one
INSERT INTO districts (
  name,
  region_id,
  code
) VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (name)
DO UPDATE SET
  region_id = COALESCE(EXCLUDED.region_id, districts.region_id),
  code = COALESCE(EXCLUDED.code, districts.code),
  updated_at = now()
RETURNING id, name, region_id, code, created_at, updated_at
`

type UpsertDistrictParams struct {
	Name     string         `json:"name"`
	RegionID uuid.NullUUID  `json:"region_id"`
	Code     sql.NullString `json:"code"`
}

func (q *Queries) UpsertDistrict(ctx context.Context, arg UpsertDistrictParams) (District, error) {
	row := q.db.QueryRowContext(ctx, upsertDistrict, arg.Name, arg.RegionID, arg.Code)
	var i District
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
