// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: district_weekly_status.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDistrictWeeklyDiseaseStatus = `-- name: CreateDistrictWeeklyDiseaseStatus :one
INSERT INTO district_weekly_status (
  district_id,
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  $1, $2, NULL, $3, $4, $5
)
RETURNING id, district_id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type CreateDistrictWeeklyDiseaseStatusParams struct {
	DistrictID uuid.UUID      `json:"district_id"`
	DiseaseID  uuid.UUID      `json:"disease_id"`
	EpiWeekID  uuid.UUID      `json:"epi_week_id"`
	Status     interface{}    `json:"status"`
	SourceName sql.NullString `json:"source_name"`
}

func (q *Queries) CreateDistrictWeeklyDiseaseStatus(ctx context.Context, arg CreateDistrictWeeklyDiseaseStatusParams) (DistrictWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, createDistrictWeeklyDiseaseStatus,
		arg.DistrictID,
		arg.DiseaseID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i DistrictWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDistrictWeeklyIndicatorStatus = `-- name: CreateDistrictWeeklyIndicatorStatus :one
INSERT INTO district_weekly_status (
  district_id,
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  $1, NULL, $2, $3, $4, $5
)
RETURNING id, district_id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type CreateDistrictWeeklyIndicatorStatusParams struct {
	DistrictID  uuid.UUID      `json:"district_id"`
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
}

func (q *Queries) CreateDistrictWeeklyIndicatorStatus(ctx context.Context, arg CreateDistrictWeeklyIndicatorStatusParams) (DistrictWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, createDistrictWeeklyIndicatorStatus,
		arg.DistrictID,
		arg.IndicatorID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i DistrictWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDistrictStatusesByWeek = `-- name: DeleteDistrictStatusesByWeek :exec
DELETE FROM district_weekly_status
WHERE epi_week_id = $1
`

func (q *Queries) DeleteDistrictStatusesByWeek(ctx context.Context, epiWeekID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDistrictStatusesByWeek, epiWeekID)
	return err
}

const listDistrictStatusesByDistrictAndWeek = `-- name: ListDistrictStatusesByDistrictAndWeek :many
SELECT
  s.id,
  s.district_id,
  s.disease_id,
  s.indicator_id,
  s.epi_week_id,
  s.status,
  s.source_name,
  s.imported_at,
  s.created_at,
  CASE
    WHEN s.disease_id IS NOT NULL THEN 'DISEASE'
    ELSE 'INDICATOR'
  END AS subject_type,
  COALESCE(dis.name, i.name) AS subject_name
FROM district_weekly_status s
LEFT JOIN diseases dis ON dis.id = s.disease_id
LEFT JOIN indicators i ON i.id = s.indicator_id
WHERE s.district_id = $1
  AND s.epi_week_id = $2
ORDER BY
  CASE s.status
    WHEN 'MAROON' THEN 1
    WHEN 'RED' THEN 2
    WHEN 'YELLOW' THEN 3
    WHEN 'GREEN' THEN 4
  END,
  subject_name ASC
`

type ListDistrictStatusesByDistrictAndWeekParams struct {
	DistrictID uuid.UUID `json:"district_id"`
	EpiWeekID  uuid.UUID `json:"epi_week_id"`
}

type ListDistrictStatusesByDistrictAndWeekRow struct {
	ID          uuid.UUID      `json:"id"`
	DistrictID  uuid.UUID      `json:"district_id"`
	DiseaseID   uuid.UUID      `json:"disease_id"`
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
	ImportedAt  time.Time      `json:"imported_at"`
	CreatedAt   time.Time      `json:"created_at"`
	SubjectType string         `json:"subject_type"`
	SubjectName string         `json:"subject_name"`
}

func (q *Queries) ListDistrictStatusesByDistrictAndWeek(ctx context.Context, arg ListDistrictStatusesByDistrictAndWeekParams) ([]ListDistrictStatusesByDistrictAndWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistrictStatusesByDistrictAndWeek, arg.DistrictID, arg.EpiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistrictStatusesByDistrictAndWeekRow{}
	for rows.Next() {
		var i ListDistrictStatusesByDistrictAndWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.DistrictID,
			&i.DiseaseID,
			&i.IndicatorID,
			&i.EpiWeekID,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.SubjectType,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistrictWeeklyDiseaseStatusesByWeek = `-- name: ListDistrictWeeklyDiseaseStatusesByWeek :many
SELECT
  s.id, s.district_id, s.disease_id, s.indicator_id, s.epi_week_id, s.status, s.source_name, s.imported_at, s.created_at,
  d.name AS district_name,
  dis.name AS disease_name
FROM district_weekly_status s
JOIN districts d ON d.id = s.district_id
JOIN diseases dis ON dis.id = s.disease_id
WHERE s.epi_week_id = $1
  AND s.disease_id IS NOT NULL
ORDER BY d.name ASC, dis.name ASC
`

type ListDistrictWeeklyDiseaseStatusesByWeekRow struct {
	ID           uuid.UUID      `json:"id"`
	DistrictID   uuid.UUID      `json:"district_id"`
	DiseaseID    uuid.UUID      `json:"disease_id"`
	IndicatorID  uuid.UUID      `json:"indicator_id"`
	EpiWeekID    uuid.UUID      `json:"epi_week_id"`
	Status       interface{}    `json:"status"`
	SourceName   sql.NullString `json:"source_name"`
	ImportedAt   time.Time      `json:"imported_at"`
	CreatedAt    time.Time      `json:"created_at"`
	DistrictName string         `json:"district_name"`
	DiseaseName  string         `json:"disease_name"`
}

func (q *Queries) ListDistrictWeeklyDiseaseStatusesByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListDistrictWeeklyDiseaseStatusesByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistrictWeeklyDiseaseStatusesByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistrictWeeklyDiseaseStatusesByWeekRow{}
	for rows.Next() {
		var i ListDistrictWeeklyDiseaseStatusesByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.DistrictID,
			&i.DiseaseID,
			&i.IndicatorID,
			&i.EpiWeekID,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.DistrictName,
			&i.DiseaseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistrictWeeklyIndicatorStatusesByWeek = `-- name: ListDistrictWeeklyIndicatorStatusesByWeek :many
SELECT
  s.id, s.district_id, s.disease_id, s.indicator_id, s.epi_week_id, s.status, s.source_name, s.imported_at, s.created_at,
  d.name AS district_name,
  i.name AS indicator_name
FROM district_weekly_status s
JOIN districts d ON d.id = s.district_id
JOIN indicators i ON i.id = s.indicator_id
WHERE s.epi_week_id = $1
  AND s.indicator_id IS NOT NULL
ORDER BY d.name ASC, i.name ASC
`

type ListDistrictWeeklyIndicatorStatusesByWeekRow struct {
	ID            uuid.UUID      `json:"id"`
	DistrictID    uuid.UUID      `json:"district_id"`
	DiseaseID     uuid.UUID      `json:"disease_id"`
	IndicatorID   uuid.UUID      `json:"indicator_id"`
	EpiWeekID     uuid.UUID      `json:"epi_week_id"`
	Status        interface{}    `json:"status"`
	SourceName    sql.NullString `json:"source_name"`
	ImportedAt    time.Time      `json:"imported_at"`
	CreatedAt     time.Time      `json:"created_at"`
	DistrictName  string         `json:"district_name"`
	IndicatorName string         `json:"indicator_name"`
}

func (q *Queries) ListDistrictWeeklyIndicatorStatusesByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListDistrictWeeklyIndicatorStatusesByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistrictWeeklyIndicatorStatusesByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistrictWeeklyIndicatorStatusesByWeekRow{}
	for rows.Next() {
		var i ListDistrictWeeklyIndicatorStatusesByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.DistrictID,
			&i.DiseaseID,
			&i.IndicatorID,
			&i.EpiWeekID,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.DistrictName,
			&i.IndicatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDistrictWeeklyDiseaseStatus = `-- name: UpsertDistrictWeeklyDiseaseStatus :one
INSERT INTO district_weekly_status (
  district_id,
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  $1, $2, NULL, $3, $4, $5
)
ON CONFLICT (district_id, disease_id, epi_week_id)
WHERE disease_id IS NOT NULL
DO UPDATE SET
  status = EXCLUDED.status,
  source_name = COALESCE(EXCLUDED.source_name, district_weekly_status.source_name),
  imported_at = now()
RETURNING id, district_id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type UpsertDistrictWeeklyDiseaseStatusParams struct {
	DistrictID uuid.UUID      `json:"district_id"`
	DiseaseID  uuid.UUID      `json:"disease_id"`
	EpiWeekID  uuid.UUID      `json:"epi_week_id"`
	Status     interface{}    `json:"status"`
	SourceName sql.NullString `json:"source_name"`
}

func (q *Queries) UpsertDistrictWeeklyDiseaseStatus(ctx context.Context, arg UpsertDistrictWeeklyDiseaseStatusParams) (DistrictWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertDistrictWeeklyDiseaseStatus,
		arg.DistrictID,
		arg.DiseaseID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i DistrictWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertDistrictWeeklyIndicatorStatus = `-- name: UpsertDistrictWeeklyIndicatorStatus :one
INSERT INTO district_weekly_status (
  district_id,
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  $1, NULL, $2, $3, $4, $5
)
ON CONFLICT (district_id, indicator_id, epi_week_id)
WHERE indicator_id IS NOT NULL
DO UPDATE SET
  status = EXCLUDED.status,
  source_name = COALESCE(EXCLUDED.source_name, district_weekly_status.source_name),
  imported_at = now()
RETURNING id, district_id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type UpsertDistrictWeeklyIndicatorStatusParams struct {
	DistrictID  uuid.UUID      `json:"district_id"`
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
}

func (q *Queries) UpsertDistrictWeeklyIndicatorStatus(ctx context.Context, arg UpsertDistrictWeeklyIndicatorStatusParams) (DistrictWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertDistrictWeeklyIndicatorStatus,
		arg.DistrictID,
		arg.IndicatorID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i DistrictWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.DistrictID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}
