// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id,
    original_filename,
    content_type,
    size_bytes,
    checksum_sha256,
    storage_location_id,
    object_key,
    uploaded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, original_filename, content_type, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, created_at
`

type CreateDocumentParams struct {
	ID                uuid.UUID      `json:"id"`
	OriginalFilename  string         `json:"original_filename"`
	ContentType       sql.NullString `json:"content_type"`
	SizeBytes         int64          `json:"size_bytes"`
	ChecksumSha256    sql.NullString `json:"checksum_sha256"`
	StorageLocationID uuid.UUID      `json:"storage_location_id"`
	ObjectKey         string         `json:"object_key"`
	UploadedBy        uuid.UUID      `json:"uploaded_by"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.OriginalFilename,
		arg.ContentType,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.StorageLocationID,
		arg.ObjectKey,
		arg.UploadedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, original_filename, content_type, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, created_at
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, original_filename, content_type, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, created_at
FROM documents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageLocationID,
			&i.ObjectKey,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByUser = `-- name: ListDocumentsByUser :many
SELECT id, original_filename, content_type, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, created_at
FROM documents
WHERE uploaded_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByUserParams struct {
	UploadedBy uuid.UUID `json:"uploaded_by"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListDocumentsByUser(ctx context.Context, arg ListDocumentsByUserParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByUser, arg.UploadedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageLocationID,
			&i.ObjectKey,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET original_filename = $2,
    content_type = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, original_filename, content_type, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, created_at
`

type UpdateDocumentParams struct {
	ID               uuid.UUID      `json:"id"`
	OriginalFilename string         `json:"original_filename"`
	ContentType      sql.NullString `json:"content_type"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocument, arg.ID, arg.OriginalFilename, arg.ContentType)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}
