// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id,
    original_filename,
    content_type,
    size_bytes,
    checksum_sha256,
    storage_location_id,
    object_key,
    uploaded_by,
    status,
    metadata,
    is_template
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
`

type CreateDocumentParams struct {
	ID                uuid.UUID       `json:"id"`
	OriginalFilename  string          `json:"original_filename"`
	ContentType       sql.NullString  `json:"content_type"`
	SizeBytes         int64           `json:"size_bytes"`
	ChecksumSha256    sql.NullString  `json:"checksum_sha256"`
	StorageLocationID uuid.UUID       `json:"storage_location_id"`
	ObjectKey         string          `json:"object_key"`
	UploadedBy        uuid.UUID       `json:"uploaded_by"`
	Status            DocumentStatus  `json:"status"`
	Metadata          json.RawMessage `json:"metadata"`
	IsTemplate        bool            `json:"is_template"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.OriginalFilename,
		arg.ContentType,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.StorageLocationID,
		arg.ObjectKey,
		arg.UploadedBy,
		arg.Status,
		arg.Metadata,
		arg.IsTemplate,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.NormalizedFilename,
		&i.ContentType,
		&i.Extension,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.Status,
		&i.Version,
		&i.ParentDocumentID,
		&i.Metadata,
		&i.Tags,
		&i.IsTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
FROM documents
WHERE id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.NormalizedFilename,
		&i.ContentType,
		&i.Extension,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.Status,
		&i.Version,
		&i.ParentDocumentID,
		&i.Metadata,
		&i.Tags,
		&i.IsTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
FROM documents
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDocumentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.NormalizedFilename,
			&i.ContentType,
			&i.Extension,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageLocationID,
			&i.ObjectKey,
			&i.UploadedBy,
			&i.Status,
			&i.Version,
			&i.ParentDocumentID,
			&i.Metadata,
			&i.Tags,
			&i.IsTemplate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByStatus = `-- name: ListDocumentsByStatus :many
SELECT id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
FROM documents
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByStatusParams struct {
	Status DocumentStatus `json:"status"`
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
}

func (q *Queries) ListDocumentsByStatus(ctx context.Context, arg ListDocumentsByStatusParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.NormalizedFilename,
			&i.ContentType,
			&i.Extension,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageLocationID,
			&i.ObjectKey,
			&i.UploadedBy,
			&i.Status,
			&i.Version,
			&i.ParentDocumentID,
			&i.Metadata,
			&i.Tags,
			&i.IsTemplate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByUser = `-- name: ListDocumentsByUser :many
SELECT id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
FROM documents
WHERE uploaded_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsByUserParams struct {
	UploadedBy uuid.UUID `json:"uploaded_by"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListDocumentsByUser(ctx context.Context, arg ListDocumentsByUserParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentsByUser, arg.UploadedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.OriginalFilename,
			&i.NormalizedFilename,
			&i.ContentType,
			&i.Extension,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.StorageLocationID,
			&i.ObjectKey,
			&i.UploadedBy,
			&i.Status,
			&i.Version,
			&i.ParentDocumentID,
			&i.Metadata,
			&i.Tags,
			&i.IsTemplate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentCompleted = `-- name: MarkDocumentCompleted :one
UPDATE documents
SET status = 'COMPLETED',
    updated_at = NOW()
WHERE id = $1
RETURNING id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
`

func (q *Queries) MarkDocumentCompleted(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, markDocumentCompleted, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.NormalizedFilename,
		&i.ContentType,
		&i.Extension,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.Status,
		&i.Version,
		&i.ParentDocumentID,
		&i.Metadata,
		&i.Tags,
		&i.IsTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markDocumentFailed = `-- name: MarkDocumentFailed :one
UPDATE documents
SET status = 'FAILED',
    updated_at = NOW()
WHERE id = $1
RETURNING id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
`

func (q *Queries) MarkDocumentFailed(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, markDocumentFailed, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.NormalizedFilename,
		&i.ContentType,
		&i.Extension,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.Status,
		&i.Version,
		&i.ParentDocumentID,
		&i.Metadata,
		&i.Tags,
		&i.IsTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markDocumentPending = `-- name: MarkDocumentPending :one
UPDATE documents
SET status = 'PENDING',
    updated_at = NOW()
WHERE id = $1
RETURNING id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
`

func (q *Queries) MarkDocumentPending(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, markDocumentPending, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.NormalizedFilename,
		&i.ContentType,
		&i.Extension,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.Status,
		&i.Version,
		&i.ParentDocumentID,
		&i.Metadata,
		&i.Tags,
		&i.IsTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markDocumentProcessing = `-- name: MarkDocumentProcessing :one
UPDATE documents
SET status = 'PROCESSING',
    updated_at = NOW()
WHERE id = $1
RETURNING id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
`

func (q *Queries) MarkDocumentProcessing(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRowContext(ctx, markDocumentProcessing, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.NormalizedFilename,
		&i.ContentType,
		&i.Extension,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.Status,
		&i.Version,
		&i.ParentDocumentID,
		&i.Metadata,
		&i.Tags,
		&i.IsTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET original_filename = $2,
    content_type = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
`

type UpdateDocumentParams struct {
	ID               uuid.UUID      `json:"id"`
	OriginalFilename string         `json:"original_filename"`
	ContentType      sql.NullString `json:"content_type"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocument, arg.ID, arg.OriginalFilename, arg.ContentType)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.NormalizedFilename,
		&i.ContentType,
		&i.Extension,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.Status,
		&i.Version,
		&i.ParentDocumentID,
		&i.Metadata,
		&i.Tags,
		&i.IsTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, original_filename, normalized_filename, content_type, extension, size_bytes, checksum_sha256, storage_location_id, object_key, uploaded_by, status, version, parent_document_id, metadata, tags, is_template, created_at, updated_at, deleted_at
`

type UpdateDocumentStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status DocumentStatus `json:"status"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentStatus, arg.ID, arg.Status)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalFilename,
		&i.NormalizedFilename,
		&i.ContentType,
		&i.Extension,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.StorageLocationID,
		&i.ObjectKey,
		&i.UploadedBy,
		&i.Status,
		&i.Version,
		&i.ParentDocumentID,
		&i.Metadata,
		&i.Tags,
		&i.IsTemplate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
