// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_outbox.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const claimEmailOutboxBatch = `-- name: ClaimEmailOutboxBatch :many
WITH picked AS (
  SELECT id
  FROM email_outbox
  WHERE status IN ('PENDING', 'RETRYING')
    AND (scheduled_at IS NULL OR scheduled_at <= now())
    AND attempts < max_attempts
    AND (locked_at IS NULL OR locked_at < now() - interval '5 minutes')
  ORDER BY created_at ASC
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
UPDATE email_outbox eo
SET status = 'PROCESSING',
    locked_at = now(),
    updated_at = now()
FROM picked
WHERE eo.id = picked.id
RETURNING eo.id, eo.message_id, eo.from_address, eo.to_addresses, eo.cc_addresses, eo.bcc_addresses, eo.reply_to_addresses, eo.subject, eo.text_body, eo.html_body, eo.template_name, eo.template_data, eo.attachments, eo.headers, eo.metadata, eo.status, eo.attempts, eo.max_attempts, eo.last_error, eo.scheduled_at, eo.locked_at, eo.sent_at, eo.created_at, eo.updated_at
`

func (q *Queries) ClaimEmailOutboxBatch(ctx context.Context, limit int32) ([]EmailOutbox, error) {
	rows, err := q.db.QueryContext(ctx, claimEmailOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FromAddress,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.ReplyToAddresses,
			&i.Subject,
			&i.TextBody,
			&i.HtmlBody,
			&i.TemplateName,
			&i.TemplateData,
			&i.Attachments,
			&i.Headers,
			&i.Metadata,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.ScheduledAt,
			&i.LockedAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEmailOutboxByStatus = `-- name: CountEmailOutboxByStatus :one
SELECT COUNT(*)::bigint
FROM email_outbox
WHERE status = $1
`

func (q *Queries) CountEmailOutboxByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailOutboxByStatus, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createEmailOutbox = `-- name: CreateEmailOutbox :one
INSERT INTO email_outbox (
  message_id,
  from_address,
  to_addresses,
  cc_addresses,
  bcc_addresses,
  reply_to_addresses,
  subject,
  text_body,
  html_body,
  template_name,
  template_data,
  attachments,
  headers,
  metadata,
  status,
  attempts,
  max_attempts,
  scheduled_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  COALESCE($15, 'PENDING'),
  COALESCE($16, 0),
  COALESCE($17, 5),
  $18
)
RETURNING id, message_id, from_address, to_addresses, cc_addresses, bcc_addresses, reply_to_addresses, subject, text_body, html_body, template_name, template_data, attachments, headers, metadata, status, attempts, max_attempts, last_error, scheduled_at, locked_at, sent_at, created_at, updated_at
`

type CreateEmailOutboxParams struct {
	MessageID        sql.NullString        `json:"message_id"`
	FromAddress      pqtype.NullRawMessage `json:"from_address"`
	ToAddresses      json.RawMessage       `json:"to_addresses"`
	CcAddresses      pqtype.NullRawMessage `json:"cc_addresses"`
	BccAddresses     pqtype.NullRawMessage `json:"bcc_addresses"`
	ReplyToAddresses pqtype.NullRawMessage `json:"reply_to_addresses"`
	Subject          string                `json:"subject"`
	TextBody         sql.NullString        `json:"text_body"`
	HtmlBody         sql.NullString        `json:"html_body"`
	TemplateName     sql.NullString        `json:"template_name"`
	TemplateData     pqtype.NullRawMessage `json:"template_data"`
	Attachments      pqtype.NullRawMessage `json:"attachments"`
	Headers          pqtype.NullRawMessage `json:"headers"`
	Metadata         pqtype.NullRawMessage `json:"metadata"`
	Status           interface{}           `json:"status"`
	Attempts         interface{}           `json:"attempts"`
	MaxAttempts      interface{}           `json:"max_attempts"`
	ScheduledAt      sql.NullTime          `json:"scheduled_at"`
}

func (q *Queries) CreateEmailOutbox(ctx context.Context, arg CreateEmailOutboxParams) (EmailOutbox, error) {
	row := q.db.QueryRowContext(ctx, createEmailOutbox,
		arg.MessageID,
		arg.FromAddress,
		arg.ToAddresses,
		arg.CcAddresses,
		arg.BccAddresses,
		arg.ReplyToAddresses,
		arg.Subject,
		arg.TextBody,
		arg.HtmlBody,
		arg.TemplateName,
		arg.TemplateData,
		arg.Attachments,
		arg.Headers,
		arg.Metadata,
		arg.Status,
		arg.Attempts,
		arg.MaxAttempts,
		arg.ScheduledAt,
	)
	var i EmailOutbox
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FromAddress,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.ReplyToAddresses,
		&i.Subject,
		&i.TextBody,
		&i.HtmlBody,
		&i.TemplateName,
		&i.TemplateData,
		&i.Attachments,
		&i.Headers,
		&i.Metadata,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.ScheduledAt,
		&i.LockedAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmailOutboxByID = `-- name: DeleteEmailOutboxByID :exec
DELETE FROM email_outbox
WHERE id = $1
`

func (q *Queries) DeleteEmailOutboxByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmailOutboxByID, id)
	return err
}

const deleteSentEmailOutboxOlderThan = `-- name: DeleteSentEmailOutboxOlderThan :execrows
DELETE FROM email_outbox
WHERE status = 'SENT'
  AND sent_at IS NOT NULL
  AND sent_at < $1
`

func (q *Queries) DeleteSentEmailOutboxOlderThan(ctx context.Context, sentAt sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSentEmailOutboxOlderThan, sentAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEmailOutboxByID = `-- name: GetEmailOutboxByID :one
SELECT id, message_id, from_address, to_addresses, cc_addresses, bcc_addresses, reply_to_addresses, subject, text_body, html_body, template_name, template_data, attachments, headers, metadata, status, attempts, max_attempts, last_error, scheduled_at, locked_at, sent_at, created_at, updated_at
FROM email_outbox
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEmailOutboxByID(ctx context.Context, id uuid.UUID) (EmailOutbox, error) {
	row := q.db.QueryRowContext(ctx, getEmailOutboxByID, id)
	var i EmailOutbox
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FromAddress,
		&i.ToAddresses,
		&i.CcAddresses,
		&i.BccAddresses,
		&i.ReplyToAddresses,
		&i.Subject,
		&i.TextBody,
		&i.HtmlBody,
		&i.TemplateName,
		&i.TemplateData,
		&i.Attachments,
		&i.Headers,
		&i.Metadata,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.ScheduledAt,
		&i.LockedAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailOutbox = `-- name: ListEmailOutbox :many
SELECT id, message_id, from_address, to_addresses, cc_addresses, bcc_addresses, reply_to_addresses, subject, text_body, html_body, template_name, template_data, attachments, headers, metadata, status, attempts, max_attempts, last_error, scheduled_at, locked_at, sent_at, created_at, updated_at
FROM email_outbox
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListEmailOutboxParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEmailOutbox(ctx context.Context, arg ListEmailOutboxParams) ([]EmailOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listEmailOutbox, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FromAddress,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.ReplyToAddresses,
			&i.Subject,
			&i.TextBody,
			&i.HtmlBody,
			&i.TemplateName,
			&i.TemplateData,
			&i.Attachments,
			&i.Headers,
			&i.Metadata,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.ScheduledAt,
			&i.LockedAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailOutboxByRecipient = `-- name: ListEmailOutboxByRecipient :many
SELECT id, message_id, from_address, to_addresses, cc_addresses, bcc_addresses, reply_to_addresses, subject, text_body, html_body, template_name, template_data, attachments, headers, metadata, status, attempts, max_attempts, last_error, scheduled_at, locked_at, sent_at, created_at, updated_at
FROM email_outbox
WHERE to_addresses::text ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEmailOutboxByRecipientParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) ListEmailOutboxByRecipient(ctx context.Context, arg ListEmailOutboxByRecipientParams) ([]EmailOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listEmailOutboxByRecipient, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FromAddress,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.ReplyToAddresses,
			&i.Subject,
			&i.TextBody,
			&i.HtmlBody,
			&i.TemplateName,
			&i.TemplateData,
			&i.Attachments,
			&i.Headers,
			&i.Metadata,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.ScheduledAt,
			&i.LockedAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailOutboxByStatus = `-- name: ListEmailOutboxByStatus :many
SELECT id, message_id, from_address, to_addresses, cc_addresses, bcc_addresses, reply_to_addresses, subject, text_body, html_body, template_name, template_data, attachments, headers, metadata, status, attempts, max_attempts, last_error, scheduled_at, locked_at, sent_at, created_at, updated_at
FROM email_outbox
WHERE status = $1
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListEmailOutboxByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListEmailOutboxByStatus(ctx context.Context, arg ListEmailOutboxByStatusParams) ([]EmailOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listEmailOutboxByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FromAddress,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.ReplyToAddresses,
			&i.Subject,
			&i.TextBody,
			&i.HtmlBody,
			&i.TemplateName,
			&i.TemplateData,
			&i.Attachments,
			&i.Headers,
			&i.Metadata,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.ScheduledAt,
			&i.LockedAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailOutboxFailures = `-- name: ListEmailOutboxFailures :many
SELECT id, message_id, from_address, to_addresses, cc_addresses, bcc_addresses, reply_to_addresses, subject, text_body, html_body, template_name, template_data, attachments, headers, metadata, status, attempts, max_attempts, last_error, scheduled_at, locked_at, sent_at, created_at, updated_at
FROM email_outbox
WHERE status = 'FAILED'
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListEmailOutboxFailuresParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEmailOutboxFailures(ctx context.Context, arg ListEmailOutboxFailuresParams) ([]EmailOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listEmailOutboxFailures, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FromAddress,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.ReplyToAddresses,
			&i.Subject,
			&i.TextBody,
			&i.HtmlBody,
			&i.TemplateName,
			&i.TemplateData,
			&i.Attachments,
			&i.Headers,
			&i.Metadata,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.ScheduledAt,
			&i.LockedAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailOutboxPendingDue = `-- name: ListEmailOutboxPendingDue :many
SELECT id, message_id, from_address, to_addresses, cc_addresses, bcc_addresses, reply_to_addresses, subject, text_body, html_body, template_name, template_data, attachments, headers, metadata, status, attempts, max_attempts, last_error, scheduled_at, locked_at, sent_at, created_at, updated_at
FROM email_outbox
WHERE status IN ('PENDING', 'RETRYING')
  AND attempts < max_attempts
  AND (scheduled_at IS NULL OR scheduled_at <= now())
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListEmailOutboxPendingDue(ctx context.Context, limit int32) ([]EmailOutbox, error) {
	rows, err := q.db.QueryContext(ctx, listEmailOutboxPendingDue, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FromAddress,
			&i.ToAddresses,
			&i.CcAddresses,
			&i.BccAddresses,
			&i.ReplyToAddresses,
			&i.Subject,
			&i.TextBody,
			&i.HtmlBody,
			&i.TemplateName,
			&i.TemplateData,
			&i.Attachments,
			&i.Headers,
			&i.Metadata,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.ScheduledAt,
			&i.LockedAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailOutboxFailed = `-- name: MarkEmailOutboxFailed :exec
UPDATE email_outbox
SET
  status = 'FAILED',
  attempts = $1,
  last_error = $2,
  locked_at = NULL,
  updated_at = now()
WHERE id = $3
`

type MarkEmailOutboxFailedParams struct {
	Attempts  int32          `json:"attempts"`
	LastError sql.NullString `json:"last_error"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) MarkEmailOutboxFailed(ctx context.Context, arg MarkEmailOutboxFailedParams) error {
	_, err := q.db.ExecContext(ctx, markEmailOutboxFailed, arg.Attempts, arg.LastError, arg.ID)
	return err
}

const markEmailOutboxProcessing = `-- name: MarkEmailOutboxProcessing :exec
UPDATE email_outbox
SET
  status = 'PROCESSING',
  locked_at = now(),
  updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkEmailOutboxProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markEmailOutboxProcessing, id)
	return err
}

const markEmailOutboxRetry = `-- name: MarkEmailOutboxRetry :exec
UPDATE email_outbox
SET
  status = 'RETRYING',
  attempts = $1,
  last_error = $2,
  locked_at = NULL,
  updated_at = now()
WHERE id = $3
`

type MarkEmailOutboxRetryParams struct {
	Attempts  int32          `json:"attempts"`
	LastError sql.NullString `json:"last_error"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) MarkEmailOutboxRetry(ctx context.Context, arg MarkEmailOutboxRetryParams) error {
	_, err := q.db.ExecContext(ctx, markEmailOutboxRetry, arg.Attempts, arg.LastError, arg.ID)
	return err
}

const markEmailOutboxSent = `-- name: MarkEmailOutboxSent :exec
UPDATE email_outbox
SET status = 'SENT',
    sent_at = now(),
    locked_at = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkEmailOutboxSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markEmailOutboxSent, id)
	return err
}

const resetStuckEmailOutboxJobs = `-- name: ResetStuckEmailOutboxJobs :execrows
UPDATE email_outbox
SET
  status = 'RETRYING',
  locked_at = NULL,
  updated_at = now()
WHERE status = 'PROCESSING'
  AND locked_at IS NOT NULL
  AND locked_at < now() - interval '15 minutes'
`

func (q *Queries) ResetStuckEmailOutboxJobs(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetStuckEmailOutboxJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
