// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: epi_weeks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createEpiWeek = `-- name: CreateEpiWeek :one
INSERT INTO epi_weeks (
  epi_year,
  epi_week,
  week_start_date,
  week_end_date
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, epi_year, epi_week, week_start_date, week_end_date, created_at
`

type CreateEpiWeekParams struct {
	EpiYear       int32        `json:"epi_year"`
	EpiWeek       int32        `json:"epi_week"`
	WeekStartDate sql.NullTime `json:"week_start_date"`
	WeekEndDate   sql.NullTime `json:"week_end_date"`
}

func (q *Queries) CreateEpiWeek(ctx context.Context, arg CreateEpiWeekParams) (EpiWeek, error) {
	row := q.db.QueryRowContext(ctx, createEpiWeek,
		arg.EpiYear,
		arg.EpiWeek,
		arg.WeekStartDate,
		arg.WeekEndDate,
	)
	var i EpiWeek
	err := row.Scan(
		&i.ID,
		&i.EpiYear,
		&i.EpiWeek,
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getEpiWeekByID = `-- name: GetEpiWeekByID :one
SELECT id, epi_year, epi_week, week_start_date, week_end_date, created_at
FROM epi_weeks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetEpiWeekByID(ctx context.Context, id uuid.UUID) (EpiWeek, error) {
	row := q.db.QueryRowContext(ctx, getEpiWeekByID, id)
	var i EpiWeek
	err := row.Scan(
		&i.ID,
		&i.EpiYear,
		&i.EpiWeek,
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getEpiWeekByYearWeek = `-- name: GetEpiWeekByYearWeek :one
SELECT id, epi_year, epi_week, week_start_date, week_end_date, created_at
FROM epi_weeks
WHERE epi_year = $1
  AND epi_week = $2
LIMIT 1
`

type GetEpiWeekByYearWeekParams struct {
	EpiYear int32 `json:"epi_year"`
	EpiWeek int32 `json:"epi_week"`
}

func (q *Queries) GetEpiWeekByYearWeek(ctx context.Context, arg GetEpiWeekByYearWeekParams) (EpiWeek, error) {
	row := q.db.QueryRowContext(ctx, getEpiWeekByYearWeek, arg.EpiYear, arg.EpiWeek)
	var i EpiWeek
	err := row.Scan(
		&i.ID,
		&i.EpiYear,
		&i.EpiWeek,
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.CreatedAt,
	)
	return i, err
}

const listEpiWeeksByYear = `-- name: ListEpiWeeksByYear :many
SELECT id, epi_year, epi_week, week_start_date, week_end_date, created_at
FROM epi_weeks
WHERE epi_year = $1
ORDER BY epi_week ASC
`

func (q *Queries) ListEpiWeeksByYear(ctx context.Context, epiYear int32) ([]EpiWeek, error) {
	rows, err := q.db.QueryContext(ctx, listEpiWeeksByYear, epiYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EpiWeek{}
	for rows.Next() {
		var i EpiWeek
		if err := rows.Scan(
			&i.ID,
			&i.EpiYear,
			&i.EpiWeek,
			&i.WeekStartDate,
			&i.WeekEndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEpiWeek = `-- name: UpsertEpiWeek :one
INSERT INTO epi_weeks (
  epi_year,
  epi_week,
  week_start_date,
  week_end_date
) VALUES (
  $1,
  $2,
  $3,
  $4
)
ON CONFLICT (epi_year, epi_week)
DO UPDATE SET
  week_start_date = COALESCE(EXCLUDED.week_start_date, epi_weeks.week_start_date),
  week_end_date = COALESCE(EXCLUDED.week_end_date, epi_weeks.week_end_date)
RETURNING id, epi_year, epi_week, week_start_date, week_end_date, created_at
`

type UpsertEpiWeekParams struct {
	EpiYear       int32        `json:"epi_year"`
	EpiWeek       int32        `json:"epi_week"`
	WeekStartDate sql.NullTime `json:"week_start_date"`
	WeekEndDate   sql.NullTime `json:"week_end_date"`
}

func (q *Queries) UpsertEpiWeek(ctx context.Context, arg UpsertEpiWeekParams) (EpiWeek, error) {
	row := q.db.QueryRowContext(ctx, upsertEpiWeek,
		arg.EpiYear,
		arg.EpiWeek,
		arg.WeekStartDate,
		arg.WeekEndDate,
	)
	var i EpiWeek
	err := row.Scan(
		&i.ID,
		&i.EpiYear,
		&i.EpiWeek,
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.CreatedAt,
	)
	return i, err
}
