// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: facilities.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFacility = `-- name: CreateFacility :one
INSERT INTO facilities (
  external_id,
  name,
  district_id,
  sub_county_id,
  region_id,
  facility_level,
  facility_type,
  dhis2_org_unit_id,
  latitude,
  longitude
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, external_id, name, district_id, sub_county_id, region_id, facility_level, facility_type, dhis2_org_unit_id, latitude, longitude, created_at, updated_at
`

type CreateFacilityParams struct {
	ExternalID     sql.NullString `json:"external_id"`
	Name           string         `json:"name"`
	DistrictID     uuid.NullUUID  `json:"district_id"`
	SubCountyID    uuid.NullUUID  `json:"sub_county_id"`
	RegionID       uuid.NullUUID  `json:"region_id"`
	FacilityLevel  sql.NullString `json:"facility_level"`
	FacilityType   sql.NullString `json:"facility_type"`
	Dhis2OrgUnitID sql.NullString `json:"dhis2_org_unit_id"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
}

func (q *Queries) CreateFacility(ctx context.Context, arg CreateFacilityParams) (Facility, error) {
	row := q.db.QueryRowContext(ctx, createFacility,
		arg.ExternalID,
		arg.Name,
		arg.DistrictID,
		arg.SubCountyID,
		arg.RegionID,
		arg.FacilityLevel,
		arg.FacilityType,
		arg.Dhis2OrgUnitID,
		arg.Latitude,
		arg.Longitude,
	)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.DistrictID,
		&i.SubCountyID,
		&i.RegionID,
		&i.FacilityLevel,
		&i.FacilityType,
		&i.Dhis2OrgUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFacility = `-- name: DeleteFacility :exec
DELETE FROM facilities
WHERE id = $1
`

func (q *Queries) DeleteFacility(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFacility, id)
	return err
}

const getFacilityByExternalID = `-- name: GetFacilityByExternalID :one
SELECT id, external_id, name, district_id, sub_county_id, region_id, facility_level, facility_type, dhis2_org_unit_id, latitude, longitude, created_at, updated_at
FROM facilities
WHERE external_id = $1
LIMIT 1
`

func (q *Queries) GetFacilityByExternalID(ctx context.Context, externalID sql.NullString) (Facility, error) {
	row := q.db.QueryRowContext(ctx, getFacilityByExternalID, externalID)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.DistrictID,
		&i.SubCountyID,
		&i.RegionID,
		&i.FacilityLevel,
		&i.FacilityType,
		&i.Dhis2OrgUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFacilityByID = `-- name: GetFacilityByID :one
SELECT id, external_id, name, district_id, sub_county_id, region_id, facility_level, facility_type, dhis2_org_unit_id, latitude, longitude, created_at, updated_at
FROM facilities
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFacilityByID(ctx context.Context, id uuid.UUID) (Facility, error) {
	row := q.db.QueryRowContext(ctx, getFacilityByID, id)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.DistrictID,
		&i.SubCountyID,
		&i.RegionID,
		&i.FacilityLevel,
		&i.FacilityType,
		&i.Dhis2OrgUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFacilityByName = `-- name: GetFacilityByName :one
SELECT id, external_id, name, district_id, sub_county_id, region_id, facility_level, facility_type, dhis2_org_unit_id, latitude, longitude, created_at, updated_at
FROM facilities
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetFacilityByName(ctx context.Context, name string) (Facility, error) {
	row := q.db.QueryRowContext(ctx, getFacilityByName, name)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.DistrictID,
		&i.SubCountyID,
		&i.RegionID,
		&i.FacilityLevel,
		&i.FacilityType,
		&i.Dhis2OrgUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFacilityByNameAndDistrict = `-- name: GetFacilityByNameAndDistrict :one
SELECT id, external_id, name, district_id, sub_county_id, region_id, facility_level, facility_type, dhis2_org_unit_id, latitude, longitude, created_at, updated_at
FROM facilities
WHERE LOWER(name) = LOWER($1)
  AND district_id = $2
LIMIT 1
`

type GetFacilityByNameAndDistrictParams struct {
	Lower      string        `json:"lower"`
	DistrictID uuid.NullUUID `json:"district_id"`
}

func (q *Queries) GetFacilityByNameAndDistrict(ctx context.Context, arg GetFacilityByNameAndDistrictParams) (Facility, error) {
	row := q.db.QueryRowContext(ctx, getFacilityByNameAndDistrict, arg.Lower, arg.DistrictID)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.DistrictID,
		&i.SubCountyID,
		&i.RegionID,
		&i.FacilityLevel,
		&i.FacilityType,
		&i.Dhis2OrgUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFacilities = `-- name: ListFacilities :many
SELECT
  f.id, f.external_id, f.name, f.district_id, f.sub_county_id, f.region_id, f.facility_level, f.facility_type, f.dhis2_org_unit_id, f.latitude, f.longitude, f.created_at, f.updated_at,
  d.name AS district_name,
  sc.name AS sub_county_name,
  r.name AS region_name
FROM facilities f
LEFT JOIN districts d ON d.id = f.district_id
LEFT JOIN sub_counties sc ON sc.id = f.sub_county_id
LEFT JOIN regions r ON r.id = f.region_id
ORDER BY f.name ASC
`

type ListFacilitiesRow struct {
	ID             uuid.UUID      `json:"id"`
	ExternalID     sql.NullString `json:"external_id"`
	Name           string         `json:"name"`
	DistrictID     uuid.NullUUID  `json:"district_id"`
	SubCountyID    uuid.NullUUID  `json:"sub_county_id"`
	RegionID       uuid.NullUUID  `json:"region_id"`
	FacilityLevel  sql.NullString `json:"facility_level"`
	FacilityType   sql.NullString `json:"facility_type"`
	Dhis2OrgUnitID sql.NullString `json:"dhis2_org_unit_id"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DistrictName   sql.NullString `json:"district_name"`
	SubCountyName  sql.NullString `json:"sub_county_name"`
	RegionName     sql.NullString `json:"region_name"`
}

func (q *Queries) ListFacilities(ctx context.Context) ([]ListFacilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFacilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacilitiesRow{}
	for rows.Next() {
		var i ListFacilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.DistrictID,
			&i.SubCountyID,
			&i.RegionID,
			&i.FacilityLevel,
			&i.FacilityType,
			&i.Dhis2OrgUnitID,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DistrictName,
			&i.SubCountyName,
			&i.RegionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacilitiesByDistrict = `-- name: ListFacilitiesByDistrict :many
SELECT id, external_id, name, district_id, sub_county_id, region_id, facility_level, facility_type, dhis2_org_unit_id, latitude, longitude, created_at, updated_at
FROM facilities
WHERE district_id = $1
ORDER BY name ASC
`

func (q *Queries) ListFacilitiesByDistrict(ctx context.Context, districtID uuid.NullUUID) ([]Facility, error) {
	rows, err := q.db.QueryContext(ctx, listFacilitiesByDistrict, districtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Facility{}
	for rows.Next() {
		var i Facility
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Name,
			&i.DistrictID,
			&i.SubCountyID,
			&i.RegionID,
			&i.FacilityLevel,
			&i.FacilityType,
			&i.Dhis2OrgUnitID,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFacilityByExternalID = `-- name: UpsertFacilityByExternalID :one
INSERT INTO facilities (
  external_id,
  name,
  district_id,
  sub_county_id,
  region_id,
  facility_level,
  facility_type,
  dhis2_org_unit_id,
  latitude,
  longitude
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (external_id)
DO UPDATE SET
  name = EXCLUDED.name,
  district_id = COALESCE(EXCLUDED.district_id, facilities.district_id),
  sub_county_id = COALESCE(EXCLUDED.sub_county_id, facilities.sub_county_id),
  region_id = COALESCE(EXCLUDED.region_id, facilities.region_id),
  facility_level = COALESCE(EXCLUDED.facility_level, facilities.facility_level),
  facility_type = COALESCE(EXCLUDED.facility_type, facilities.facility_type),
  dhis2_org_unit_id = COALESCE(EXCLUDED.dhis2_org_unit_id, facilities.dhis2_org_unit_id),
  latitude = COALESCE(EXCLUDED.latitude, facilities.latitude),
  longitude = COALESCE(EXCLUDED.longitude, facilities.longitude),
  updated_at = now()
RETURNING id, external_id, name, district_id, sub_county_id, region_id, facility_level, facility_type, dhis2_org_unit_id, latitude, longitude, created_at, updated_at
`

type UpsertFacilityByExternalIDParams struct {
	ExternalID     sql.NullString `json:"external_id"`
	Name           string         `json:"name"`
	DistrictID     uuid.NullUUID  `json:"district_id"`
	SubCountyID    uuid.NullUUID  `json:"sub_county_id"`
	RegionID       uuid.NullUUID  `json:"region_id"`
	FacilityLevel  sql.NullString `json:"facility_level"`
	FacilityType   sql.NullString `json:"facility_type"`
	Dhis2OrgUnitID sql.NullString `json:"dhis2_org_unit_id"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
}

func (q *Queries) UpsertFacilityByExternalID(ctx context.Context, arg UpsertFacilityByExternalIDParams) (Facility, error) {
	row := q.db.QueryRowContext(ctx, upsertFacilityByExternalID,
		arg.ExternalID,
		arg.Name,
		arg.DistrictID,
		arg.SubCountyID,
		arg.RegionID,
		arg.FacilityLevel,
		arg.FacilityType,
		arg.Dhis2OrgUnitID,
		arg.Latitude,
		arg.Longitude,
	)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.DistrictID,
		&i.SubCountyID,
		&i.RegionID,
		&i.FacilityLevel,
		&i.FacilityType,
		&i.Dhis2OrgUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFacilityByNameDistrict = `-- name: UpsertFacilityByNameDistrict :one
INSERT INTO facilities (
  external_id,
  name,
  district_id,
  sub_county_id,
  region_id,
  facility_level,
  facility_type,
  dhis2_org_unit_id,
  latitude,
  longitude
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (name, district_id)
DO UPDATE SET
  external_id = COALESCE(EXCLUDED.external_id, facilities.external_id),
  sub_county_id = COALESCE(EXCLUDED.sub_county_id, facilities.sub_county_id),
  region_id = COALESCE(EXCLUDED.region_id, facilities.region_id),
  facility_level = COALESCE(EXCLUDED.facility_level, facilities.facility_level),
  facility_type = COALESCE(EXCLUDED.facility_type, facilities.facility_type),
  dhis2_org_unit_id = COALESCE(EXCLUDED.dhis2_org_unit_id, facilities.dhis2_org_unit_id),
  latitude = COALESCE(EXCLUDED.latitude, facilities.latitude),
  longitude = COALESCE(EXCLUDED.longitude, facilities.longitude),
  updated_at = now()
RETURNING id, external_id, name, district_id, sub_county_id, region_id, facility_level, facility_type, dhis2_org_unit_id, latitude, longitude, created_at, updated_at
`

type UpsertFacilityByNameDistrictParams struct {
	ExternalID     sql.NullString `json:"external_id"`
	Name           string         `json:"name"`
	DistrictID     uuid.NullUUID  `json:"district_id"`
	SubCountyID    uuid.NullUUID  `json:"sub_county_id"`
	RegionID       uuid.NullUUID  `json:"region_id"`
	FacilityLevel  sql.NullString `json:"facility_level"`
	FacilityType   sql.NullString `json:"facility_type"`
	Dhis2OrgUnitID sql.NullString `json:"dhis2_org_unit_id"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
}

func (q *Queries) UpsertFacilityByNameDistrict(ctx context.Context, arg UpsertFacilityByNameDistrictParams) (Facility, error) {
	row := q.db.QueryRowContext(ctx, upsertFacilityByNameDistrict,
		arg.ExternalID,
		arg.Name,
		arg.DistrictID,
		arg.SubCountyID,
		arg.RegionID,
		arg.FacilityLevel,
		arg.FacilityType,
		arg.Dhis2OrgUnitID,
		arg.Latitude,
		arg.Longitude,
	)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.DistrictID,
		&i.SubCountyID,
		&i.RegionID,
		&i.FacilityLevel,
		&i.FacilityType,
		&i.Dhis2OrgUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
