// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: facility_weekly_metrics.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFacilityWeeklyDiseaseMetric = `-- name: CreateFacilityWeeklyDiseaseMetric :one
INSERT INTO facility_weekly_metrics (
  source_record_id,
  facility_id,
  disease_id,
  indicator_id,
  epi_week_id,
  metric_value,
  source_name
) VALUES (
  $1, $2, $3, NULL, $4, $5, $6
)
RETURNING id, source_record_id, facility_id, disease_id, indicator_id, epi_week_id, metric_value, source_name, imported_at, created_at
`

type CreateFacilityWeeklyDiseaseMetricParams struct {
	SourceRecordID sql.NullString `json:"source_record_id"`
	FacilityID     uuid.UUID      `json:"facility_id"`
	DiseaseID      uuid.UUID      `json:"disease_id"`
	EpiWeekID      uuid.UUID      `json:"epi_week_id"`
	MetricValue    string         `json:"metric_value"`
	SourceName     sql.NullString `json:"source_name"`
}

func (q *Queries) CreateFacilityWeeklyDiseaseMetric(ctx context.Context, arg CreateFacilityWeeklyDiseaseMetricParams) (FacilityWeeklyMetric, error) {
	row := q.db.QueryRowContext(ctx, createFacilityWeeklyDiseaseMetric,
		arg.SourceRecordID,
		arg.FacilityID,
		arg.DiseaseID,
		arg.EpiWeekID,
		arg.MetricValue,
		arg.SourceName,
	)
	var i FacilityWeeklyMetric
	err := row.Scan(
		&i.ID,
		&i.SourceRecordID,
		&i.FacilityID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.MetricValue,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createFacilityWeeklyIndicatorMetric = `-- name: CreateFacilityWeeklyIndicatorMetric :one
INSERT INTO facility_weekly_metrics (
  source_record_id,
  facility_id,
  disease_id,
  indicator_id,
  epi_week_id,
  metric_value,
  source_name
) VALUES (
  $1, $2, NULL, $3, $4, $5, $6
)
RETURNING id, source_record_id, facility_id, disease_id, indicator_id, epi_week_id, metric_value, source_name, imported_at, created_at
`

type CreateFacilityWeeklyIndicatorMetricParams struct {
	SourceRecordID sql.NullString `json:"source_record_id"`
	FacilityID     uuid.UUID      `json:"facility_id"`
	IndicatorID    uuid.UUID      `json:"indicator_id"`
	EpiWeekID      uuid.UUID      `json:"epi_week_id"`
	MetricValue    string         `json:"metric_value"`
	SourceName     sql.NullString `json:"source_name"`
}

func (q *Queries) CreateFacilityWeeklyIndicatorMetric(ctx context.Context, arg CreateFacilityWeeklyIndicatorMetricParams) (FacilityWeeklyMetric, error) {
	row := q.db.QueryRowContext(ctx, createFacilityWeeklyIndicatorMetric,
		arg.SourceRecordID,
		arg.FacilityID,
		arg.IndicatorID,
		arg.EpiWeekID,
		arg.MetricValue,
		arg.SourceName,
	)
	var i FacilityWeeklyMetric
	err := row.Scan(
		&i.ID,
		&i.SourceRecordID,
		&i.FacilityID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.MetricValue,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFacilityMetricsByWeek = `-- name: DeleteFacilityMetricsByWeek :exec
DELETE FROM facility_weekly_metrics
WHERE epi_week_id = $1
`

func (q *Queries) DeleteFacilityMetricsByWeek(ctx context.Context, epiWeekID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFacilityMetricsByWeek, epiWeekID)
	return err
}

const getFacilityMetricBySourceRecordID = `-- name: GetFacilityMetricBySourceRecordID :one
SELECT id, source_record_id, facility_id, disease_id, indicator_id, epi_week_id, metric_value, source_name, imported_at, created_at
FROM facility_weekly_metrics
WHERE source_record_id = $1
LIMIT 1
`

func (q *Queries) GetFacilityMetricBySourceRecordID(ctx context.Context, sourceRecordID sql.NullString) (FacilityWeeklyMetric, error) {
	row := q.db.QueryRowContext(ctx, getFacilityMetricBySourceRecordID, sourceRecordID)
	var i FacilityWeeklyMetric
	err := row.Scan(
		&i.ID,
		&i.SourceRecordID,
		&i.FacilityID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.MetricValue,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFacilityWeeklyMetricByID = `-- name: GetFacilityWeeklyMetricByID :one
SELECT id, source_record_id, facility_id, disease_id, indicator_id, epi_week_id, metric_value, source_name, imported_at, created_at
FROM facility_weekly_metrics
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFacilityWeeklyMetricByID(ctx context.Context, id uuid.UUID) (FacilityWeeklyMetric, error) {
	row := q.db.QueryRowContext(ctx, getFacilityWeeklyMetricByID, id)
	var i FacilityWeeklyMetric
	err := row.Scan(
		&i.ID,
		&i.SourceRecordID,
		&i.FacilityID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.MetricValue,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFacilityMetricsByFacility = `-- name: ListFacilityMetricsByFacility :many
SELECT
  m.id,
  m.source_record_id,
  m.facility_id,
  m.disease_id,
  m.indicator_id,
  m.epi_week_id,
  m.metric_value,
  m.source_name,
  m.imported_at,
  m.created_at,
  ew.epi_year,
  ew.epi_week,
  CASE
    WHEN m.disease_id IS NOT NULL THEN 'DISEASE'
    ELSE 'INDICATOR'
  END AS subject_type,
  COALESCE(d.name, i.name) AS subject_name
FROM facility_weekly_metrics m
JOIN epi_weeks ew ON ew.id = m.epi_week_id
LEFT JOIN diseases d ON d.id = m.disease_id
LEFT JOIN indicators i ON i.id = m.indicator_id
WHERE m.facility_id = $1
ORDER BY ew.epi_year DESC, ew.epi_week DESC, subject_name ASC
`

type ListFacilityMetricsByFacilityRow struct {
	ID             uuid.UUID      `json:"id"`
	SourceRecordID sql.NullString `json:"source_record_id"`
	FacilityID     uuid.UUID      `json:"facility_id"`
	DiseaseID      uuid.UUID      `json:"disease_id"`
	IndicatorID    uuid.UUID      `json:"indicator_id"`
	EpiWeekID      uuid.UUID      `json:"epi_week_id"`
	MetricValue    string         `json:"metric_value"`
	SourceName     sql.NullString `json:"source_name"`
	ImportedAt     time.Time      `json:"imported_at"`
	CreatedAt      time.Time      `json:"created_at"`
	EpiYear        int32          `json:"epi_year"`
	EpiWeek        int32          `json:"epi_week"`
	SubjectType    string         `json:"subject_type"`
	SubjectName    string         `json:"subject_name"`
}

func (q *Queries) ListFacilityMetricsByFacility(ctx context.Context, facilityID uuid.UUID) ([]ListFacilityMetricsByFacilityRow, error) {
	rows, err := q.db.QueryContext(ctx, listFacilityMetricsByFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacilityMetricsByFacilityRow{}
	for rows.Next() {
		var i ListFacilityMetricsByFacilityRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceRecordID,
			&i.FacilityID,
			&i.DiseaseID,
			&i.IndicatorID,
			&i.EpiWeekID,
			&i.MetricValue,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.EpiYear,
			&i.EpiWeek,
			&i.SubjectType,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacilityWeeklyDiseaseMetricsByWeek = `-- name: ListFacilityWeeklyDiseaseMetricsByWeek :many
SELECT
  m.id, m.source_record_id, m.facility_id, m.disease_id, m.indicator_id, m.epi_week_id, m.metric_value, m.source_name, m.imported_at, m.created_at,
  f.name AS facility_name,
  d.name AS disease_name,
  ew.epi_year,
  ew.epi_week
FROM facility_weekly_metrics m
JOIN facilities f ON f.id = m.facility_id
JOIN diseases d ON d.id = m.disease_id
JOIN epi_weeks ew ON ew.id = m.epi_week_id
WHERE m.epi_week_id = $1
  AND m.disease_id IS NOT NULL
ORDER BY f.name ASC, d.name ASC
`

type ListFacilityWeeklyDiseaseMetricsByWeekRow struct {
	ID             uuid.UUID      `json:"id"`
	SourceRecordID sql.NullString `json:"source_record_id"`
	FacilityID     uuid.UUID      `json:"facility_id"`
	DiseaseID      uuid.UUID      `json:"disease_id"`
	IndicatorID    uuid.UUID      `json:"indicator_id"`
	EpiWeekID      uuid.UUID      `json:"epi_week_id"`
	MetricValue    string         `json:"metric_value"`
	SourceName     sql.NullString `json:"source_name"`
	ImportedAt     time.Time      `json:"imported_at"`
	CreatedAt      time.Time      `json:"created_at"`
	FacilityName   string         `json:"facility_name"`
	DiseaseName    string         `json:"disease_name"`
	EpiYear        int32          `json:"epi_year"`
	EpiWeek        int32          `json:"epi_week"`
}

func (q *Queries) ListFacilityWeeklyDiseaseMetricsByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListFacilityWeeklyDiseaseMetricsByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listFacilityWeeklyDiseaseMetricsByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacilityWeeklyDiseaseMetricsByWeekRow{}
	for rows.Next() {
		var i ListFacilityWeeklyDiseaseMetricsByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceRecordID,
			&i.FacilityID,
			&i.DiseaseID,
			&i.IndicatorID,
			&i.EpiWeekID,
			&i.MetricValue,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.FacilityName,
			&i.DiseaseName,
			&i.EpiYear,
			&i.EpiWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacilityWeeklyIndicatorMetricsByWeek = `-- name: ListFacilityWeeklyIndicatorMetricsByWeek :many
SELECT
  m.id, m.source_record_id, m.facility_id, m.disease_id, m.indicator_id, m.epi_week_id, m.metric_value, m.source_name, m.imported_at, m.created_at,
  f.name AS facility_name,
  i.name AS indicator_name,
  ew.epi_year,
  ew.epi_week
FROM facility_weekly_metrics m
JOIN facilities f ON f.id = m.facility_id
JOIN indicators i ON i.id = m.indicator_id
JOIN epi_weeks ew ON ew.id = m.epi_week_id
WHERE m.epi_week_id = $1
  AND m.indicator_id IS NOT NULL
ORDER BY f.name ASC, i.name ASC
`

type ListFacilityWeeklyIndicatorMetricsByWeekRow struct {
	ID             uuid.UUID      `json:"id"`
	SourceRecordID sql.NullString `json:"source_record_id"`
	FacilityID     uuid.UUID      `json:"facility_id"`
	DiseaseID      uuid.UUID      `json:"disease_id"`
	IndicatorID    uuid.UUID      `json:"indicator_id"`
	EpiWeekID      uuid.UUID      `json:"epi_week_id"`
	MetricValue    string         `json:"metric_value"`
	SourceName     sql.NullString `json:"source_name"`
	ImportedAt     time.Time      `json:"imported_at"`
	CreatedAt      time.Time      `json:"created_at"`
	FacilityName   string         `json:"facility_name"`
	IndicatorName  string         `json:"indicator_name"`
	EpiYear        int32          `json:"epi_year"`
	EpiWeek        int32          `json:"epi_week"`
}

func (q *Queries) ListFacilityWeeklyIndicatorMetricsByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListFacilityWeeklyIndicatorMetricsByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listFacilityWeeklyIndicatorMetricsByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFacilityWeeklyIndicatorMetricsByWeekRow{}
	for rows.Next() {
		var i ListFacilityWeeklyIndicatorMetricsByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceRecordID,
			&i.FacilityID,
			&i.DiseaseID,
			&i.IndicatorID,
			&i.EpiWeekID,
			&i.MetricValue,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.FacilityName,
			&i.IndicatorName,
			&i.EpiYear,
			&i.EpiWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFacilityWeeklyDiseaseMetric = `-- name: UpsertFacilityWeeklyDiseaseMetric :one
INSERT INTO facility_weekly_metrics (
  source_record_id,
  facility_id,
  disease_id,
  indicator_id,
  epi_week_id,
  metric_value,
  source_name
) VALUES (
  $1, $2, $3, NULL, $4, $5, $6
)
ON CONFLICT (facility_id, disease_id, epi_week_id)
WHERE disease_id IS NOT NULL
DO UPDATE SET
  source_record_id = COALESCE(EXCLUDED.source_record_id, facility_weekly_metrics.source_record_id),
  metric_value = EXCLUDED.metric_value,
  source_name = COALESCE(EXCLUDED.source_name, facility_weekly_metrics.source_name),
  imported_at = now()
RETURNING id, source_record_id, facility_id, disease_id, indicator_id, epi_week_id, metric_value, source_name, imported_at, created_at
`

type UpsertFacilityWeeklyDiseaseMetricParams struct {
	SourceRecordID sql.NullString `json:"source_record_id"`
	FacilityID     uuid.UUID      `json:"facility_id"`
	DiseaseID      uuid.UUID      `json:"disease_id"`
	EpiWeekID      uuid.UUID      `json:"epi_week_id"`
	MetricValue    string         `json:"metric_value"`
	SourceName     sql.NullString `json:"source_name"`
}

func (q *Queries) UpsertFacilityWeeklyDiseaseMetric(ctx context.Context, arg UpsertFacilityWeeklyDiseaseMetricParams) (FacilityWeeklyMetric, error) {
	row := q.db.QueryRowContext(ctx, upsertFacilityWeeklyDiseaseMetric,
		arg.SourceRecordID,
		arg.FacilityID,
		arg.DiseaseID,
		arg.EpiWeekID,
		arg.MetricValue,
		arg.SourceName,
	)
	var i FacilityWeeklyMetric
	err := row.Scan(
		&i.ID,
		&i.SourceRecordID,
		&i.FacilityID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.MetricValue,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertFacilityWeeklyIndicatorMetric = `-- name: UpsertFacilityWeeklyIndicatorMetric :one
INSERT INTO facility_weekly_metrics (
  source_record_id,
  facility_id,
  disease_id,
  indicator_id,
  epi_week_id,
  metric_value,
  source_name
) VALUES (
  $1, $2, NULL, $3, $4, $5, $6
)
ON CONFLICT (facility_id, indicator_id, epi_week_id)
WHERE indicator_id IS NOT NULL
DO UPDATE SET
  source_record_id = COALESCE(EXCLUDED.source_record_id, facility_weekly_metrics.source_record_id),
  metric_value = EXCLUDED.metric_value,
  source_name = COALESCE(EXCLUDED.source_name, facility_weekly_metrics.source_name),
  imported_at = now()
RETURNING id, source_record_id, facility_id, disease_id, indicator_id, epi_week_id, metric_value, source_name, imported_at, created_at
`

type UpsertFacilityWeeklyIndicatorMetricParams struct {
	SourceRecordID sql.NullString `json:"source_record_id"`
	FacilityID     uuid.UUID      `json:"facility_id"`
	IndicatorID    uuid.UUID      `json:"indicator_id"`
	EpiWeekID      uuid.UUID      `json:"epi_week_id"`
	MetricValue    string         `json:"metric_value"`
	SourceName     sql.NullString `json:"source_name"`
}

func (q *Queries) UpsertFacilityWeeklyIndicatorMetric(ctx context.Context, arg UpsertFacilityWeeklyIndicatorMetricParams) (FacilityWeeklyMetric, error) {
	row := q.db.QueryRowContext(ctx, upsertFacilityWeeklyIndicatorMetric,
		arg.SourceRecordID,
		arg.FacilityID,
		arg.IndicatorID,
		arg.EpiWeekID,
		arg.MetricValue,
		arg.SourceName,
	)
	var i FacilityWeeklyMetric
	err := row.Scan(
		&i.ID,
		&i.SourceRecordID,
		&i.FacilityID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.MetricValue,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}
