// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: indicators.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createIndicator = `-- name: CreateIndicator :one
INSERT INTO indicators (
  name,
  short_name,
  code,
  indicator_type
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, short_name, code, indicator_type, is_active, created_at, updated_at
`

type CreateIndicatorParams struct {
	Name          string         `json:"name"`
	ShortName     sql.NullString `json:"short_name"`
	Code          sql.NullString `json:"code"`
	IndicatorType sql.NullString `json:"indicator_type"`
}

func (q *Queries) CreateIndicator(ctx context.Context, arg CreateIndicatorParams) (Indicator, error) {
	row := q.db.QueryRowContext(ctx, createIndicator,
		arg.Name,
		arg.ShortName,
		arg.Code,
		arg.IndicatorType,
	)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.IndicatorType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIndicator = `-- name: DeleteIndicator :exec
DELETE FROM indicators
WHERE id = $1
`

func (q *Queries) DeleteIndicator(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteIndicator, id)
	return err
}

const existsDiseaseIndicator = `-- name: ExistsDiseaseIndicator :one
SELECT EXISTS (
  SELECT 1
  FROM disease_indicators
  WHERE disease_id = $1
    AND indicator_id = $2
    AND is_active = TRUE
)
`

type ExistsDiseaseIndicatorParams struct {
	DiseaseID   uuid.UUID `json:"disease_id"`
	IndicatorID uuid.UUID `json:"indicator_id"`
}

func (q *Queries) ExistsDiseaseIndicator(ctx context.Context, arg ExistsDiseaseIndicatorParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsDiseaseIndicator, arg.DiseaseID, arg.IndicatorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getIndicatorByID = `-- name: GetIndicatorByID :one
SELECT id, name, short_name, code, indicator_type, is_active, created_at, updated_at
FROM indicators
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetIndicatorByID(ctx context.Context, id uuid.UUID) (Indicator, error) {
	row := q.db.QueryRowContext(ctx, getIndicatorByID, id)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.IndicatorType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIndicatorByName = `-- name: GetIndicatorByName :one
SELECT id, name, short_name, code, indicator_type, is_active, created_at, updated_at
FROM indicators
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetIndicatorByName(ctx context.Context, lower string) (Indicator, error) {
	row := q.db.QueryRowContext(ctx, getIndicatorByName, lower)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.IndicatorType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveIndicators = `-- name: ListActiveIndicators :many
SELECT id, name, short_name, code, indicator_type, is_active, created_at, updated_at
FROM indicators
WHERE is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListActiveIndicators(ctx context.Context) ([]Indicator, error) {
	rows, err := q.db.QueryContext(ctx, listActiveIndicators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Indicator{}
	for rows.Next() {
		var i Indicator
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.Code,
			&i.IndicatorType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndicators = `-- name: ListIndicators :many
SELECT id, name, short_name, code, indicator_type, is_active, created_at, updated_at
FROM indicators
ORDER BY name ASC
`

func (q *Queries) ListIndicators(ctx context.Context) ([]Indicator, error) {
	rows, err := q.db.QueryContext(ctx, listIndicators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Indicator{}
	for rows.Next() {
		var i Indicator
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.Code,
			&i.IndicatorType,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIndicatorActiveState = `-- name: SetIndicatorActiveState :one
UPDATE indicators
SET
  is_active = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, name, short_name, code, indicator_type, is_active, created_at, updated_at
`

type SetIndicatorActiveStateParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetIndicatorActiveState(ctx context.Context, arg SetIndicatorActiveStateParams) (Indicator, error) {
	row := q.db.QueryRowContext(ctx, setIndicatorActiveState, arg.ID, arg.IsActive)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.IndicatorType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIndicator = `-- name: UpsertIndicator :one
INSERT INTO indicators (
  name,
  short_name,
  code,
  indicator_type
) VALUES (
  $1, $2, $3, $4
)
ON CONFLICT (name)
DO UPDATE SET
  short_name = COALESCE(EXCLUDED.short_name, indicators.short_name),
  code = COALESCE(EXCLUDED.code, indicators.code),
  indicator_type = COALESCE(EXCLUDED.indicator_type, indicators.indicator_type),
  updated_at = now()
RETURNING id, name, short_name, code, indicator_type, is_active, created_at, updated_at
`

type UpsertIndicatorParams struct {
	Name          string         `json:"name"`
	ShortName     sql.NullString `json:"short_name"`
	Code          sql.NullString `json:"code"`
	IndicatorType sql.NullString `json:"indicator_type"`
}

func (q *Queries) UpsertIndicator(ctx context.Context, arg UpsertIndicatorParams) (Indicator, error) {
	row := q.db.QueryRowContext(ctx, upsertIndicator,
		arg.Name,
		arg.ShortName,
		arg.Code,
		arg.IndicatorType,
	)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.IndicatorType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
