// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lookup.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const resolveDiseaseByName = `-- name: ResolveDiseaseByName :one
SELECT id, name, short_name, code, category, is_active, created_at, updated_at
FROM diseases
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

func (q *Queries) ResolveDiseaseByName(ctx context.Context, lower string) (Disease, error) {
	row := q.db.QueryRowContext(ctx, resolveDiseaseByName, lower)
	var i Disease
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveDistrictByName = `-- name: ResolveDistrictByName :one
SELECT id, name, region_id, code, created_at, updated_at
FROM districts
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

func (q *Queries) ResolveDistrictByName(ctx context.Context, lower string) (District, error) {
	row := q.db.QueryRowContext(ctx, resolveDistrictByName, lower)
	var i District
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegionID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveFacilityByExternalID = `-- name: ResolveFacilityByExternalID :one
SELECT id, external_id, name, district_id, sub_county_id, region_id, facility_level, facility_type, dhis2_org_unit_id, latitude, longitude, created_at, updated_at
FROM facilities
WHERE external_id = $1
LIMIT 1
`

func (q *Queries) ResolveFacilityByExternalID(ctx context.Context, externalID sql.NullString) (Facility, error) {
	row := q.db.QueryRowContext(ctx, resolveFacilityByExternalID, externalID)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.DistrictID,
		&i.SubCountyID,
		&i.RegionID,
		&i.FacilityLevel,
		&i.FacilityType,
		&i.Dhis2OrgUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveFacilityByNameAndDistrict = `-- name: ResolveFacilityByNameAndDistrict :one
SELECT id, external_id, name, district_id, sub_county_id, region_id, facility_level, facility_type, dhis2_org_unit_id, latitude, longitude, created_at, updated_at
FROM facilities
WHERE LOWER(name) = LOWER($1)
  AND district_id = $2
LIMIT 1
`

type ResolveFacilityByNameAndDistrictParams struct {
	Lower      string        `json:"lower"`
	DistrictID uuid.NullUUID `json:"district_id"`
}

func (q *Queries) ResolveFacilityByNameAndDistrict(ctx context.Context, arg ResolveFacilityByNameAndDistrictParams) (Facility, error) {
	row := q.db.QueryRowContext(ctx, resolveFacilityByNameAndDistrict, arg.Lower, arg.DistrictID)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.DistrictID,
		&i.SubCountyID,
		&i.RegionID,
		&i.FacilityLevel,
		&i.FacilityType,
		&i.Dhis2OrgUnitID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveIndicatorByName = `-- name: ResolveIndicatorByName :one
SELECT id, name, short_name, code, indicator_type, is_active, created_at, updated_at
FROM indicators
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

func (q *Queries) ResolveIndicatorByName(ctx context.Context, lower string) (Indicator, error) {
	row := q.db.QueryRowContext(ctx, resolveIndicatorByName, lower)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.IndicatorType,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveRegionByName = `-- name: ResolveRegionByName :one
SELECT id, name, code, created_at, updated_at
FROM regions
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

func (q *Queries) ResolveRegionByName(ctx context.Context, lower string) (Region, error) {
	row := q.db.QueryRowContext(ctx, resolveRegionByName, lower)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveSubCountyByNameAndDistrict = `-- name: ResolveSubCountyByNameAndDistrict :one
SELECT id, name, district_id, code, created_at, updated_at
FROM sub_counties
WHERE LOWER(name) = LOWER($1)
  AND district_id = $2
LIMIT 1
`

type ResolveSubCountyByNameAndDistrictParams struct {
	Lower      string    `json:"lower"`
	DistrictID uuid.UUID `json:"district_id"`
}

func (q *Queries) ResolveSubCountyByNameAndDistrict(ctx context.Context, arg ResolveSubCountyByNameAndDistrictParams) (SubCounty, error) {
	row := q.db.QueryRowContext(ctx, resolveSubCountyByNameAndDistrict, arg.Lower, arg.DistrictID)
	var i SubCounty
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DistrictID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveWeekByYearWeek = `-- name: ResolveWeekByYearWeek :one
SELECT id, epi_year, epi_week, week_start_date, week_end_date, created_at
FROM epi_weeks
WHERE epi_year = $1
  AND epi_week = $2
LIMIT 1
`

type ResolveWeekByYearWeekParams struct {
	EpiYear int32 `json:"epi_year"`
	EpiWeek int32 `json:"epi_week"`
}

func (q *Queries) ResolveWeekByYearWeek(ctx context.Context, arg ResolveWeekByYearWeekParams) (EpiWeek, error) {
	row := q.db.QueryRowContext(ctx, resolveWeekByYearWeek, arg.EpiYear, arg.EpiWeek)
	var i EpiWeek
	err := row.Scan(
		&i.ID,
		&i.EpiYear,
		&i.EpiWeek,
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.CreatedAt,
	)
	return i, err
}
