// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AlertStatus string

const (
	AlertStatusNEW           AlertStatus = "NEW"
	AlertStatusACKNOWLEDGE   AlertStatus = "ACKNOWLEDGE"
	AlertStatusINVESTIGATING AlertStatus = "INVESTIGATING"
	AlertStatusRESOLVED      AlertStatus = "RESOLVED"
	AlertStatusCLOSED        AlertStatus = "CLOSED"
)

func (e *AlertStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertStatus(s)
	case string:
		*e = AlertStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertStatus: %T", src)
	}
	return nil
}

type NullAlertStatus struct {
	AlertStatus AlertStatus `json:"alert_status"`
	Valid       bool        `json:"valid"` // Valid is true if AlertStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlertStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertStatus), nil
}

type ImportJobStatus string

const (
	ImportJobStatusPreviewed ImportJobStatus = "previewed"
	ImportJobStatusRunning   ImportJobStatus = "running"
	ImportJobStatusCompleted ImportJobStatus = "completed"
	ImportJobStatusFailed    ImportJobStatus = "failed"
)

func (e *ImportJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportJobStatus(s)
	case string:
		*e = ImportJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportJobStatus: %T", src)
	}
	return nil
}

type NullImportJobStatus struct {
	ImportJobStatus ImportJobStatus `json:"import_job_status"`
	Valid           bool            `json:"valid"` // Valid is true if ImportJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImportJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportJobStatus), nil
}

type RiskLevel string

const (
	RiskLevelMAROON RiskLevel = "MAROON"
	RiskLevelRED    RiskLevel = "RED"
	RiskLevelYELLOW RiskLevel = "YELLOW"
	RiskLevelGREEN  RiskLevel = "GREEN"
)

func (e *RiskLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiskLevel(s)
	case string:
		*e = RiskLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for RiskLevel: %T", src)
	}
	return nil
}

type NullRiskLevel struct {
	RiskLevel RiskLevel `json:"risk_level"`
	Valid     bool      `json:"valid"` // Valid is true if RiskLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiskLevel) Scan(value interface{}) error {
	if value == nil {
		ns.RiskLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiskLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiskLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiskLevel), nil
}

type Alert struct {
	ID          uuid.UUID      `json:"id"`
	ExternalID  sql.NullString `json:"external_id"`
	DiseaseID   uuid.UUID      `json:"disease_id"`
	DistrictID  uuid.NullUUID  `json:"district_id"`
	EpiWeekID   uuid.NullUUID  `json:"epi_week_id"`
	OccurredOn  sql.NullTime   `json:"occurred_on"`
	CreatedOn   sql.NullTime   `json:"created_on"`
	Narrative   string         `json:"narrative"`
	SubmittedBy sql.NullString `json:"submitted_by"`
	Status      AlertStatus    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
	ImportedAt  time.Time      `json:"imported_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Announcement struct {
	ID           uuid.UUID      `json:"id"`
	Title        string         `json:"title"`
	Message      string         `json:"message"`
	Summary      sql.NullString `json:"summary"`
	Level        interface{}    `json:"level"`
	Tag          sql.NullString `json:"tag"`
	LinkUrl      sql.NullString `json:"link_url"`
	Priority     int32          `json:"priority"`
	IsPinned     bool           `json:"is_pinned"`
	Status       interface{}    `json:"status"`
	PublishAt    sql.NullTime   `json:"publish_at"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
	AudienceType interface{}    `json:"audience_type"`
	CreatedBy    uuid.UUID      `json:"created_by"`
	UpdatedBy    uuid.NullUUID  `json:"updated_by"`
	PublishedBy  uuid.NullUUID  `json:"published_by"`
	ArchivedBy   uuid.NullUUID  `json:"archived_by"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	PublishedAt  sql.NullTime   `json:"published_at"`
	ArchivedAt   sql.NullTime   `json:"archived_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	DeletedBy    uuid.NullUUID  `json:"deleted_by"`
	Version      int32          `json:"version"`
}

type AnnouncementClient struct {
	AnnouncementID uuid.UUID `json:"announcement_id"`
	ClientID       uuid.UUID `json:"client_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type AnnouncementRole struct {
	AnnouncementID uuid.UUID `json:"announcement_id"`
	RoleName       string    `json:"role_name"`
	CreatedAt      time.Time `json:"created_at"`
}

type AnnouncementUser struct {
	AnnouncementID uuid.UUID `json:"announcement_id"`
	UserID         uuid.UUID `json:"user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type AuditLog struct {
	ID        uuid.UUID             `json:"id"`
	UserID    uuid.NullUUID         `json:"user_id"`
	Action    string                `json:"action"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Client struct {
	ID           uuid.UUID       `json:"id"`
	ClientID     string          `json:"client_id"`
	Name         string          `json:"name"`
	Description  sql.NullString  `json:"description"`
	Icon         sql.NullString  `json:"icon"`
	BaseUrl      sql.NullString  `json:"base_url"`
	RootUrl      sql.NullString  `json:"root_url"`
	AdminUrl     sql.NullString  `json:"admin_url"`
	PublicClient bool            `json:"public_client"`
	RedirectUris []string        `json:"redirect_uris"`
	WebOrigins   []string        `json:"web_origins"`
	Enabled      bool            `json:"enabled"`
	Attributes   json.RawMessage `json:"attributes"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type ClientSecret struct {
	ID         uuid.UUID    `json:"id"`
	ClientID   uuid.UUID    `json:"client_id"`
	SecretHash string       `json:"secret_hash"`
	CreatedAt  sql.NullTime `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
}

type Disease struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	ShortName sql.NullString `json:"short_name"`
	Code      sql.NullString `json:"code"`
	Category  sql.NullString `json:"category"`
	IsActive  bool           `json:"is_active"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type District struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	RegionID  uuid.NullUUID  `json:"region_id"`
	Code      sql.NullString `json:"code"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type DistrictWeeklyStatus struct {
	ID          uuid.UUID      `json:"id"`
	DistrictID  uuid.UUID      `json:"district_id"`
	DiseaseID   uuid.UUID      `json:"disease_id"`
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      RiskLevel      `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
	ImportedAt  time.Time      `json:"imported_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Document struct {
	ID                uuid.UUID      `json:"id"`
	OriginalFilename  string         `json:"original_filename"`
	ContentType       sql.NullString `json:"content_type"`
	SizeBytes         int64          `json:"size_bytes"`
	ChecksumSha256    sql.NullString `json:"checksum_sha256"`
	StorageLocationID uuid.UUID      `json:"storage_location_id"`
	ObjectKey         string         `json:"object_key"`
	UploadedBy        uuid.UUID      `json:"uploaded_by"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}

type EpiWeek struct {
	ID            uuid.UUID    `json:"id"`
	EpiYear       int32        `json:"epi_year"`
	EpiWeek       int32        `json:"epi_week"`
	WeekStartDate sql.NullTime `json:"week_start_date"`
	WeekEndDate   sql.NullTime `json:"week_end_date"`
	CreatedAt     time.Time    `json:"created_at"`
}

type Facility struct {
	ID             uuid.UUID      `json:"id"`
	ExternalID     sql.NullString `json:"external_id"`
	Name           string         `json:"name"`
	DistrictID     uuid.NullUUID  `json:"district_id"`
	SubCountyID    uuid.NullUUID  `json:"sub_county_id"`
	RegionID       uuid.NullUUID  `json:"region_id"`
	FacilityLevel  sql.NullString `json:"facility_level"`
	FacilityType   sql.NullString `json:"facility_type"`
	Dhis2OrgUnitID sql.NullString `json:"dhis2_org_unit_id"`
	Latitude       sql.NullString `json:"latitude"`
	Longitude      sql.NullString `json:"longitude"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type FacilityWeeklyMetric struct {
	ID             uuid.UUID      `json:"id"`
	SourceRecordID sql.NullString `json:"source_record_id"`
	FacilityID     uuid.UUID      `json:"facility_id"`
	DiseaseID      uuid.UUID      `json:"disease_id"`
	IndicatorID    uuid.UUID      `json:"indicator_id"`
	EpiWeekID      uuid.UUID      `json:"epi_week_id"`
	MetricValue    string         `json:"metric_value"`
	SourceName     sql.NullString `json:"source_name"`
	ImportedAt     time.Time      `json:"imported_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

type ImportJob struct {
	ID           uuid.UUID       `json:"id"`
	Filename     string          `json:"filename"`
	Status       ImportJobStatus `json:"status"`
	TotalRows    int32           `json:"total_rows"`
	ValidRows    int32           `json:"valid_rows"`
	SuccessCount int32           `json:"success_count"`
	FailureCount int32           `json:"failure_count"`
	CreatedBy    string          `json:"created_by"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type ImportJobItem struct {
	ID          uuid.UUID      `json:"id"`
	JobID       uuid.UUID      `json:"job_id"`
	RowNumber   int32          `json:"row_number"`
	Username    sql.NullString `json:"username"`
	Email       sql.NullString `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	Roles       []string       `json:"roles"`
	Enabled     sql.NullBool   `json:"enabled"`
	EmailSent   bool           `json:"email_sent"`
	EmailSentAt time.Time      `json:"email_sent_at"`
	ClientIds   sql.NullString `json:"client_ids"`
	Status      string         `json:"status"`
	ErrorMsg    sql.NullString `json:"error_msg"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Indicator struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	ShortName     sql.NullString `json:"short_name"`
	Code          sql.NullString `json:"code"`
	IndicatorType sql.NullString `json:"indicator_type"`
	IsActive      bool           `json:"is_active"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type NationalWeeklyStatus struct {
	ID          uuid.UUID      `json:"id"`
	DiseaseID   uuid.UUID      `json:"disease_id"`
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      RiskLevel      `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
	ImportedAt  time.Time      `json:"imported_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Notification struct {
	ID         uuid.UUID             `json:"id"`
	Type       string                `json:"type"`
	Title      string                `json:"title"`
	Message    string                `json:"message"`
	Severity   sql.NullString        `json:"severity"`
	TargetRole string                `json:"target_role"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	Read       sql.NullBool          `json:"read"`
	CreatedAt  sql.NullTime          `json:"created_at"`
}

type Process struct {
	ID          uuid.UUID      `json:"id"`
	DocumentID  uuid.UUID      `json:"document_id"`
	ProcessType string         `json:"process_type"`
	Status      interface{}    `json:"status"`
	Progress    int32          `json:"progress"`
	Message     sql.NullString `json:"message"`
	Error       sql.NullString `json:"error"`
	Attempts    int32          `json:"attempts"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	StartedAt   sql.NullTime   `json:"started_at"`
	FinishedAt  sql.NullTime   `json:"finished_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Region struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Code      sql.NullString `json:"code"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type RegionWeeklyStatus struct {
	ID          uuid.UUID      `json:"id"`
	RegionID    uuid.UUID      `json:"region_id"`
	DiseaseID   uuid.UUID      `json:"disease_id"`
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      RiskLevel      `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
	ImportedAt  time.Time      `json:"imported_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type RevokedToken struct {
	ID        int64        `json:"id"`
	TokenHash string       `json:"token_hash"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	UserAgent    sql.NullString `json:"user_agent"`
	IpAddress    sql.NullString `json:"ip_address"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
}

type StorageLocation struct {
	ID        uuid.UUID    `json:"id"`
	Code      string       `json:"code"`
	Name      string       `json:"name"`
	Provider  string       `json:"provider"`
	BaseUri   string       `json:"base_uri"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type SubCounty struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	DistrictID uuid.UUID      `json:"district_id"`
	Code       sql.NullString `json:"code"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type SurveillanceImportBatch struct {
	ID          uuid.UUID      `json:"id"`
	SourceName  string         `json:"source_name"`
	FileName    sql.NullString `json:"file_name"`
	DatasetType string         `json:"dataset_type"`
	ImportedBy  sql.NullString `json:"imported_by"`
	ImportedAt  time.Time      `json:"imported_at"`
	Status      string         `json:"status"`
	Notes       sql.NullString `json:"notes"`
}

type SurveillanceImportRawRow struct {
	ID        uuid.UUID       `json:"id"`
	BatchID   uuid.UUID       `json:"batch_id"`
	RowNumber int32           `json:"row_number"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	Email       string         `json:"email"`
	Enabled     sql.NullBool   `json:"enabled"`
	Roles       []string       `json:"roles"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	LastLoginAt sql.NullTime   `json:"last_login_at"`
}

type UserClientAccess struct {
	UserID    uuid.UUID    `json:"user_id"`
	ClientID  uuid.UUID    `json:"client_id"`
	GrantedAt sql.NullTime `json:"granted_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
