// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ImportJobStatus string

const (
	ImportJobStatusPreviewed ImportJobStatus = "previewed"
	ImportJobStatusRunning   ImportJobStatus = "running"
	ImportJobStatusCompleted ImportJobStatus = "completed"
	ImportJobStatusFailed    ImportJobStatus = "failed"
)

func (e *ImportJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportJobStatus(s)
	case string:
		*e = ImportJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportJobStatus: %T", src)
	}
	return nil
}

type NullImportJobStatus struct {
	ImportJobStatus ImportJobStatus `json:"import_job_status"`
	Valid           bool            `json:"valid"` // Valid is true if ImportJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImportJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportJobStatus), nil
}

type AuditLog struct {
	ID        uuid.UUID             `json:"id"`
	UserID    uuid.NullUUID         `json:"user_id"`
	Action    string                `json:"action"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Client struct {
	ID           uuid.UUID       `json:"id"`
	ClientID     string          `json:"client_id"`
	Name         string          `json:"name"`
	Description  sql.NullString  `json:"description"`
	Icon         sql.NullString  `json:"icon"`
	BaseUrl      sql.NullString  `json:"base_url"`
	RootUrl      sql.NullString  `json:"root_url"`
	AdminUrl     sql.NullString  `json:"admin_url"`
	PublicClient bool            `json:"public_client"`
	RedirectUris []string        `json:"redirect_uris"`
	WebOrigins   []string        `json:"web_origins"`
	Enabled      bool            `json:"enabled"`
	Attributes   json.RawMessage `json:"attributes"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type ClientSecret struct {
	ID         uuid.UUID    `json:"id"`
	ClientID   uuid.UUID    `json:"client_id"`
	SecretHash string       `json:"secret_hash"`
	CreatedAt  sql.NullTime `json:"created_at"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
}

type Document struct {
	ID                uuid.UUID      `json:"id"`
	OriginalFilename  string         `json:"original_filename"`
	ContentType       sql.NullString `json:"content_type"`
	SizeBytes         int64          `json:"size_bytes"`
	ChecksumSha256    sql.NullString `json:"checksum_sha256"`
	StorageLocationID uuid.UUID      `json:"storage_location_id"`
	ObjectKey         string         `json:"object_key"`
	UploadedBy        uuid.UUID      `json:"uploaded_by"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}

type ImportJob struct {
	ID           uuid.UUID       `json:"id"`
	Filename     string          `json:"filename"`
	Status       ImportJobStatus `json:"status"`
	TotalRows    int32           `json:"total_rows"`
	ValidRows    int32           `json:"valid_rows"`
	SuccessCount int32           `json:"success_count"`
	FailureCount int32           `json:"failure_count"`
	CreatedBy    string          `json:"created_by"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type ImportJobItem struct {
	ID          uuid.UUID      `json:"id"`
	JobID       uuid.UUID      `json:"job_id"`
	RowNumber   int32          `json:"row_number"`
	Username    sql.NullString `json:"username"`
	Email       sql.NullString `json:"email"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	Roles       []string       `json:"roles"`
	Enabled     sql.NullBool   `json:"enabled"`
	EmailSent   bool           `json:"email_sent"`
	EmailSentAt time.Time      `json:"email_sent_at"`
	ClientIds   sql.NullString `json:"client_ids"`
	Status      string         `json:"status"`
	ErrorMsg    sql.NullString `json:"error_msg"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Notification struct {
	ID         uuid.UUID             `json:"id"`
	Type       string                `json:"type"`
	Title      string                `json:"title"`
	Message    string                `json:"message"`
	Severity   sql.NullString        `json:"severity"`
	TargetRole string                `json:"target_role"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	Read       sql.NullBool          `json:"read"`
	CreatedAt  sql.NullTime          `json:"created_at"`
}

type Process struct {
	ID          uuid.UUID      `json:"id"`
	DocumentID  uuid.UUID      `json:"document_id"`
	ProcessType string         `json:"process_type"`
	Status      interface{}    `json:"status"`
	Progress    int32          `json:"progress"`
	Message     sql.NullString `json:"message"`
	Error       sql.NullString `json:"error"`
	Attempts    int32          `json:"attempts"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	StartedAt   sql.NullTime   `json:"started_at"`
	FinishedAt  sql.NullTime   `json:"finished_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type RevokedToken struct {
	ID        int64        `json:"id"`
	TokenHash string       `json:"token_hash"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	RefreshToken string         `json:"refresh_token"`
	UserAgent    sql.NullString `json:"user_agent"`
	IpAddress    sql.NullString `json:"ip_address"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	ExpiresAt    time.Time      `json:"expires_at"`
}

type StorageLocation struct {
	ID        uuid.UUID    `json:"id"`
	Code      string       `json:"code"`
	Name      string       `json:"name"`
	Provider  string       `json:"provider"`
	BaseUri   string       `json:"base_uri"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	Email       string         `json:"email"`
	Enabled     sql.NullBool   `json:"enabled"`
	Roles       []string       `json:"roles"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	LastLoginAt sql.NullTime   `json:"last_login_at"`
}

type UserClientAccess struct {
	UserID    uuid.UUID    `json:"user_id"`
	ClientID  uuid.UUID    `json:"client_id"`
	GrantedAt sql.NullTime `json:"granted_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
