// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: national_weekly_status.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createNationalWeeklyDiseaseStatus = `-- name: CreateNationalWeeklyDiseaseStatus :one
INSERT INTO national_weekly_status (
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  $1, NULL, $2, $3, $4
)
RETURNING id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type CreateNationalWeeklyDiseaseStatusParams struct {
	DiseaseID  uuid.UUID      `json:"disease_id"`
	EpiWeekID  uuid.UUID      `json:"epi_week_id"`
	Status     RiskLevel      `json:"status"`
	SourceName sql.NullString `json:"source_name"`
}

func (q *Queries) CreateNationalWeeklyDiseaseStatus(ctx context.Context, arg CreateNationalWeeklyDiseaseStatusParams) (NationalWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, createNationalWeeklyDiseaseStatus,
		arg.DiseaseID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i NationalWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNationalWeeklyIndicatorStatus = `-- name: CreateNationalWeeklyIndicatorStatus :one
INSERT INTO national_weekly_status (
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  NULL, $1, $2, $3, $4
)
RETURNING id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type CreateNationalWeeklyIndicatorStatusParams struct {
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      RiskLevel      `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
}

func (q *Queries) CreateNationalWeeklyIndicatorStatus(ctx context.Context, arg CreateNationalWeeklyIndicatorStatusParams) (NationalWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, createNationalWeeklyIndicatorStatus,
		arg.IndicatorID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i NationalWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNationalStatusesByWeek = `-- name: DeleteNationalStatusesByWeek :exec
DELETE FROM national_weekly_status
WHERE epi_week_id = $1
`

func (q *Queries) DeleteNationalStatusesByWeek(ctx context.Context, epiWeekID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNationalStatusesByWeek, epiWeekID)
	return err
}

const listNationalWeeklyDiseaseStatusesByWeek = `-- name: ListNationalWeeklyDiseaseStatusesByWeek :many
SELECT
  s.id, s.disease_id, s.indicator_id, s.epi_week_id, s.status, s.source_name, s.imported_at, s.created_at,
  d.name AS disease_name
FROM national_weekly_status s
JOIN diseases d ON d.id = s.disease_id
WHERE s.epi_week_id = $1
  AND s.disease_id IS NOT NULL
ORDER BY
  CASE s.status
    WHEN 'MAROON' THEN 1
    WHEN 'RED' THEN 2
    WHEN 'YELLOW' THEN 3
    WHEN 'GREEN' THEN 4
  END,
  d.name ASC
`

type ListNationalWeeklyDiseaseStatusesByWeekRow struct {
	ID          uuid.UUID      `json:"id"`
	DiseaseID   uuid.UUID      `json:"disease_id"`
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      RiskLevel      `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
	ImportedAt  time.Time      `json:"imported_at"`
	CreatedAt   time.Time      `json:"created_at"`
	DiseaseName string         `json:"disease_name"`
}

func (q *Queries) ListNationalWeeklyDiseaseStatusesByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListNationalWeeklyDiseaseStatusesByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listNationalWeeklyDiseaseStatusesByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNationalWeeklyDiseaseStatusesByWeekRow{}
	for rows.Next() {
		var i ListNationalWeeklyDiseaseStatusesByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.DiseaseID,
			&i.IndicatorID,
			&i.EpiWeekID,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.DiseaseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNationalWeeklyIndicatorStatusesByWeek = `-- name: ListNationalWeeklyIndicatorStatusesByWeek :many
SELECT
  s.id, s.disease_id, s.indicator_id, s.epi_week_id, s.status, s.source_name, s.imported_at, s.created_at,
  i.name AS indicator_name
FROM national_weekly_status s
JOIN indicators i ON i.id = s.indicator_id
WHERE s.epi_week_id = $1
  AND s.indicator_id IS NOT NULL
ORDER BY
  CASE s.status
    WHEN 'MAROON' THEN 1
    WHEN 'RED' THEN 2
    WHEN 'YELLOW' THEN 3
    WHEN 'GREEN' THEN 4
  END,
  i.name ASC
`

type ListNationalWeeklyIndicatorStatusesByWeekRow struct {
	ID            uuid.UUID      `json:"id"`
	DiseaseID     uuid.UUID      `json:"disease_id"`
	IndicatorID   uuid.UUID      `json:"indicator_id"`
	EpiWeekID     uuid.UUID      `json:"epi_week_id"`
	Status        RiskLevel      `json:"status"`
	SourceName    sql.NullString `json:"source_name"`
	ImportedAt    time.Time      `json:"imported_at"`
	CreatedAt     time.Time      `json:"created_at"`
	IndicatorName string         `json:"indicator_name"`
}

func (q *Queries) ListNationalWeeklyIndicatorStatusesByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListNationalWeeklyIndicatorStatusesByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listNationalWeeklyIndicatorStatusesByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNationalWeeklyIndicatorStatusesByWeekRow{}
	for rows.Next() {
		var i ListNationalWeeklyIndicatorStatusesByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.DiseaseID,
			&i.IndicatorID,
			&i.EpiWeekID,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.IndicatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNationalWeeklyDiseaseStatus = `-- name: UpsertNationalWeeklyDiseaseStatus :one
INSERT INTO national_weekly_status (
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  $1, NULL, $2, $3, $4
)
ON CONFLICT (disease_id, epi_week_id)
WHERE disease_id IS NOT NULL
DO UPDATE SET
  status = EXCLUDED.status,
  source_name = COALESCE(EXCLUDED.source_name, national_weekly_status.source_name),
  imported_at = now()
RETURNING id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type UpsertNationalWeeklyDiseaseStatusParams struct {
	DiseaseID  uuid.UUID      `json:"disease_id"`
	EpiWeekID  uuid.UUID      `json:"epi_week_id"`
	Status     RiskLevel      `json:"status"`
	SourceName sql.NullString `json:"source_name"`
}

func (q *Queries) UpsertNationalWeeklyDiseaseStatus(ctx context.Context, arg UpsertNationalWeeklyDiseaseStatusParams) (NationalWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertNationalWeeklyDiseaseStatus,
		arg.DiseaseID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i NationalWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertNationalWeeklyIndicatorStatus = `-- name: UpsertNationalWeeklyIndicatorStatus :one
INSERT INTO national_weekly_status (
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  NULL, $1, $2, $3, $4
)
ON CONFLICT (indicator_id, epi_week_id)
WHERE indicator_id IS NOT NULL
DO UPDATE SET
  status = EXCLUDED.status,
  source_name = COALESCE(EXCLUDED.source_name, national_weekly_status.source_name),
  imported_at = now()
RETURNING id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type UpsertNationalWeeklyIndicatorStatusParams struct {
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      RiskLevel      `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
}

func (q *Queries) UpsertNationalWeeklyIndicatorStatus(ctx context.Context, arg UpsertNationalWeeklyIndicatorStatusParams) (NationalWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertNationalWeeklyIndicatorStatus,
		arg.IndicatorID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i NationalWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}
