// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_deliveries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const cancelNotificationDelivery = `-- name: CancelNotificationDelivery :exec
UPDATE notification_deliveries
SET
  status = 'CANCELLED',
  locked_at = NULL,
  updated_at = now()
WHERE id = $1
`

func (q *Queries) CancelNotificationDelivery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, cancelNotificationDelivery, id)
	return err
}

const claimPendingNotificationDeliveries = `-- name: ClaimPendingNotificationDeliveries :many
WITH next_deliveries AS (
  SELECT nd.id
  FROM notification_deliveries nd
  WHERE
    nd.channel = $1
    AND nd.status IN ('PENDING', 'RETRY')
    AND (nd.scheduled_at IS NULL OR nd.scheduled_at <= now())
  ORDER BY nd.scheduled_at NULLS FIRST, nd.created_at ASC
  LIMIT $2
  FOR UPDATE SKIP LOCKED
)
UPDATE notification_deliveries nd
SET
  status = 'PROCESSING',
  locked_at = now(),
  updated_at = now()
FROM next_deliveries next
WHERE nd.id = next.id
RETURNING nd.id, nd.notification_id, nd.channel, nd.status, nd.recipient, nd.template_name, nd.template_data, nd.payload, nd.scheduled_at, nd.locked_at, nd.sent_at, nd.attempts, nd.max_attempts, nd.last_error, nd.created_at, nd.updated_at, nd.provider, nd.provider_message_id, nd.provider_status, nd.provider_response
`

type ClaimPendingNotificationDeliveriesParams struct {
	Channel string `json:"channel"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ClaimPendingNotificationDeliveries(ctx context.Context, arg ClaimPendingNotificationDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, claimPendingNotificationDeliveries, arg.Channel, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Status,
			&i.Recipient,
			&i.TemplateName,
			&i.TemplateData,
			&i.Payload,
			&i.ScheduledAt,
			&i.LockedAt,
			&i.SentAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Provider,
			&i.ProviderMessageID,
			&i.ProviderStatus,
			&i.ProviderResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNotificationDeliveries = `-- name: CountNotificationDeliveries :one
SELECT COUNT(*)::bigint
FROM notification_deliveries nd
WHERE
  (
    $1::text IS NULL
    OR nd.channel = $1::text
  )
  AND (
    $2::text IS NULL
    OR nd.status = $2::text
  )
  AND (
    $3::text IS NULL
    OR nd.id::text ILIKE '%' || $3::text || '%'
    OR nd.notification_id::text ILIKE '%' || $3::text || '%'
    OR nd.recipient::text ILIKE '%' || $3::text || '%'
    OR COALESCE(nd.provider_message_id, '') ILIKE '%' || $3::text || '%'
  )
`

type CountNotificationDeliveriesParams struct {
	FilterChannel sql.NullString `json:"filter_channel"`
	FilterStatus  sql.NullString `json:"filter_status"`
	FilterSearch  sql.NullString `json:"filter_search"`
}

func (q *Queries) CountNotificationDeliveries(ctx context.Context, arg CountNotificationDeliveriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationDeliveries, arg.FilterChannel, arg.FilterStatus, arg.FilterSearch)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPendingNotificationDeliveriesByChannel = `-- name: CountPendingNotificationDeliveriesByChannel :one
SELECT COUNT(*)::bigint
FROM notification_deliveries
WHERE
  channel = $1
  AND status IN ('PENDING', 'RETRY')
  AND (scheduled_at IS NULL OR scheduled_at <= now())
`

func (q *Queries) CountPendingNotificationDeliveriesByChannel(ctx context.Context, channel string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingNotificationDeliveriesByChannel, channel)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :one

INSERT INTO notification_deliveries (
  notification_id,
  channel,
  status,
  recipient,
  template_name,
  template_data,
  payload,
  scheduled_at,
  attempts,
  max_attempts
)
VALUES (
  $1,
  $2,
  COALESCE($8, 'PENDING'),
  $3,
  $4,
  $5,
  $6,
  $7,
  0,
  COALESCE($9, 5)
)
RETURNING id, notification_id, channel, status, recipient, template_name, template_data, payload, scheduled_at, locked_at, sent_at, attempts, max_attempts, last_error, created_at, updated_at, provider, provider_message_id, provider_status, provider_response
`

type CreateNotificationDeliveryParams struct {
	NotificationID      uuid.UUID             `json:"notification_id"`
	Channel             string                `json:"channel"`
	Recipient           pqtype.NullRawMessage `json:"recipient"`
	TemplateName        sql.NullString        `json:"template_name"`
	TemplateData        pqtype.NullRawMessage `json:"template_data"`
	Payload             pqtype.NullRawMessage `json:"payload"`
	ScheduledAt         sql.NullTime          `json:"scheduled_at"`
	DeliveryStatus      interface{}           `json:"delivery_status"`
	DeliveryMaxAttempts interface{}           `json:"delivery_max_attempts"`
}

// =====================================================
// Notification Deliveries
// =====================================================
func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRowContext(ctx, createNotificationDelivery,
		arg.NotificationID,
		arg.Channel,
		arg.Recipient,
		arg.TemplateName,
		arg.TemplateData,
		arg.Payload,
		arg.ScheduledAt,
		arg.DeliveryStatus,
		arg.DeliveryMaxAttempts,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Status,
		&i.Recipient,
		&i.TemplateName,
		&i.TemplateData,
		&i.Payload,
		&i.ScheduledAt,
		&i.LockedAt,
		&i.SentAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderMessageID,
		&i.ProviderStatus,
		&i.ProviderResponse,
	)
	return i, err
}

const getNotificationDeliveryByID = `-- name: GetNotificationDeliveryByID :one
SELECT id, notification_id, channel, status, recipient, template_name, template_data, payload, scheduled_at, locked_at, sent_at, attempts, max_attempts, last_error, created_at, updated_at, provider, provider_message_id, provider_status, provider_response
FROM notification_deliveries
WHERE id = $1
`

func (q *Queries) GetNotificationDeliveryByID(ctx context.Context, id uuid.UUID) (NotificationDelivery, error) {
	row := q.db.QueryRowContext(ctx, getNotificationDeliveryByID, id)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.NotificationID,
		&i.Channel,
		&i.Status,
		&i.Recipient,
		&i.TemplateName,
		&i.TemplateData,
		&i.Payload,
		&i.ScheduledAt,
		&i.LockedAt,
		&i.SentAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderMessageID,
		&i.ProviderStatus,
		&i.ProviderResponse,
	)
	return i, err
}

const listNotificationDeliveries = `-- name: ListNotificationDeliveries :many
SELECT nd.id, nd.notification_id, nd.channel, nd.status, nd.recipient, nd.template_name, nd.template_data, nd.payload, nd.scheduled_at, nd.locked_at, nd.sent_at, nd.attempts, nd.max_attempts, nd.last_error, nd.created_at, nd.updated_at, nd.provider, nd.provider_message_id, nd.provider_status, nd.provider_response
FROM notification_deliveries nd
WHERE
  (
    $3::text IS NULL
    OR nd.channel = $3::text
  )
  AND (
    $4::text IS NULL
    OR nd.status = $4::text
  )
  AND (
    $5::text IS NULL
    OR nd.id::text ILIKE '%' || $5::text || '%'
    OR nd.notification_id::text ILIKE '%' || $5::text || '%'
    OR nd.recipient::text ILIKE '%' || $5::text || '%'
    OR COALESCE(nd.provider_message_id, '') ILIKE '%' || $5::text || '%'
  )
ORDER BY nd.created_at DESC
LIMIT $1 OFFSET $2
`

type ListNotificationDeliveriesParams struct {
	Limit         int32          `json:"limit"`
	Offset        int32          `json:"offset"`
	FilterChannel sql.NullString `json:"filter_channel"`
	FilterStatus  sql.NullString `json:"filter_status"`
	FilterSearch  sql.NullString `json:"filter_search"`
}

func (q *Queries) ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationDeliveries,
		arg.Limit,
		arg.Offset,
		arg.FilterChannel,
		arg.FilterStatus,
		arg.FilterSearch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Status,
			&i.Recipient,
			&i.TemplateName,
			&i.TemplateData,
			&i.Payload,
			&i.ScheduledAt,
			&i.LockedAt,
			&i.SentAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Provider,
			&i.ProviderMessageID,
			&i.ProviderStatus,
			&i.ProviderResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDeliveriesByNotificationID = `-- name: ListNotificationDeliveriesByNotificationID :many
SELECT id, notification_id, channel, status, recipient, template_name, template_data, payload, scheduled_at, locked_at, sent_at, attempts, max_attempts, last_error, created_at, updated_at, provider, provider_message_id, provider_status, provider_response
FROM notification_deliveries
WHERE notification_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListNotificationDeliveriesByNotificationID(ctx context.Context, notificationID uuid.UUID) ([]NotificationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationDeliveriesByNotificationID, notificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Status,
			&i.Recipient,
			&i.TemplateName,
			&i.TemplateData,
			&i.Payload,
			&i.ScheduledAt,
			&i.LockedAt,
			&i.SentAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Provider,
			&i.ProviderMessageID,
			&i.ProviderStatus,
			&i.ProviderResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDeliveryMetrics = `-- name: ListNotificationDeliveryMetrics :many
SELECT
  nd.channel,
  COALESCE(nd.provider, '')::text AS provider,
  COUNT(*)::bigint AS total,
  COUNT(*) FILTER (WHERE nd.status = 'PENDING')::bigint AS pending,
  COUNT(*) FILTER (WHERE nd.status = 'PROCESSING')::bigint AS processing,
  COUNT(*) FILTER (WHERE nd.status = 'SENT')::bigint AS sent,
  COUNT(*) FILTER (WHERE nd.status = 'FAILED')::bigint AS failed,
  COUNT(*) FILTER (WHERE nd.status = 'RETRY')::bigint AS retry,
  COUNT(*) FILTER (WHERE nd.status = 'CANCELLED')::bigint AS cancelled,
  COALESCE(
    AVG(EXTRACT(EPOCH FROM (nd.sent_at - nd.created_at)))
      FILTER (WHERE nd.sent_at IS NOT NULL),
    0
  )::double precision AS avg_processing_seconds
FROM notification_deliveries nd
GROUP BY nd.channel, COALESCE(nd.provider, '')
ORDER BY nd.channel ASC, provider ASC
`

type ListNotificationDeliveryMetricsRow struct {
	Channel              string  `json:"channel"`
	Provider             string  `json:"provider"`
	Total                int64   `json:"total"`
	Pending              int64   `json:"pending"`
	Processing           int64   `json:"processing"`
	Sent                 int64   `json:"sent"`
	Failed               int64   `json:"failed"`
	Retry                int64   `json:"retry"`
	Cancelled            int64   `json:"cancelled"`
	AvgProcessingSeconds float64 `json:"avg_processing_seconds"`
}

func (q *Queries) ListNotificationDeliveryMetrics(ctx context.Context) ([]ListNotificationDeliveryMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationDeliveryMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationDeliveryMetricsRow{}
	for rows.Next() {
		var i ListNotificationDeliveryMetricsRow
		if err := rows.Scan(
			&i.Channel,
			&i.Provider,
			&i.Total,
			&i.Pending,
			&i.Processing,
			&i.Sent,
			&i.Failed,
			&i.Retry,
			&i.Cancelled,
			&i.AvgProcessingSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationDeliveryFailed = `-- name: MarkNotificationDeliveryFailed :exec
UPDATE notification_deliveries
SET
  status = 'FAILED',
  attempts = attempts + 1,
  locked_at = NULL,
  last_error = $2,
  updated_at = now()
WHERE id = $1
`

type MarkNotificationDeliveryFailedParams struct {
	ID        uuid.UUID      `json:"id"`
	LastError sql.NullString `json:"last_error"`
}

func (q *Queries) MarkNotificationDeliveryFailed(ctx context.Context, arg MarkNotificationDeliveryFailedParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationDeliveryFailed, arg.ID, arg.LastError)
	return err
}

const markNotificationDeliveryRetry = `-- name: MarkNotificationDeliveryRetry :exec
UPDATE notification_deliveries
SET
  status = 'RETRY',
  attempts = attempts + 1,
  locked_at = NULL,
  last_error = $2,
  scheduled_at = now() + ($3::text)::interval,
  updated_at = now()
WHERE id = $1
`

type MarkNotificationDeliveryRetryParams struct {
	ID        uuid.UUID      `json:"id"`
	LastError sql.NullString `json:"last_error"`
	Column3   string         `json:"column_3"`
}

func (q *Queries) MarkNotificationDeliveryRetry(ctx context.Context, arg MarkNotificationDeliveryRetryParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationDeliveryRetry, arg.ID, arg.LastError, arg.Column3)
	return err
}

const markNotificationDeliverySent = `-- name: MarkNotificationDeliverySent :exec
UPDATE notification_deliveries
SET
  status = 'SENT',
  sent_at = now(),
  locked_at = NULL,
  last_error = NULL,
  updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkNotificationDeliverySent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markNotificationDeliverySent, id)
	return err
}
