// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_preferences.sql

package db

import (
	"context"
	"database/sql"
)

const getNotificationPreferencesByUserID = `-- name: GetNotificationPreferencesByUserID :one
SELECT id, user_id, email_enabled, sms_enabled, phone_number, phone_verified, quiet_hours_start, quiet_hours_end, created_at, updated_at
FROM notification_preferences
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetNotificationPreferencesByUserID(ctx context.Context, userID string) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, getNotificationPreferencesByUserID, userID)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailEnabled,
		&i.SmsEnabled,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationPreferencesForSMS = `-- name: ListNotificationPreferencesForSMS :many
SELECT id, user_id, email_enabled, sms_enabled, phone_number, phone_verified, quiet_hours_start, quiet_hours_end, created_at, updated_at
FROM notification_preferences
WHERE sms_enabled = TRUE
    AND phone_number IS NOT NULL
    AND trim(phone_number) <> ''
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListNotificationPreferencesForSMSParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNotificationPreferencesForSMS(ctx context.Context, arg ListNotificationPreferencesForSMSParams) ([]NotificationPreference, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationPreferencesForSMS, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EmailEnabled,
			&i.SmsEnabled,
			&i.PhoneNumber,
			&i.PhoneVerified,
			&i.QuietHoursStart,
			&i.QuietHoursEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (
    user_id,
    email_enabled,
    sms_enabled,
    phone_number,
    phone_verified,
    quiet_hours_start,
    quiet_hours_end
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (user_id) DO UPDATE SET
    email_enabled = EXCLUDED.email_enabled,
    sms_enabled = EXCLUDED.sms_enabled,
    phone_number = EXCLUDED.phone_number,
    phone_verified = CASE
        WHEN COALESCE(notification_preferences.phone_number, '') IS DISTINCT FROM COALESCE(EXCLUDED.phone_number, '')
        THEN FALSE
        ELSE notification_preferences.phone_verified
    END,
    quiet_hours_start = EXCLUDED.quiet_hours_start,
    quiet_hours_end = EXCLUDED.quiet_hours_end,
    updated_at = now()
RETURNING id, user_id, email_enabled, sms_enabled, phone_number, phone_verified, quiet_hours_start, quiet_hours_end, created_at, updated_at
`

type UpsertNotificationPreferencesParams struct {
	UserID          string         `json:"user_id"`
	EmailEnabled    bool           `json:"email_enabled"`
	SmsEnabled      bool           `json:"sms_enabled"`
	PhoneNumber     sql.NullString `json:"phone_number"`
	PhoneVerified   bool           `json:"phone_verified"`
	QuietHoursStart sql.NullString `json:"quiet_hours_start"`
	QuietHoursEnd   sql.NullString `json:"quiet_hours_end"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, upsertNotificationPreferences,
		arg.UserID,
		arg.EmailEnabled,
		arg.SmsEnabled,
		arg.PhoneNumber,
		arg.PhoneVerified,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailEnabled,
		&i.SmsEnabled,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
