// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processes.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cancelProcess = `-- name: CancelProcess :exec
UPDATE processes
SET status = 'CANCELLED',
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelProcess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, cancelProcess, id)
	return err
}

const claimNextPendingProcess = `-- name: ClaimNextPendingProcess :one
UPDATE processes
SET status = 'PROCESSING',
    started_at = NOW(),
    attempts = attempts + 1,
    updated_at = NOW()
WHERE id = (
    SELECT id
    FROM processes
    WHERE status = 'PENDING'
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, document_id, process_type, status, progress, message, error, attempts, created_by, started_at, finished_at, created_at, updated_at
`

func (q *Queries) ClaimNextPendingProcess(ctx context.Context) (Process, error) {
	row := q.db.QueryRowContext(ctx, claimNextPendingProcess)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ProcessType,
		&i.Status,
		&i.Progress,
		&i.Message,
		&i.Error,
		&i.Attempts,
		&i.CreatedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeProcess = `-- name: CompleteProcess :exec
UPDATE processes
SET status = 'COMPLETED',
    progress = 100,
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteProcess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, completeProcess, id)
	return err
}

const createProcess = `-- name: CreateProcess :one
INSERT INTO processes (
    id,
    document_id,
    process_type,
    created_by
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, document_id, process_type, status, progress, message, error, attempts, created_by, started_at, finished_at, created_at, updated_at
`

type CreateProcessParams struct {
	ID          uuid.UUID `json:"id"`
	DocumentID  uuid.UUID `json:"document_id"`
	ProcessType string    `json:"process_type"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProcess(ctx context.Context, arg CreateProcessParams) (Process, error) {
	row := q.db.QueryRowContext(ctx, createProcess,
		arg.ID,
		arg.DocumentID,
		arg.ProcessType,
		arg.CreatedBy,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ProcessType,
		&i.Status,
		&i.Progress,
		&i.Message,
		&i.Error,
		&i.Attempts,
		&i.CreatedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failProcess = `-- name: FailProcess :exec
UPDATE processes
SET status = 'FAILED',
    error = $2,
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type FailProcessParams struct {
	ID    uuid.UUID      `json:"id"`
	Error sql.NullString `json:"error"`
}

func (q *Queries) FailProcess(ctx context.Context, arg FailProcessParams) error {
	_, err := q.db.ExecContext(ctx, failProcess, arg.ID, arg.Error)
	return err
}

const getProcessByID = `-- name: GetProcessByID :one
SELECT id, document_id, process_type, status, progress, message, error, attempts, created_by, started_at, finished_at, created_at, updated_at
FROM processes
WHERE id = $1
`

func (q *Queries) GetProcessByID(ctx context.Context, id uuid.UUID) (Process, error) {
	row := q.db.QueryRowContext(ctx, getProcessByID, id)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ProcessType,
		&i.Status,
		&i.Progress,
		&i.Message,
		&i.Error,
		&i.Attempts,
		&i.CreatedBy,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProcesses = `-- name: ListProcesses :many
SELECT id, document_id, process_type, status, progress, message, error, attempts, created_by, started_at, finished_at, created_at, updated_at
FROM processes
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProcessesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProcesses(ctx context.Context, arg ListProcessesParams) ([]Process, error) {
	rows, err := q.db.QueryContext(ctx, listProcesses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ProcessType,
			&i.Status,
			&i.Progress,
			&i.Message,
			&i.Error,
			&i.Attempts,
			&i.CreatedBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessesByDocument = `-- name: ListProcessesByDocument :many



SELECT id, document_id, process_type, status, progress, message, error, attempts, created_by, started_at, finished_at, created_at, updated_at
FROM processes
WHERE document_id = $1
ORDER BY created_at DESC
`

// -- name: InsertProcessEvent :one
// INSERT INTO process_events (
//
//	id,
//	process_id,
//	status,
//	message
//
// ) VALUES (
//
//	$1, $2, $3, $4
//
// )
// RETURNING *;
// -- name: ListProcessEvents :many
// SELECT *
// FROM process_events
// WHERE process_id = $1
// ORDER BY created_at ASC;
func (q *Queries) ListProcessesByDocument(ctx context.Context, documentID uuid.UUID) ([]Process, error) {
	rows, err := q.db.QueryContext(ctx, listProcessesByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ProcessType,
			&i.Status,
			&i.Progress,
			&i.Message,
			&i.Error,
			&i.Attempts,
			&i.CreatedBy,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcessProgress = `-- name: UpdateProcessProgress :exec
UPDATE processes
SET progress = $2,
    message = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateProcessProgressParams struct {
	ID       uuid.UUID      `json:"id"`
	Progress int32          `json:"progress"`
	Message  sql.NullString `json:"message"`
}

func (q *Queries) UpdateProcessProgress(ctx context.Context, arg UpdateProcessProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateProcessProgress, arg.ID, arg.Progress, arg.Message)
	return err
}
