// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	ActiveUsersPerClientThisWeek(ctx context.Context) ([]ActiveUsersPerClientThisWeekRow, error)
	ActiveUsersPerClientToday(ctx context.Context) ([]ActiveUsersPerClientTodayRow, error)
	ActiveUsersThisWeek(ctx context.Context) (int64, error)
	ActiveUsersToday(ctx context.Context) (int64, error)
	ApproximateActiveSessions(ctx context.Context) (int64, error)
	ArchiveAnnouncement(ctx context.Context, arg ArchiveAnnouncementParams) (Announcement, error)
	AuditMetricsOverview(ctx context.Context, arg AuditMetricsOverviewParams) (AuditMetricsOverviewRow, error)
	CancelProcess(ctx context.Context, id uuid.UUID) error
	ClaimNextPendingProcess(ctx context.Context) (Process, error)
	ClientUsageForUserInRange(ctx context.Context, arg ClientUsageForUserInRangeParams) ([]ClientUsageForUserInRangeRow, error)
	CompleteProcess(ctx context.Context, id uuid.UUID) error
	CountActivePublishedAnnouncements(ctx context.Context) (int64, error)
	CountActiveUsers(ctx context.Context) (int64, error)
	CountActiveUsersInRange(ctx context.Context, arg CountActiveUsersInRangeParams) (int64, error)
	CountAnnouncementsAdmin(ctx context.Context) (int64, error)
	CountAnnouncementsByStatus(ctx context.Context, status interface{}) (int64, error)
	CountAnnouncementsCreatedByUser(ctx context.Context, createdBy uuid.UUID) (int64, error)
	CountClients(ctx context.Context) (int64, error)
	CountDisabledClients(ctx context.Context) (int64, error)
	CountDisabledUsers(ctx context.Context) (int64, error)
	CountEnabledClients(ctx context.Context) (int64, error)
	CountFailedLogins(ctx context.Context) (int64, error)
	CountFailedLoginsInRange(ctx context.Context, arg CountFailedLoginsInRangeParams) (int64, error)
	CountNewClientsThisWeek(ctx context.Context) (int64, error)
	CountNewClientsToday(ctx context.Context) (int64, error)
	CountNewUsersThisWeek(ctx context.Context) (int64, error)
	CountNewUsersToday(ctx context.Context) (int64, error)
	CountNotifications(ctx context.Context, targetRole string) (int64, error)
	CountPasswordResetsInRange(ctx context.Context, arg CountPasswordResetsInRangeParams) (int64, error)
	CountSearchAnnouncementsAdmin(ctx context.Context, searchText sql.NullString) (int64, error)
	CountUnreadNotifications(ctx context.Context, targetRole string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error)
	// =====================================================
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	// =====================================================
	// Clients
	// =====================================================
	CreateClient(ctx context.Context, arg CreateClientParams) error
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	// =====================================================
	// Import Jobs
	// =====================================================
	CreateImportJob(ctx context.Context, arg CreateImportJobParams) error
	// =====================================================
	// Notifications
	// =====================================================
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateProcess(ctx context.Context, arg CreateProcessParams) (Process, error)
	CreateStorageLocation(ctx context.Context, arg CreateStorageLocationParams) (StorageLocation, error)
	// =====================================================
	// Users
	// =====================================================
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAnnouncementClients(ctx context.Context, announcementID uuid.UUID) error
	DeleteAnnouncementRoles(ctx context.Context, announcementID uuid.UUID) error
	DeleteAnnouncementUsers(ctx context.Context, announcementID uuid.UUID) error
	DeleteClient(ctx context.Context, id uuid.UUID) error
	DeleteDocument(ctx context.Context, id uuid.UUID) error
	DeleteNotificationByID(ctx context.Context, id uuid.UUID) error
	DeleteOldNotifications(ctx context.Context) error
	DeleteStorageLocation(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	ExportAuditLogs(ctx context.Context, arg ExportAuditLogsParams) ([]ExportAuditLogsRow, error)
	FailProcess(ctx context.Context, arg FailProcessParams) error
	FailedLoginsByDay(ctx context.Context, arg FailedLoginsByDayParams) ([]FailedLoginsByDayRow, error)
	FailedLoginsByUserInRange(ctx context.Context, arg FailedLoginsByUserInRangeParams) ([]FailedLoginsByUserInRangeRow, error)
	FirstLoginForUser(ctx context.Context, userID uuid.UUID) (sql.NullTime, error)
	GetAnnouncementByID(ctx context.Context, id uuid.UUID) (Announcement, error)
	GetAnnouncementByIDForUpdate(ctx context.Context, id uuid.UUID) (Announcement, error)
	GetAnnouncementStats(ctx context.Context) (GetAnnouncementStatsRow, error)
	GetAuditLog(ctx context.Context, id uuid.UUID) (GetAuditLogRow, error)
	GetClientByClientID(ctx context.Context, clientID string) (Client, error)
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
	GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error)
	GetImportJob(ctx context.Context, id uuid.UUID) (ImportJob, error)
	GetLatestProcessByDocumentID(ctx context.Context, documentID uuid.UUID) (Process, error)
	GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error)
	GetProcessByID(ctx context.Context, id uuid.UUID) (Process, error)
	GetStorageLocationByCode(ctx context.Context, code string) (StorageLocation, error)
	GetStorageLocationByID(ctx context.Context, id uuid.UUID) (StorageLocation, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsersByRole(ctx context.Context, roles []string) ([]User, error)
	InactiveUsersSince(ctx context.Context) ([]User, error)
	InsertAnnouncementClient(ctx context.Context, arg InsertAnnouncementClientParams) error
	InsertAnnouncementRole(ctx context.Context, arg InsertAnnouncementRoleParams) error
	InsertAnnouncementUser(ctx context.Context, arg InsertAnnouncementUserParams) error
	InsertImportJobItem(ctx context.Context, arg InsertImportJobItemParams) error
	LastLoginForAllUsers(ctx context.Context) ([]LastLoginForAllUsersRow, error)
	LastLoginForUser(ctx context.Context, userID uuid.UUID) (sql.NullTime, error)
	ListActivePublishedAnnouncements(ctx context.Context, arg ListActivePublishedAnnouncementsParams) ([]Announcement, error)
	ListActiveStorageLocations(ctx context.Context) ([]StorageLocation, error)
	ListAnnouncementClients(ctx context.Context, announcementID uuid.UUID) ([]uuid.UUID, error)
	ListAnnouncementRoles(ctx context.Context, announcementID uuid.UUID) ([]string, error)
	ListAnnouncementUsers(ctx context.Context, announcementID uuid.UUID) ([]uuid.UUID, error)
	ListAnnouncementsAdmin(ctx context.Context, arg ListAnnouncementsAdminParams) ([]Announcement, error)
	ListAnnouncementsByStatus(ctx context.Context, arg ListAnnouncementsByStatusParams) ([]Announcement, error)
	ListAnnouncementsCreatedByUser(ctx context.Context, arg ListAnnouncementsCreatedByUserParams) ([]Announcement, error)
	ListAnnouncementsForClient(ctx context.Context, arg ListAnnouncementsForClientParams) ([]Announcement, error)
	ListAnnouncementsForRole(ctx context.Context, arg ListAnnouncementsForRoleParams) ([]Announcement, error)
	ListAnnouncementsForUser(ctx context.Context, arg ListAnnouncementsForUserParams) ([]Announcement, error)
	ListAuditActions(ctx context.Context) ([]string, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListClientsPaged(ctx context.Context, arg ListClientsPagedParams) ([]Client, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error)
	ListDocumentsByUser(ctx context.Context, arg ListDocumentsByUserParams) ([]Document, error)
	ListEnabledClients(ctx context.Context) ([]Client, error)
	ListImportJobFailedItems(ctx context.Context, jobID uuid.UUID) ([]ImportJobItem, error)
	ListImportJobItems(ctx context.Context, jobID uuid.UUID) ([]ImportJobItem, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListNotificationsByCursor(ctx context.Context, arg ListNotificationsByCursorParams) ([]Notification, error)
	ListProcesses(ctx context.Context, arg ListProcessesParams) ([]Process, error)
	// -- name: InsertProcessEvent :one
	// INSERT INTO process_events (
	//     id,
	//     process_id,
	//     status,
	//     message
	// ) VALUES (
	//     $1, $2, $3, $4
	// )
	// RETURNING *;
	// -- name: ListProcessEvents :many
	// SELECT *
	// FROM process_events
	// WHERE process_id = $1
	// ORDER BY created_at ASC;
	ListProcessesByDocument(ctx context.Context, documentID uuid.UUID) ([]Process, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersPaged(ctx context.Context, arg ListUsersPagedParams) ([]User, error)
	LoginCountForClientInRange(ctx context.Context, arg LoginCountForClientInRangeParams) (int64, error)
	LoginCountPerUserInRange(ctx context.Context, arg LoginCountPerUserInRangeParams) ([]LoginCountPerUserInRangeRow, error)
	LoginSuccessFailureInRange(ctx context.Context, arg LoginSuccessFailureInRangeParams) (LoginSuccessFailureInRangeRow, error)
	LoginTrend(ctx context.Context) ([]LoginTrendRow, error)
	LoginTrendByDay(ctx context.Context, arg LoginTrendByDayParams) ([]LoginTrendByDayRow, error)
	MarkAllNotificationsRead(ctx context.Context, targetRole string) error
	MarkNotificationRead(ctx context.Context, id uuid.UUID) error
	MostAccessedClients(ctx context.Context, arg MostAccessedClientsParams) ([]MostAccessedClientsRow, error)
	MostActiveClients(ctx context.Context) ([]MostActiveClientsRow, error)
	NeverLoggedInUsers(ctx context.Context) ([]User, error)
	NewClientsInRange(ctx context.Context, arg NewClientsInRangeParams) ([]NewClientsInRangeRow, error)
	NewUsersInRange(ctx context.Context, arg NewUsersInRangeParams) ([]User, error)
	NewUsersTrend(ctx context.Context, arg NewUsersTrendParams) ([]NewUsersTrendRow, error)
	PublishAnnouncementNow(ctx context.Context, arg PublishAnnouncementNowParams) (Announcement, error)
	RecentlyCreatedClients(ctx context.Context, rowLimit int32) ([]RecentlyCreatedClientsRow, error)
	RestoreAnnouncement(ctx context.Context, arg RestoreAnnouncementParams) (Announcement, error)
	RoleDistribution(ctx context.Context) ([]RoleDistributionRow, error)
	ScheduleAnnouncement(ctx context.Context, arg ScheduleAnnouncementParams) (Announcement, error)
	SearchAnnouncementsAdmin(ctx context.Context, arg SearchAnnouncementsAdminParams) ([]Announcement, error)
	SearchClients(ctx context.Context, query sql.NullString) ([]Client, error)
	SearchUsers(ctx context.Context, dollar_1 sql.NullString) ([]User, error)
	SetAnnouncementPinned(ctx context.Context, arg SetAnnouncementPinnedParams) (Announcement, error)
	SetAnnouncementPriority(ctx context.Context, arg SetAnnouncementPriorityParams) (Announcement, error)
	SoftDeleteAnnouncement(ctx context.Context, arg SoftDeleteAnnouncementParams) error
	SuspiciousLoginsInRange(ctx context.Context, arg SuspiciousLoginsInRangeParams) ([]SuspiciousLoginsInRangeRow, error)
	TopFailureIPs(ctx context.Context, arg TopFailureIPsParams) ([]TopFailureIPsRow, error)
	TopTenantsByLogins(ctx context.Context, arg TopTenantsByLoginsParams) ([]TopTenantsByLoginsRow, error)
	TotalLoginsInRange(ctx context.Context, arg TotalLoginsInRangeParams) (int64, error)
	UnarchiveAnnouncementToDraft(ctx context.Context, arg UnarchiveAnnouncementToDraftParams) (Announcement, error)
	UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error)
	UpdateAnnouncementStatus(ctx context.Context, arg UpdateAnnouncementStatusParams) (Announcement, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) error
	UpdateClientEnabled(ctx context.Context, arg UpdateClientEnabledParams) error
	UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error)
	UpdateImportJobCounts(ctx context.Context, arg UpdateImportJobCountsParams) error
	UpdateImportJobItemStatus(ctx context.Context, arg UpdateImportJobItemStatusParams) error
	UpdateImportJobStatus(ctx context.Context, arg UpdateImportJobStatusParams) error
	UpdateProcessProgress(ctx context.Context, arg UpdateProcessProgressParams) error
	UpdateStorageLocation(ctx context.Context, arg UpdateStorageLocationParams) (StorageLocation, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserEnabled(ctx context.Context, arg UpdateUserEnabledParams) error
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpsertClient(ctx context.Context, arg UpsertClientParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
	UserAgentStatsInRange(ctx context.Context, arg UserAgentStatsInRangeParams) ([]UserAgentStatsInRangeRow, error)
	UserExists(ctx context.Context, id uuid.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
