// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: region_weekly_status.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRegionWeeklyDiseaseStatus = `-- name: CreateRegionWeeklyDiseaseStatus :one
INSERT INTO region_weekly_status (
  region_id,
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  $1, $2, NULL, $3, $4, $5
)
RETURNING id, region_id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type CreateRegionWeeklyDiseaseStatusParams struct {
	RegionID   uuid.UUID      `json:"region_id"`
	DiseaseID  uuid.UUID      `json:"disease_id"`
	EpiWeekID  uuid.UUID      `json:"epi_week_id"`
	Status     interface{}    `json:"status"`
	SourceName sql.NullString `json:"source_name"`
}

func (q *Queries) CreateRegionWeeklyDiseaseStatus(ctx context.Context, arg CreateRegionWeeklyDiseaseStatusParams) (RegionWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, createRegionWeeklyDiseaseStatus,
		arg.RegionID,
		arg.DiseaseID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i RegionWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRegionWeeklyIndicatorStatus = `-- name: CreateRegionWeeklyIndicatorStatus :one
INSERT INTO region_weekly_status (
  region_id,
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  $1, NULL, $2, $3, $4, $5
)
RETURNING id, region_id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type CreateRegionWeeklyIndicatorStatusParams struct {
	RegionID    uuid.UUID      `json:"region_id"`
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
}

func (q *Queries) CreateRegionWeeklyIndicatorStatus(ctx context.Context, arg CreateRegionWeeklyIndicatorStatusParams) (RegionWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, createRegionWeeklyIndicatorStatus,
		arg.RegionID,
		arg.IndicatorID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i RegionWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRegionStatusesByWeek = `-- name: DeleteRegionStatusesByWeek :exec
DELETE FROM region_weekly_status
WHERE epi_week_id = $1
`

func (q *Queries) DeleteRegionStatusesByWeek(ctx context.Context, epiWeekID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRegionStatusesByWeek, epiWeekID)
	return err
}

const listRegionWeeklyDiseaseStatusesByWeek = `-- name: ListRegionWeeklyDiseaseStatusesByWeek :many
SELECT
  s.id, s.region_id, s.disease_id, s.indicator_id, s.epi_week_id, s.status, s.source_name, s.imported_at, s.created_at,
  r.name AS region_name,
  d.name AS disease_name
FROM region_weekly_status s
JOIN regions r ON r.id = s.region_id
JOIN diseases d ON d.id = s.disease_id
WHERE s.epi_week_id = $1
  AND s.disease_id IS NOT NULL
ORDER BY r.name ASC, d.name ASC
`

type ListRegionWeeklyDiseaseStatusesByWeekRow struct {
	ID          uuid.UUID      `json:"id"`
	RegionID    uuid.UUID      `json:"region_id"`
	DiseaseID   uuid.UUID      `json:"disease_id"`
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
	ImportedAt  time.Time      `json:"imported_at"`
	CreatedAt   time.Time      `json:"created_at"`
	RegionName  string         `json:"region_name"`
	DiseaseName string         `json:"disease_name"`
}

func (q *Queries) ListRegionWeeklyDiseaseStatusesByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListRegionWeeklyDiseaseStatusesByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listRegionWeeklyDiseaseStatusesByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegionWeeklyDiseaseStatusesByWeekRow{}
	for rows.Next() {
		var i ListRegionWeeklyDiseaseStatusesByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.DiseaseID,
			&i.IndicatorID,
			&i.EpiWeekID,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.RegionName,
			&i.DiseaseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegionWeeklyIndicatorStatusesByWeek = `-- name: ListRegionWeeklyIndicatorStatusesByWeek :many
SELECT
  s.id, s.region_id, s.disease_id, s.indicator_id, s.epi_week_id, s.status, s.source_name, s.imported_at, s.created_at,
  r.name AS region_name,
  i.name AS indicator_name
FROM region_weekly_status s
JOIN regions r ON r.id = s.region_id
JOIN indicators i ON i.id = s.indicator_id
WHERE s.epi_week_id = $1
  AND s.indicator_id IS NOT NULL
ORDER BY r.name ASC, i.name ASC
`

type ListRegionWeeklyIndicatorStatusesByWeekRow struct {
	ID            uuid.UUID      `json:"id"`
	RegionID      uuid.UUID      `json:"region_id"`
	DiseaseID     uuid.UUID      `json:"disease_id"`
	IndicatorID   uuid.UUID      `json:"indicator_id"`
	EpiWeekID     uuid.UUID      `json:"epi_week_id"`
	Status        interface{}    `json:"status"`
	SourceName    sql.NullString `json:"source_name"`
	ImportedAt    time.Time      `json:"imported_at"`
	CreatedAt     time.Time      `json:"created_at"`
	RegionName    string         `json:"region_name"`
	IndicatorName string         `json:"indicator_name"`
}

func (q *Queries) ListRegionWeeklyIndicatorStatusesByWeek(ctx context.Context, epiWeekID uuid.UUID) ([]ListRegionWeeklyIndicatorStatusesByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listRegionWeeklyIndicatorStatusesByWeek, epiWeekID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRegionWeeklyIndicatorStatusesByWeekRow{}
	for rows.Next() {
		var i ListRegionWeeklyIndicatorStatusesByWeekRow
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.DiseaseID,
			&i.IndicatorID,
			&i.EpiWeekID,
			&i.Status,
			&i.SourceName,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.RegionName,
			&i.IndicatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRegionWeeklyDiseaseStatus = `-- name: UpsertRegionWeeklyDiseaseStatus :one
INSERT INTO region_weekly_status (
  region_id,
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  $1, $2, NULL, $3, $4, $5
)
ON CONFLICT (region_id, disease_id, epi_week_id)
WHERE disease_id IS NOT NULL
DO UPDATE SET
  status = EXCLUDED.status,
  source_name = COALESCE(EXCLUDED.source_name, region_weekly_status.source_name),
  imported_at = now()
RETURNING id, region_id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type UpsertRegionWeeklyDiseaseStatusParams struct {
	RegionID   uuid.UUID      `json:"region_id"`
	DiseaseID  uuid.UUID      `json:"disease_id"`
	EpiWeekID  uuid.UUID      `json:"epi_week_id"`
	Status     interface{}    `json:"status"`
	SourceName sql.NullString `json:"source_name"`
}

func (q *Queries) UpsertRegionWeeklyDiseaseStatus(ctx context.Context, arg UpsertRegionWeeklyDiseaseStatusParams) (RegionWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertRegionWeeklyDiseaseStatus,
		arg.RegionID,
		arg.DiseaseID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i RegionWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRegionWeeklyIndicatorStatus = `-- name: UpsertRegionWeeklyIndicatorStatus :one
INSERT INTO region_weekly_status (
  region_id,
  disease_id,
  indicator_id,
  epi_week_id,
  status,
  source_name
) VALUES (
  $1, NULL, $2, $3, $4, $5
)
ON CONFLICT (region_id, indicator_id, epi_week_id)
WHERE indicator_id IS NOT NULL
DO UPDATE SET
  status = EXCLUDED.status,
  source_name = COALESCE(EXCLUDED.source_name, region_weekly_status.source_name),
  imported_at = now()
RETURNING id, region_id, disease_id, indicator_id, epi_week_id, status, source_name, imported_at, created_at
`

type UpsertRegionWeeklyIndicatorStatusParams struct {
	RegionID    uuid.UUID      `json:"region_id"`
	IndicatorID uuid.UUID      `json:"indicator_id"`
	EpiWeekID   uuid.UUID      `json:"epi_week_id"`
	Status      interface{}    `json:"status"`
	SourceName  sql.NullString `json:"source_name"`
}

func (q *Queries) UpsertRegionWeeklyIndicatorStatus(ctx context.Context, arg UpsertRegionWeeklyIndicatorStatusParams) (RegionWeeklyStatus, error) {
	row := q.db.QueryRowContext(ctx, upsertRegionWeeklyIndicatorStatus,
		arg.RegionID,
		arg.IndicatorID,
		arg.EpiWeekID,
		arg.Status,
		arg.SourceName,
	)
	var i RegionWeeklyStatus
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.DiseaseID,
		&i.IndicatorID,
		&i.EpiWeekID,
		&i.Status,
		&i.SourceName,
		&i.ImportedAt,
		&i.CreatedAt,
	)
	return i, err
}
