// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: regions.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRegion = `-- name: CreateRegion :one
INSERT INTO regions (
  name,
  code
) VALUES (
  $1,
  $2
)
RETURNING id, name, code, created_at, updated_at
`

type CreateRegionParams struct {
	Name string         `json:"name"`
	Code sql.NullString `json:"code"`
}

func (q *Queries) CreateRegion(ctx context.Context, arg CreateRegionParams) (Region, error) {
	row := q.db.QueryRowContext(ctx, createRegion, arg.Name, arg.Code)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRegion = `-- name: DeleteRegion :exec
DELETE FROM regions
WHERE id = $1
`

func (q *Queries) DeleteRegion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRegion, id)
	return err
}

const getRegionByID = `-- name: GetRegionByID :one
SELECT id, name, code, created_at, updated_at
FROM regions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRegionByID(ctx context.Context, id uuid.UUID) (Region, error) {
	row := q.db.QueryRowContext(ctx, getRegionByID, id)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegionByName = `-- name: GetRegionByName :one
SELECT id, name, code, created_at, updated_at
FROM regions
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetRegionByName(ctx context.Context, lower string) (Region, error) {
	row := q.db.QueryRowContext(ctx, getRegionByName, lower)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegions = `-- name: ListRegions :many
SELECT id, name, code, created_at, updated_at
FROM regions
ORDER BY name ASC
`

func (q *Queries) ListRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.QueryContext(ctx, listRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Region{}
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRegion = `-- name: UpsertRegion :one
INSERT INTO regions (
  name,
  code
) VALUES (
  $1,
  $2
)
ON CONFLICT (name)
DO UPDATE SET
  code = COALESCE(EXCLUDED.code, regions.code),
  updated_at = now()
RETURNING id, name, code, created_at, updated_at
`

type UpsertRegionParams struct {
	Name string         `json:"name"`
	Code sql.NullString `json:"code"`
}

func (q *Queries) UpsertRegion(ctx context.Context, arg UpsertRegionParams) (Region, error) {
	row := q.db.QueryRowContext(ctx, upsertRegion, arg.Name, arg.Code)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
