// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sub_counties.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSubCounty = `-- name: CreateSubCounty :one
INSERT INTO sub_counties (
  name,
  district_id,
  code
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id, name, district_id, code, created_at, updated_at
`

type CreateSubCountyParams struct {
	Name       string         `json:"name"`
	DistrictID uuid.UUID      `json:"district_id"`
	Code       sql.NullString `json:"code"`
}

func (q *Queries) CreateSubCounty(ctx context.Context, arg CreateSubCountyParams) (SubCounty, error) {
	row := q.db.QueryRowContext(ctx, createSubCounty, arg.Name, arg.DistrictID, arg.Code)
	var i SubCounty
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DistrictID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubCounty = `-- name: DeleteSubCounty :exec
DELETE FROM sub_counties
WHERE id = $1
`

func (q *Queries) DeleteSubCounty(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSubCounty, id)
	return err
}

const getSubCountyByID = `-- name: GetSubCountyByID :one
SELECT id, name, district_id, code, created_at, updated_at
FROM sub_counties
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubCountyByID(ctx context.Context, id uuid.UUID) (SubCounty, error) {
	row := q.db.QueryRowContext(ctx, getSubCountyByID, id)
	var i SubCounty
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DistrictID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubCountyByNameAndDistrict = `-- name: GetSubCountyByNameAndDistrict :one
SELECT id, name, district_id, code, created_at, updated_at
FROM sub_counties
WHERE LOWER(name) = LOWER($1)
  AND district_id = $2
LIMIT 1
`

type GetSubCountyByNameAndDistrictParams struct {
	Lower      string    `json:"lower"`
	DistrictID uuid.UUID `json:"district_id"`
}

func (q *Queries) GetSubCountyByNameAndDistrict(ctx context.Context, arg GetSubCountyByNameAndDistrictParams) (SubCounty, error) {
	row := q.db.QueryRowContext(ctx, getSubCountyByNameAndDistrict, arg.Lower, arg.DistrictID)
	var i SubCounty
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DistrictID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubcountyByName = `-- name: GetSubcountyByName :one
SELECT id, name, code, district_id, created_at, updated_at
FROM sub_counties
WHERE LOWER(name) = LOWER($1)
LIMIT 1
`

type GetSubcountyByNameRow struct {
	ID         uuid.UUID      `json:"id"`
	Name       string         `json:"name"`
	Code       sql.NullString `json:"code"`
	DistrictID uuid.UUID      `json:"district_id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

func (q *Queries) GetSubcountyByName(ctx context.Context, name string) (GetSubcountyByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getSubcountyByName, name)
	var i GetSubcountyByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.DistrictID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubCountiesByDistrict = `-- name: ListSubCountiesByDistrict :many
SELECT id, name, district_id, code, created_at, updated_at
FROM sub_counties
WHERE district_id = $1
ORDER BY name ASC
`

func (q *Queries) ListSubCountiesByDistrict(ctx context.Context, districtID uuid.UUID) ([]SubCounty, error) {
	rows, err := q.db.QueryContext(ctx, listSubCountiesByDistrict, districtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubCounty{}
	for rows.Next() {
		var i SubCounty
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DistrictID,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubCounty = `-- name: UpsertSubCounty :one
INSERT INTO sub_counties (
  name,
  district_id,
  code
) VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (name, district_id)
DO UPDATE SET
  code = COALESCE(EXCLUDED.code, sub_counties.code),
  updated_at = now()
RETURNING id, name, district_id, code, created_at, updated_at
`

type UpsertSubCountyParams struct {
	Name       string         `json:"name"`
	DistrictID uuid.UUID      `json:"district_id"`
	Code       sql.NullString `json:"code"`
}

func (q *Queries) UpsertSubCounty(ctx context.Context, arg UpsertSubCountyParams) (SubCounty, error) {
	row := q.db.QueryRowContext(ctx, upsertSubCounty, arg.Name, arg.DistrictID, arg.Code)
	var i SubCounty
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DistrictID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
