// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: surveillance_import.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const completeSurveillanceImportBatch = `-- name: CompleteSurveillanceImportBatch :exec
UPDATE surveillance_import_batches
SET
  status = 'COMPLETED',
  success_rows = $2,
  failed_rows = $3,
  completed_at = now()
WHERE id = $1
`

type CompleteSurveillanceImportBatchParams struct {
	ID          uuid.UUID `json:"id"`
	SuccessRows int32     `json:"success_rows"`
	FailedRows  int32     `json:"failed_rows"`
}

func (q *Queries) CompleteSurveillanceImportBatch(ctx context.Context, arg CompleteSurveillanceImportBatchParams) error {
	_, err := q.db.ExecContext(ctx, completeSurveillanceImportBatch, arg.ID, arg.SuccessRows, arg.FailedRows)
	return err
}

const createImportBatch = `-- name: CreateImportBatch :one
INSERT INTO surveillance_import_batches (
  source_name,
  file_name,
  dataset_type,
  imported_by,
  status,
  notes
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, source_name, file_name, dataset_type, imported_by, imported_at, status, notes, total_rows, success_rows, failed_rows, completed_at
`

type CreateImportBatchParams struct {
	SourceName  string         `json:"source_name"`
	FileName    sql.NullString `json:"file_name"`
	DatasetType string         `json:"dataset_type"`
	ImportedBy  sql.NullString `json:"imported_by"`
	Status      string         `json:"status"`
	Notes       sql.NullString `json:"notes"`
}

func (q *Queries) CreateImportBatch(ctx context.Context, arg CreateImportBatchParams) (SurveillanceImportBatch, error) {
	row := q.db.QueryRowContext(ctx, createImportBatch,
		arg.SourceName,
		arg.FileName,
		arg.DatasetType,
		arg.ImportedBy,
		arg.Status,
		arg.Notes,
	)
	var i SurveillanceImportBatch
	err := row.Scan(
		&i.ID,
		&i.SourceName,
		&i.FileName,
		&i.DatasetType,
		&i.ImportedBy,
		&i.ImportedAt,
		&i.Status,
		&i.Notes,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.CompletedAt,
	)
	return i, err
}

const createImportRawRow = `-- name: CreateImportRawRow :one
INSERT INTO surveillance_import_raw_rows (
  batch_id,
  row_number,
  payload
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id, batch_id, row_number, payload, created_at, status, error_message
`

type CreateImportRawRowParams struct {
	BatchID   uuid.UUID       `json:"batch_id"`
	RowNumber int32           `json:"row_number"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) CreateImportRawRow(ctx context.Context, arg CreateImportRawRowParams) (SurveillanceImportRawRow, error) {
	row := q.db.QueryRowContext(ctx, createImportRawRow, arg.BatchID, arg.RowNumber, arg.Payload)
	var i SurveillanceImportRawRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.RowNumber,
		&i.Payload,
		&i.CreatedAt,
		&i.Status,
		&i.ErrorMessage,
	)
	return i, err
}

const deleteProcessedSurveillanceImportRawRows = `-- name: DeleteProcessedSurveillanceImportRawRows :exec
DELETE FROM surveillance_import_raw_rows
WHERE batch_id = $1
  AND status = 'PROCESSED'
`

func (q *Queries) DeleteProcessedSurveillanceImportRawRows(ctx context.Context, batchID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProcessedSurveillanceImportRawRows, batchID)
	return err
}

const failSurveillanceImportBatch = `-- name: FailSurveillanceImportBatch :exec
UPDATE surveillance_import_batches
SET
  status = 'FAILED',
  notes = $2,
  completed_at = now()
WHERE id = $1
`

type FailSurveillanceImportBatchParams struct {
	ID    uuid.UUID      `json:"id"`
	Notes sql.NullString `json:"notes"`
}

func (q *Queries) FailSurveillanceImportBatch(ctx context.Context, arg FailSurveillanceImportBatchParams) error {
	_, err := q.db.ExecContext(ctx, failSurveillanceImportBatch, arg.ID, arg.Notes)
	return err
}

const getImportBatchByID = `-- name: GetImportBatchByID :one
SELECT id, source_name, file_name, dataset_type, imported_by, imported_at, status, notes, total_rows, success_rows, failed_rows, completed_at
FROM surveillance_import_batches
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetImportBatchByID(ctx context.Context, id uuid.UUID) (SurveillanceImportBatch, error) {
	row := q.db.QueryRowContext(ctx, getImportBatchByID, id)
	var i SurveillanceImportBatch
	err := row.Scan(
		&i.ID,
		&i.SourceName,
		&i.FileName,
		&i.DatasetType,
		&i.ImportedBy,
		&i.ImportedAt,
		&i.Status,
		&i.Notes,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.CompletedAt,
	)
	return i, err
}

const listImportBatches = `-- name: ListImportBatches :many
SELECT id, source_name, file_name, dataset_type, imported_by, imported_at, status, notes, total_rows, success_rows, failed_rows, completed_at
FROM surveillance_import_batches
ORDER BY imported_at DESC
`

func (q *Queries) ListImportBatches(ctx context.Context) ([]SurveillanceImportBatch, error) {
	rows, err := q.db.QueryContext(ctx, listImportBatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveillanceImportBatch{}
	for rows.Next() {
		var i SurveillanceImportBatch
		if err := rows.Scan(
			&i.ID,
			&i.SourceName,
			&i.FileName,
			&i.DatasetType,
			&i.ImportedBy,
			&i.ImportedAt,
			&i.Status,
			&i.Notes,
			&i.TotalRows,
			&i.SuccessRows,
			&i.FailedRows,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportRawRowsByBatch = `-- name: ListImportRawRowsByBatch :many
SELECT id, batch_id, row_number, payload, created_at, status, error_message
FROM surveillance_import_raw_rows
WHERE batch_id = $1
ORDER BY row_number ASC
`

func (q *Queries) ListImportRawRowsByBatch(ctx context.Context, batchID uuid.UUID) ([]SurveillanceImportRawRow, error) {
	rows, err := q.db.QueryContext(ctx, listImportRawRowsByBatch, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveillanceImportRawRow{}
	for rows.Next() {
		var i SurveillanceImportRawRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.RowNumber,
			&i.Payload,
			&i.CreatedAt,
			&i.Status,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSurveillanceImportRawRowFailed = `-- name: MarkSurveillanceImportRawRowFailed :exec
UPDATE surveillance_import_raw_rows
SET status = 'FAILED', error_message = $2
WHERE id = $1
`

type MarkSurveillanceImportRawRowFailedParams struct {
	ID           uuid.UUID      `json:"id"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) MarkSurveillanceImportRawRowFailed(ctx context.Context, arg MarkSurveillanceImportRawRowFailedParams) error {
	_, err := q.db.ExecContext(ctx, markSurveillanceImportRawRowFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markSurveillanceImportRawRowProcessed = `-- name: MarkSurveillanceImportRawRowProcessed :exec
UPDATE surveillance_import_raw_rows
SET status = 'PROCESSED', error_message = NULL
WHERE id = $1
`

func (q *Queries) MarkSurveillanceImportRawRowProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markSurveillanceImportRawRowProcessed, id)
	return err
}

const updateImportBatchStatus = `-- name: UpdateImportBatchStatus :one
UPDATE surveillance_import_batches
SET
  status = $2,
  notes = $3
WHERE id = $1
RETURNING id, source_name, file_name, dataset_type, imported_by, imported_at, status, notes, total_rows, success_rows, failed_rows, completed_at
`

type UpdateImportBatchStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status string         `json:"status"`
	Notes  sql.NullString `json:"notes"`
}

func (q *Queries) UpdateImportBatchStatus(ctx context.Context, arg UpdateImportBatchStatusParams) (SurveillanceImportBatch, error) {
	row := q.db.QueryRowContext(ctx, updateImportBatchStatus, arg.ID, arg.Status, arg.Notes)
	var i SurveillanceImportBatch
	err := row.Scan(
		&i.ID,
		&i.SourceName,
		&i.FileName,
		&i.DatasetType,
		&i.ImportedBy,
		&i.ImportedAt,
		&i.Status,
		&i.Notes,
		&i.TotalRows,
		&i.SuccessRows,
		&i.FailedRows,
		&i.CompletedAt,
	)
	return i, err
}
