// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_rbac.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const assignIHPPermissionToRealmRole = `-- name: AssignIHPPermissionToRealmRole :exec
INSERT INTO ihp_realm_role_permissions (realm_role, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignIHPPermissionToRealmRoleParams struct {
	RealmRole    string    `json:"realm_role"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) AssignIHPPermissionToRealmRole(ctx context.Context, arg AssignIHPPermissionToRealmRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignIHPPermissionToRealmRole, arg.RealmRole, arg.PermissionID)
	return err
}

const assignIHPPermissionToSystemRole = `-- name: AssignIHPPermissionToSystemRole :exec
INSERT INTO ihp_system_role_permissions (system_role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignIHPPermissionToSystemRoleParams struct {
	SystemRoleID uuid.UUID `json:"system_role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) AssignIHPPermissionToSystemRole(ctx context.Context, arg AssignIHPPermissionToSystemRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignIHPPermissionToSystemRole, arg.SystemRoleID, arg.PermissionID)
	return err
}

const assignIHPSystemAccessRole = `-- name: AssignIHPSystemAccessRole :exec
INSERT INTO ihp_system_access_roles (system_id, role_name)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignIHPSystemAccessRoleParams struct {
	SystemID uuid.UUID `json:"system_id"`
	RoleName string    `json:"role_name"`
}

func (q *Queries) AssignIHPSystemAccessRole(ctx context.Context, arg AssignIHPSystemAccessRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignIHPSystemAccessRole, arg.SystemID, arg.RoleName)
	return err
}

const getIHPSystemByClientID = `-- name: GetIHPSystemByClientID :one
SELECT id, client_id, display_name, description, icon, launch_url, category, enabled, sort_order, metadata, created_at, updated_at, owner_team, owner_name, owner_email, support_url, documentation_url, environment, criticality, system_type, display_in_launcher, display_in_sidenav, launch_mode
FROM ihp_systems
WHERE client_id = $1
`

func (q *Queries) GetIHPSystemByClientID(ctx context.Context, clientID string) (IhpSystem, error) {
	row := q.db.QueryRowContext(ctx, getIHPSystemByClientID, clientID)
	var i IhpSystem
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DisplayName,
		&i.Description,
		&i.Icon,
		&i.LaunchUrl,
		&i.Category,
		&i.Enabled,
		&i.SortOrder,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerTeam,
		&i.OwnerName,
		&i.OwnerEmail,
		&i.SupportUrl,
		&i.DocumentationUrl,
		&i.Environment,
		&i.Criticality,
		&i.SystemType,
		&i.DisplayInLauncher,
		&i.DisplayInSidenav,
		&i.LaunchMode,
	)
	return i, err
}

const listEnabledIHPSystems = `-- name: ListEnabledIHPSystems :many
SELECT id, client_id, display_name, description, icon, launch_url, category, enabled, sort_order, metadata, created_at, updated_at, owner_team, owner_name, owner_email, support_url, documentation_url, environment, criticality, system_type, display_in_launcher, display_in_sidenav, launch_mode
FROM ihp_systems
WHERE enabled = TRUE
ORDER BY sort_order ASC, display_name ASC
`

func (q *Queries) ListEnabledIHPSystems(ctx context.Context) ([]IhpSystem, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledIHPSystems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IhpSystem{}
	for rows.Next() {
		var i IhpSystem
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.DisplayName,
			&i.Description,
			&i.Icon,
			&i.LaunchUrl,
			&i.Category,
			&i.Enabled,
			&i.SortOrder,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerTeam,
			&i.OwnerName,
			&i.OwnerEmail,
			&i.SupportUrl,
			&i.DocumentationUrl,
			&i.Environment,
			&i.Criticality,
			&i.SystemType,
			&i.DisplayInLauncher,
			&i.DisplayInSidenav,
			&i.LaunchMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIHPAccessibleSystemsForClientRoles = `-- name: ListIHPAccessibleSystemsForClientRoles :many
SELECT DISTINCT
    s.client_id,
    s.display_name,
    s.launch_url,
    s.icon,
    s.category,
    ARRAY(
        SELECT DISTINCT ar.role_name
        FROM ihp_system_access_roles ar
        WHERE ar.system_id = s.id
          AND ar.role_name = ANY($1::text[])
        ORDER BY ar.role_name ASC
    )::text[] AS roles
FROM ihp_systems s
JOIN ihp_system_access_roles ar ON ar.system_id = s.id
WHERE s.client_id = $2
  AND s.enabled = TRUE
  AND ar.role_name = ANY($1::text[])
ORDER BY s.display_name ASC
`

type ListIHPAccessibleSystemsForClientRolesParams struct {
	RoleNames []string `json:"role_names"`
	ClientID  string   `json:"client_id"`
}

type ListIHPAccessibleSystemsForClientRolesRow struct {
	ClientID    string         `json:"client_id"`
	DisplayName string         `json:"display_name"`
	LaunchUrl   sql.NullString `json:"launch_url"`
	Icon        sql.NullString `json:"icon"`
	Category    sql.NullString `json:"category"`
	Roles       []string       `json:"roles"`
}

func (q *Queries) ListIHPAccessibleSystemsForClientRoles(ctx context.Context, arg ListIHPAccessibleSystemsForClientRolesParams) ([]ListIHPAccessibleSystemsForClientRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listIHPAccessibleSystemsForClientRoles, pq.Array(arg.RoleNames), arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIHPAccessibleSystemsForClientRolesRow{}
	for rows.Next() {
		var i ListIHPAccessibleSystemsForClientRolesRow
		if err := rows.Scan(
			&i.ClientID,
			&i.DisplayName,
			&i.LaunchUrl,
			&i.Icon,
			&i.Category,
			pq.Array(&i.Roles),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIHPPermissions = `-- name: ListIHPPermissions :many
SELECT id, permission_key, display_name, description, category, created_at, updated_at, status, deprecated_at, metadata
FROM ihp_permissions
ORDER BY permission_key ASC
`

func (q *Queries) ListIHPPermissions(ctx context.Context) ([]IhpPermission, error) {
	rows, err := q.db.QueryContext(ctx, listIHPPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IhpPermission{}
	for rows.Next() {
		var i IhpPermission
		if err := rows.Scan(
			&i.ID,
			&i.PermissionKey,
			&i.DisplayName,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.DeprecatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIHPPermissionsForRealmRoles = `-- name: ListIHPPermissionsForRealmRoles :many
SELECT DISTINCT p.permission_key
FROM ihp_realm_role_permissions rrp
JOIN ihp_permissions p ON p.id = rrp.permission_id
WHERE rrp.realm_role = ANY($1::text[])
ORDER BY p.permission_key ASC
`

func (q *Queries) ListIHPPermissionsForRealmRoles(ctx context.Context, realmRoles []string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listIHPPermissionsForRealmRoles, pq.Array(realmRoles))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIHPPermissionsForSystemRoles = `-- name: ListIHPPermissionsForSystemRoles :many
SELECT DISTINCT p.permission_key
FROM ihp_system_role_permissions srp
JOIN ihp_permissions p ON p.id = srp.permission_id
JOIN ihp_system_roles sr ON sr.id = srp.system_role_id
JOIN ihp_systems s ON s.id = sr.system_id
WHERE s.client_id = $1
  AND sr.role_name = ANY($2::text[])
  AND s.enabled = TRUE
  AND sr.enabled = TRUE
ORDER BY p.permission_key ASC
`

type ListIHPPermissionsForSystemRolesParams struct {
	ClientID  string   `json:"client_id"`
	RoleNames []string `json:"role_names"`
}

func (q *Queries) ListIHPPermissionsForSystemRoles(ctx context.Context, arg ListIHPPermissionsForSystemRolesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listIHPPermissionsForSystemRoles, arg.ClientID, pq.Array(arg.RoleNames))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIHPSystemRoles = `-- name: ListIHPSystemRoles :many
SELECT sr.id, sr.system_id, sr.role_name, sr.display_name, sr.description, sr.enabled, sr.metadata, sr.created_at, sr.updated_at
FROM ihp_system_roles sr
JOIN ihp_systems s ON s.id = sr.system_id
WHERE s.client_id = $1
ORDER BY sr.role_name ASC
`

func (q *Queries) ListIHPSystemRoles(ctx context.Context, clientID string) ([]IhpSystemRole, error) {
	rows, err := q.db.QueryContext(ctx, listIHPSystemRoles, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IhpSystemRole{}
	for rows.Next() {
		var i IhpSystemRole
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.RoleName,
			&i.DisplayName,
			&i.Description,
			&i.Enabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIHPSystems = `-- name: ListIHPSystems :many
SELECT id, client_id, display_name, description, icon, launch_url, category, enabled, sort_order, metadata, created_at, updated_at, owner_team, owner_name, owner_email, support_url, documentation_url, environment, criticality, system_type, display_in_launcher, display_in_sidenav, launch_mode
FROM ihp_systems
ORDER BY sort_order ASC, display_name ASC
`

func (q *Queries) ListIHPSystems(ctx context.Context) ([]IhpSystem, error) {
	rows, err := q.db.QueryContext(ctx, listIHPSystems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IhpSystem{}
	for rows.Next() {
		var i IhpSystem
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.DisplayName,
			&i.Description,
			&i.Icon,
			&i.LaunchUrl,
			&i.Category,
			&i.Enabled,
			&i.SortOrder,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerTeam,
			&i.OwnerName,
			&i.OwnerEmail,
			&i.SupportUrl,
			&i.DocumentationUrl,
			&i.Environment,
			&i.Criticality,
			&i.SystemType,
			&i.DisplayInLauncher,
			&i.DisplayInSidenav,
			&i.LaunchMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeIHPPermissionFromRealmRole = `-- name: RemoveIHPPermissionFromRealmRole :exec
DELETE FROM ihp_realm_role_permissions
WHERE realm_role = $1
  AND permission_id = $2
`

type RemoveIHPPermissionFromRealmRoleParams struct {
	RealmRole    string    `json:"realm_role"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) RemoveIHPPermissionFromRealmRole(ctx context.Context, arg RemoveIHPPermissionFromRealmRoleParams) error {
	_, err := q.db.ExecContext(ctx, removeIHPPermissionFromRealmRole, arg.RealmRole, arg.PermissionID)
	return err
}

const removeIHPPermissionFromSystemRole = `-- name: RemoveIHPPermissionFromSystemRole :exec
DELETE FROM ihp_system_role_permissions
WHERE system_role_id = $1
  AND permission_id = $2
`

type RemoveIHPPermissionFromSystemRoleParams struct {
	SystemRoleID uuid.UUID `json:"system_role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) RemoveIHPPermissionFromSystemRole(ctx context.Context, arg RemoveIHPPermissionFromSystemRoleParams) error {
	_, err := q.db.ExecContext(ctx, removeIHPPermissionFromSystemRole, arg.SystemRoleID, arg.PermissionID)
	return err
}

const removeIHPSystemAccessRole = `-- name: RemoveIHPSystemAccessRole :exec
DELETE FROM ihp_system_access_roles
WHERE system_id = $1
  AND role_name = $2
`

type RemoveIHPSystemAccessRoleParams struct {
	SystemID uuid.UUID `json:"system_id"`
	RoleName string    `json:"role_name"`
}

func (q *Queries) RemoveIHPSystemAccessRole(ctx context.Context, arg RemoveIHPSystemAccessRoleParams) error {
	_, err := q.db.ExecContext(ctx, removeIHPSystemAccessRole, arg.SystemID, arg.RoleName)
	return err
}

const upsertIHPPermission = `-- name: UpsertIHPPermission :one
INSERT INTO ihp_permissions (
    permission_key,
    display_name,
    description,
    category
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (permission_key) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    updated_at = now()
RETURNING id, permission_key, display_name, description, category, created_at, updated_at, status, deprecated_at, metadata
`

type UpsertIHPPermissionParams struct {
	PermissionKey string         `json:"permission_key"`
	DisplayName   sql.NullString `json:"display_name"`
	Description   sql.NullString `json:"description"`
	Category      sql.NullString `json:"category"`
}

func (q *Queries) UpsertIHPPermission(ctx context.Context, arg UpsertIHPPermissionParams) (IhpPermission, error) {
	row := q.db.QueryRowContext(ctx, upsertIHPPermission,
		arg.PermissionKey,
		arg.DisplayName,
		arg.Description,
		arg.Category,
	)
	var i IhpPermission
	err := row.Scan(
		&i.ID,
		&i.PermissionKey,
		&i.DisplayName,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.DeprecatedAt,
		&i.Metadata,
	)
	return i, err
}

const upsertIHPSystem = `-- name: UpsertIHPSystem :one
INSERT INTO ihp_systems (
    client_id,
    display_name,
    description,
    icon,
    launch_url,
    category,
    enabled,
    sort_order,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (client_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    icon = EXCLUDED.icon,
    launch_url = EXCLUDED.launch_url,
    category = EXCLUDED.category,
    enabled = EXCLUDED.enabled,
    sort_order = EXCLUDED.sort_order,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, client_id, display_name, description, icon, launch_url, category, enabled, sort_order, metadata, created_at, updated_at, owner_team, owner_name, owner_email, support_url, documentation_url, environment, criticality, system_type, display_in_launcher, display_in_sidenav, launch_mode
`

type UpsertIHPSystemParams struct {
	ClientID    string          `json:"client_id"`
	DisplayName string          `json:"display_name"`
	Description sql.NullString  `json:"description"`
	Icon        sql.NullString  `json:"icon"`
	LaunchUrl   sql.NullString  `json:"launch_url"`
	Category    sql.NullString  `json:"category"`
	Enabled     bool            `json:"enabled"`
	SortOrder   int32           `json:"sort_order"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) UpsertIHPSystem(ctx context.Context, arg UpsertIHPSystemParams) (IhpSystem, error) {
	row := q.db.QueryRowContext(ctx, upsertIHPSystem,
		arg.ClientID,
		arg.DisplayName,
		arg.Description,
		arg.Icon,
		arg.LaunchUrl,
		arg.Category,
		arg.Enabled,
		arg.SortOrder,
		arg.Metadata,
	)
	var i IhpSystem
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.DisplayName,
		&i.Description,
		&i.Icon,
		&i.LaunchUrl,
		&i.Category,
		&i.Enabled,
		&i.SortOrder,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerTeam,
		&i.OwnerName,
		&i.OwnerEmail,
		&i.SupportUrl,
		&i.DocumentationUrl,
		&i.Environment,
		&i.Criticality,
		&i.SystemType,
		&i.DisplayInLauncher,
		&i.DisplayInSidenav,
		&i.LaunchMode,
	)
	return i, err
}

const upsertIHPSystemRole = `-- name: UpsertIHPSystemRole :one
INSERT INTO ihp_system_roles (
    system_id,
    role_name,
    display_name,
    description,
    enabled,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (system_id, role_name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    enabled = EXCLUDED.enabled,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, system_id, role_name, display_name, description, enabled, metadata, created_at, updated_at
`

type UpsertIHPSystemRoleParams struct {
	SystemID    uuid.UUID       `json:"system_id"`
	RoleName    string          `json:"role_name"`
	DisplayName sql.NullString  `json:"display_name"`
	Description sql.NullString  `json:"description"`
	Enabled     bool            `json:"enabled"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) UpsertIHPSystemRole(ctx context.Context, arg UpsertIHPSystemRoleParams) (IhpSystemRole, error) {
	row := q.db.QueryRowContext(ctx, upsertIHPSystemRole,
		arg.SystemID,
		arg.RoleName,
		arg.DisplayName,
		arg.Description,
		arg.Enabled,
		arg.Metadata,
	)
	var i IhpSystemRole
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.RoleName,
		&i.DisplayName,
		&i.Description,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
