// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countDisabledUsers = `-- name: CountDisabledUsers :one
SELECT COUNT(*)
FROM users
WHERE enabled = false
`

func (q *Queries) CountDisabledUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDisabledUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewUsersThisWeek = `-- name: CountNewUsersThisWeek :one
SELECT COUNT(*)
FROM users
WHERE created_at >= DATE_TRUNC('week', CURRENT_DATE)
`

func (q *Queries) CountNewUsersThisWeek(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNewUsersThisWeek)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewUsersToday = `-- name: CountNewUsersToday :one
SELECT COUNT(*)
FROM users
WHERE DATE(created_at) = CURRENT_DATE
`

func (q *Queries) CountNewUsersToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNewUsersToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO users (
    id, username, first_name, last_name, email, enabled, roles
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type CreateUserParams struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Email     string         `json:"email"`
	Enabled   sql.NullBool   `json:"enabled"`
	Roles     []string       `json:"roles"`
}

// =====================================================
// Users
// =====================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Enabled,
		pq.Array(arg.Roles),
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, first_name, last_name, email, enabled, roles, created_at, updated_at, last_login_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Enabled,
		pq.Array(&i.Roles),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, first_name, last_name, email, enabled, roles, created_at, updated_at, last_login_at
FROM users
WHERE LOWER(username) = LOWER($1)
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Enabled,
		pq.Array(&i.Roles),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT id, username, first_name, last_name, email, enabled, roles, created_at, updated_at, last_login_at
FROM users
WHERE roles = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUsersByRole(ctx context.Context, roles []string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByRole, pq.Array(roles))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Enabled,
			pq.Array(&i.Roles),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, first_name, last_name, email, enabled, roles, created_at, updated_at, last_login_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Enabled,
			pq.Array(&i.Roles),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPaged = `-- name: ListUsersPaged :many
SELECT id, username, first_name, last_name, email, enabled, roles, created_at, updated_at, last_login_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsersPaged(ctx context.Context, arg ListUsersPagedParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Enabled,
			pq.Array(&i.Roles),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const neverLoggedInUsers = `-- name: NeverLoggedInUsers :many
SELECT
    u.id,
    u.username,
    u.first_name,
    u.last_name,
    u.email,
    u.enabled,
    u.roles,
    u.created_at,
    u.updated_at,
    u.last_login_at
FROM users u
WHERE NOT EXISTS (
    SELECT 1 FROM audit_logs a
    WHERE a.user_id = u.id
      AND a.action = 'login'
      AND COALESCE((a.metadata->>'success')::boolean, false) = true
)
`

func (q *Queries) NeverLoggedInUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, neverLoggedInUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Enabled,
			pq.Array(&i.Roles),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newUsersInRange = `-- name: NewUsersInRange :many
SELECT
    id,
    username,
    first_name,
    last_name,
    email,
    enabled,
    roles,
    created_at,
    updated_at,
    last_login_at
FROM users
WHERE created_at BETWEEN $1 AND $2
ORDER BY created_at DESC
`

type NewUsersInRangeParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

func (q *Queries) NewUsersInRange(ctx context.Context, arg NewUsersInRangeParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, newUsersInRange, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Enabled,
			pq.Array(&i.Roles),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newUsersTrend = `-- name: NewUsersTrend :many
SELECT
  DATE(created_at) AS day,
  COUNT(*) AS new_users
FROM users
WHERE created_at BETWEEN $1 AND $2
GROUP BY day
ORDER BY day
`

type NewUsersTrendParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type NewUsersTrendRow struct {
	Day      time.Time `json:"day"`
	NewUsers int64     `json:"new_users"`
}

func (q *Queries) NewUsersTrend(ctx context.Context, arg NewUsersTrendParams) ([]NewUsersTrendRow, error) {
	rows, err := q.db.QueryContext(ctx, newUsersTrend, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewUsersTrendRow{}
	for rows.Next() {
		var i NewUsersTrendRow
		if err := rows.Scan(&i.Day, &i.NewUsers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleDistribution = `-- name: RoleDistribution :many
SELECT roles, COUNT(*) AS count
FROM users
GROUP BY roles
`

type RoleDistributionRow struct {
	Roles []string `json:"roles"`
	Count int64    `json:"count"`
}

func (q *Queries) RoleDistribution(ctx context.Context) ([]RoleDistributionRow, error) {
	rows, err := q.db.QueryContext(ctx, roleDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleDistributionRow{}
	for rows.Next() {
		var i RoleDistributionRow
		if err := rows.Scan(pq.Array(&i.Roles), &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, first_name, last_name, email, enabled, roles, created_at, updated_at, last_login_at
FROM users
WHERE 
    username ILIKE '%' || $1 || '%' OR
    email ILIKE '%' || $1 || '%' OR
    first_name ILIKE '%' || $1 || '%' OR
    last_name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
`

func (q *Queries) SearchUsers(ctx context.Context, dollar_1 sql.NullString) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Enabled,
			pq.Array(&i.Roles),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = $2,
    first_name = $3,
    last_name = $4,
    email = $5,
    enabled = $6,
    roles = $7,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Email     string         `json:"email"`
	Enabled   sql.NullBool   `json:"enabled"`
	Roles     []string       `json:"roles"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Enabled,
		pq.Array(arg.Roles),
	)
	return err
}

const updateUserEnabled = `-- name: UpdateUserEnabled :exec
UPDATE users
SET enabled = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserEnabledParams struct {
	ID      uuid.UUID    `json:"id"`
	Enabled sql.NullBool `json:"enabled"`
}

func (q *Queries) UpdateUserEnabled(ctx context.Context, arg UpdateUserEnabledParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEnabled, arg.ID, arg.Enabled)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLogin, id)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (
    id,
    username,
    email,
    first_name,
    last_name,
    enabled,
    created_at,
    updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
ON CONFLICT (id)
DO UPDATE SET
    username   = EXCLUDED.username,
    email      = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name  = EXCLUDED.last_name,
    enabled    = EXCLUDED.enabled,
    updated_at = NOW()
`

type UpsertUserParams struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	Email     string         `json:"email"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Enabled   sql.NullBool   `json:"enabled"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Enabled,
	)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
  SELECT 1 FROM users WHERE id = $1
)
`

func (q *Queries) UserExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
