-- This migration intentionally has no automatic rollback. It merges role and
-- governance data from a retired Keycloak client into Data & Statistics;
-- recreating the obsolete client would make authorization ambiguous.
