export type BackendErrorCode =
  | "CLIENT_ALREADY_EXISTS"
  | "USER_ALREADY_EXISTS"
  | "INVALID_CLIENT_ID"
  | "VALIDATION_FAILED"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "CLIENT_DISABLED"
  | "USER_DISABLED"
  | "RATE_LIMITED"
  | "INTERNAL_ERROR";
