# ==================================================
# DEV VALUES (Ingress Disabled)
# Port-forward based development
# ==================================================

global:
  namespace: sso-dev
  environment: development

imagePullSecrets:
  - name: ghcr-secret

# --------------------------------------------------
# Ingress (Disabled in Dev)
# --------------------------------------------------
ingress:
  enabled: true

keycloakIngress:
  enabled: true

# --------------------------------------------------
# Backend
# --------------------------------------------------
backend:
  env:
    # Frontend will be accessed via localhost:3000
    ALLOWED_ORIGINS: "https//portal.local"

  baseUrl: "https://portal.local"

  secrets:
    KEYCLOAK_ADMIN_CLIENT_SECRET: dashboard-admin-secret
    KEYCLOAK_WEB_CLIENT_SECRET: dashboard-web-secret

# --------------------------------------------------
# Frontend
# --------------------------------------------------
frontend:
  enabled: true

  baseUrl: "https://portal.local"
  # Browser will hit backend via port-forward
  apiBaseUrl: "https://portal.local"

# --------------------------------------------------
# Postgres (App DB)
# --------------------------------------------------
postgresApp:
  auth:
    password: postgres

# --------------------------------------------------
# Postgres (Keycloak DB)
# --------------------------------------------------
postgresKeycloak:
  auth:
    password: keycloak

# --------------------------------------------------
# Keycloak (Internal for Dev)
# --------------------------------------------------
keycloak:
  admin:
    password: admin

  publicBaseUrl: "https://portal.local"
  external:
    enabled: false

  config:
    KC_HTTP_ENABLED: "false"
    KC_HEALTH_ENABLED: "true"
    KC_METRICS_ENABLED: "true"

    # Dev: disable strict hostname validation
    KC_HOSTNAME_STRICT: "true"
    KC_HOSTNAME_STRICT_HTTPS: "true"

# --------------------------------------------------
# Redis
# --------------------------------------------------
redis:
  enabled: true
