# ==================================================
# PRODUCTION VALUES
# External Enterprise Keycloak
# ==================================================

global:
  namespace: sso-prod
  environment: production

imagePullSecrets:
  - name: ghcr-secret

# --------------------------------------------------
# Frontend + Backend Ingress
# --------------------------------------------------
ingress:
  enabled: true
  className: nginx
  host: sso.moh.go.ug
  tls:
    enabled: true
    secretName: sso-prod-tls

# --------------------------------------------------
# Backend
# --------------------------------------------------
backend:
  replicas: 3

  env:
    ALLOWED_ORIGINS: "https://sso.moh.go.ug"

  secrets:
    KEYCLOAK_ADMIN_CLIENT_SECRET: ""
    KEYCLOAK_WEB_CLIENT_SECRET: ""

# --------------------------------------------------
# Frontend
# --------------------------------------------------
frontend:
  replicas: 3

# --------------------------------------------------
# Postgres (App DB)
# --------------------------------------------------
postgresApp:
  auth:
    password: prod_app_db_password

# --------------------------------------------------
# Disable Keycloak DB (external)
# --------------------------------------------------
postgresKeycloak:
  enabled: false

# --------------------------------------------------
# Keycloak (EXTERNAL)
# --------------------------------------------------
keycloak:
  enabled: false

  external:
    enabled: true
    baseUrl: "https://auth.moh.go.ug"
    realm: "MoH"

# --------------------------------------------------
# Redis
# --------------------------------------------------
redis:
  enabled: true
