parent=keycloak.v3
import=common/keycloak
title=MOH Account Console
description=Manage your Ministry of Health Integrated Health Portal account, sign-in methods, sessions, and connected applications.
logo=img/logo.png
logoUrl=/
favIcon=img/logo.png
favIconType=image/png
styles=css/styles.css
deprecatedMode=false
