{{- if .Values.keycloak.enabled }}

# =====================================================
# Keycloak Base Configuration
# =====================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-config
  labels:
    {{- include "moh-sso.labels" . | nindent 4 }}
data:
  KC_DB: {{ .Values.keycloak.config.KC_DB | quote }}
  KC_DB_URL: {{ printf "jdbc:postgresql://%s-postgres-keycloak:5432/%s" .Release.Name .Values.postgresKeycloak.auth.database | quote }}

  KC_HTTP_ENABLED: {{ .Values.keycloak.config.KC_HTTP_ENABLED | quote }}
  KC_PROXY: {{ .Values.keycloak.config.KC_PROXY | quote }}

  KC_HOSTNAME: {{ .Values.keycloak.config.KC_HOSTNAME | quote }}
  KC_HOSTNAME_STRICT: {{ .Values.keycloak.config.KC_HOSTNAME_STRICT | quote }}
  KC_HOSTNAME_STRICT_HTTPS: {{ .Values.keycloak.config.KC_HOSTNAME_STRICT_HTTPS | quote }}
  KC_HEALTH_ENABLED: {{.Values.keycloak.config.KC_HEALTH_ENABLED | quote}}

  KC_LOG_LEVEL: {{ .Values.keycloak.config.KC_LOG_LEVEL | quote }}

---
# =====================================================
# Keycloak Admin Credentials
# =====================================================
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-admin
  labels:
    {{- include "moh-sso.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.keycloak.admin.username | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password | quote }}

---
# =====================================================
# Keycloak Database Credentials
# =====================================================
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-db
  labels:
    {{- include "moh-sso.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_DB_USERNAME: {{ .Values.postgresKeycloak.auth.username | quote }}
  KC_DB_PASSWORD: {{ .Values.postgresKeycloak.auth.password | quote }}

{{- end }}

# =====================================================
# DEV ONLY — Realm Import ConfigMap
# =====================================================
{{- if and .Values.keycloak.enabled (eq .Values.global.environment "development") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  labels:
    {{- include "moh-sso.labels" . | nindent 4 }}
data:
  realm-export.json: |
{{ .Files.Get "files/dev/realm-export.json" | indent 4 }}
{{- end }}
