export const microfrontendRoutes = {
  announcements: "/admin/announcements",
  audit: "/admin/audit-logs",
  clients: "/admin/clients",
  dataValidation: "/apps/dwh/data-validation",
  dataVisualizer: "/apps/dwh/data-visualizer",
  documents: "/apps/dwh/filesvr",
  eServices: "/apps/eservices",
  email: "/admin/emails",
  issueTracker: "/apps/dwh/issue-tracker",
  reportBrowser: "/apps/dwh/reports",
  surveillance: "/apps/dwh/surveillance",
  users: "/admin/users",
  utilities: "/apps/utilities/self-service",
} as const;
