parent=keycloak.v2
import=common/keycloak
title=MOH Identity Administration
description=Administer Ministry of Health realms, users, clients, roles, permissions, and identity providers.
logo=img/logo.png
logoUrl=/
favIcon=img/logo.png
favIconType=image/png
styles=css/styles.css
