import type { Permission } from "./auth.types";

export const PERMISSIONS = {
  portalAccess: "portal:access",
  systemsRead: "systems:read",
  systemsLaunch: "systems:launch",
  usersRead: "users:read",
  usersWrite: "users:write",
  usersRolesWrite: "users:roles:write",
  clientsRead: "clients:read",
  clientsWrite: "clients:write",
  clientsRolesWrite: "clients:roles:write",
  announcementsRead: "announcements:read",
  announcementsWrite: "announcements:write",
  announcementsPublish: "announcements:publish",
  documentsRead: "documents:read",
  documentsWrite: "documents:write",
  documentsProcess: "documents:process",
  documentTemplatesRead: "document_templates:read",
  documentTemplatesWrite: "document_templates:write",
  documentTemplatesPublish: "document_templates:publish",
  surveillanceRead: "surveillance:read",
  surveillanceImport: "surveillance:import",
  surveillanceManageLocations: "surveillance:manage_locations",
  surveillanceManageAlerts: "surveillance:manage_alerts",
  emailRead: "email:read",
  emailSend: "email:send",
  emailManage: "email:manage",
  storageLocationsRead: "storage_locations:read",
  storageLocationsWrite: "storage_locations:write",
  dataQualityRead: "data_quality:read",
  dataQualityWrite: "data_quality:write",
  dataQualityResolve: "data_quality:resolve",
  reportBrowserRead: "report_browser:read",
  outbreakAccess: "outbreak:access",
  outbreakManage: "outbreak:manage",
  metricsRead: "metrics:read",
  auditRead: "audit:read",
  notificationsRead: "notifications:read",
  notificationsWrite: "notifications:write",
  rbacRead: "rbac:read",
  rbacWrite: "rbac:write",
  rbacRolesWrite: "rbac:roles:write",
  rbacPermissionsWrite: "rbac:permissions:write",
} as const satisfies Record<string, Permission>;
